redhat-developer/rhdh

- catalog-info.yaml
- Updated catalog-info in preparation for GitHub issues plugin
N/A
> Update catalog-info in preparation for GitHub issues plugin

- app-config.yaml
- catalog-entities/components.yaml
- github-app-backstage-showcase-credentials.yaml
- packages/app/package.json
- packages/app/src/components/catalog/EntityPage.tsx
- packages/backend/package.json
- packages/backend/src/index.ts
- packages/backend/src/plugins/kubernetes.ts
- yarn.lock
- Adds the kubernetes plugin
- Fixes multiline support for the github app private key
Fixes https://github.com/janus-idp/backstage-showcase/issues/5
> Add the kubernetes plugin

- manifests/base/deployment.yaml
- manifests/base/ingress.yaml
- manifests/base/kustomization.yaml
- manifests/base/service.yaml
This PR is to update the namespace from backstage to janus-idp for deployment to Operate First
Fixes #?
> Update the namespace in the manifests

- manifests/base/certificate.yaml
- manifests/base/ingress.yaml
- manifests/base/issuer.yaml
- manifests/base/kustomization.yaml
This PR is to add the Issuer and Certificate to the manifests. It also updates the ingress route and fixes an issue with the external secret.
Fixes #?
> Add the issuer and certificate

- manifests/base/deployment.yaml
Updates the secret to match the External Secret
Fixes #?
> Update the secret in deployment

- manifests/base/certificate.yaml
- manifests/base/ingress.yaml
This PR updates the domains to use the operate first cluster domain for deployment. This will be updated whenever we have a proper domain setup.
Fixes #?
> Update the domains

- manifests/base/externalsecret.yaml
This PR is to update the refresh interval of the External Secret to 60 seconds. 
Fixes #?
> Update the refresh in external secret

- manifests/base/deployment.yaml
Currently, the old tag is missing some features that are present in the backstage-showcase app. This latest tag will be an image that includes the most recent updates to backstage-showcase. I am using an different tag in case there are any issues and we need to revert back.
Fixes #?
> Update the image tag

- .github/workflows/docker-build.yaml
- manifests/base/deployment.yaml
Publish the image to GitHub Container registry
Fixes #11
> Publish Image to ghcr

- packages/app/public/homepage/data.json
- packages/app/src/components/catalog/EntityPage.tsx
- packages/app/src/components/home/HomePage.tsx
- software-templates/scaffolder-templates/nodejs-github-actions-template/template.yaml
> Update the Entity page and add temp Dev Spaces link

- packages/app/src/components/catalog/EntityPage.tsx
> Update the Entity page

- app-config.yaml
Fixes the example data not showing up within the catalog. 
Fixes #?
> Fix example data

- Dockerfile
- catalog-entities/components.yaml
- packages/app/src/components/catalog/EntityPage.tsx
> Add a template and minor UI fixes

- packages/app/src/components/catalog/EntityPage.tsx
> Update Entity page

- app-config.yaml
The example data is not showing up when we deploy. This is because the path changes whenever we build the image. Updating the app config to include paths for whenever we build the image will fix the issue.
Fixes #?
> Update the example data

- packages/app/package.json
- packages/app/public/tech-radar/data-default.json
- packages/app/src/App.tsx
- packages/app/src/apis.ts
- packages/app/src/lib/CustomTechRadar.ts
- yarn.lock
Adds the tech radar with custom data
Fixes https://github.com/janus-idp/backstage-showcase/issues/25
> Add custom tech radar

- app-config.yaml
Move from local software templates to remote url 
Fixes #65
> Update add remote Location to load templates

- manifests/base/certificate.yaml
- manifests/base/ingress.yaml
This PR is to add the showcase.janus-idp.io URL to the backstage-showcase app
Fixes #?
> Add the showcase URL

- .github/workflows/codeql.yml
- packages/app/package.json
- packages/app/src/components/catalog/EntityPage.tsx
- yarn.lock
* Add GitHub Security Inshigts plugin
* Fix the relations graph in the dependencies tab
* Add all the relation card in the dependencies tab
* 
Fixes #80 & #66
> Add gh security and fixes

- manifests/base/kustomization.yaml
Temporarily removing the ingress to fix cert issues
Fixes #?
> Temporary remove ingress

- manifests/base/ingress.yaml
- manifests/base/kustomization.yaml
This PR is to add back the ingress now that the certs have been applied.
Fixes #?
> Replace ingress

- packages/app/package.json
- packages/app/src/components/home/HomePage.tsx
If a user is using the old url, the alert will be shown on the home page.
Fixes #?
> Add new url alert if using old url

- package.json
- yarn.lock
Update project dependencies
N/A
> Update workspace deps

- README.md
- docs/getting-started.md
This PR adds getting started documentation for those who wish to run the Backstage Showcase locally. There has been some recent interest in this.
Fixes #?
> Add Getting Started documentation

- packages/app/public/tech-radar/data-default.json
Update the Tech Radar page with more data
Fixes #59
> Add more data to the Tech Radar page

- Dockerfile
This PR fixes a bug that was introduced whenever we removed the software templates. 
Fixes #?
> Remove softwate templates from Dockerfile

- packages/app/package.json
- packages/app/src/components/catalog/EntityPage.tsx
- yarn.lock
This PR adds the topology plugin to the showcase app. The tab is placed after the Kubernetes tab and will show in the website and service entities pages.
Fixes #73
> Add topology plugin

- catalog-entities/components.yaml
- catalog-info.yaml
Update the Catalog info to match the component, add an additional annotation for the backstage Kubernetes namespace
Fixes #?
> Update the catalog-info

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/enhancement.md
- .github/ISSUE_TEMPLATE/feature.md
- .github/PULL_REQUEST_TEMPLATE.md
Add defaults templates when bug/feature/enhancement issues are created. Also updating the PR template
Fixes #78
> Add issue templates and update PR template

- DCO
- LICENSE
Add the LICENSE file and DCO for contributions.
- Fixes #? N/A
> Add LICENSE and DCO

- README.md
- docs/helm-chart.md
Updated to the README to better explain to purpose of this project as well as add some community resources. Also, went and put a warning at the top of the Helm Chart documentation as it needs to be updated. This can be done at a later date if there is more interest in deploying with the Helm Chart.
- Fixes #10 
- Fixes #108 
> Add more to README

- app-config.yaml
Currently the showcase app is unable to get the information about the bucket region from the OBC. 
- Fixes #?
> Fix for Techdocs

- .github/workflows/techdocs.yaml
- app-config.yaml
- docs/index.md
Triggers the Techdocs GitHub Actions to begin building the Techdocs for the showcase app, fixes possible build error, adds force path to app-config
- Fixes #?
> Trigger Techdocs GH actions

- .github/workflows/techdocs.yaml
Reverts a fix I made earlier that was not necessary.
- Fixes #?
> Revert Techdocs fix

- app-config.yaml
- packages/backend/src/plugins/catalog.ts
- showcase-docs/getting-started.md
added support for github org data provider.
The backstage example had some information hardcoded. @christophe-f can you help me parameterize them?
- Fixes #115 
> added support for github org data provider

- .github/workflows/docker-build.yaml
- catalog-entities/components.yaml
- packages/app/package.json
- packages/backend/package.json
- yarn.lock
- Adds cache to docker-build workflow
- Updates deps
- Fixes https://github.com/janus-idp/backstage-showcase/issues/131
> Add caching to docker-build workflow and update deps

- .github/workflows/techdocs.yaml
* Add the AWS_REGION variable that was removed from previous PR
* Externalize the AWS_ENDPOINT to an environment variable
- Fixes #?
> Re add the AWS region

- packages/app/package.json
- yarn.lock
Updates Topology plugin to latest version
- Fixes https://github.com/janus-idp/backstage-showcase/issues/152
> Update Topology plugin

- README.md
- app-config.yaml
- catalog-entities/components.yaml
- packages/backend/src/plugins/catalog.ts
- showcase-docs/getting-started.md
- Externalize the OBC url in the app-config.yaml with BUCKET_URL env variable
- Add the SonarQube annotation to the showcase catalog-info.yaml
- Remove duplicate import in the catalog.ts
- Update the Getting Started page with the Techdocs S3 information
- Add missing plugin in the README list
- Fixes #?
> Various fixes

- .github/workflows/ci.yaml
- .github/workflows/docker-build.yaml
- .github/workflows/techdocs.yaml
- Dockerfile
- app-config.yaml
- showcase-docs/getting-started.md
Externalize Techdocs config so a user can use with or without a pipeline.
- Fixes #160 
> Externalize Techdocs config

- Dockerfile
- app-config.production.yaml
- manifests/base/deployment.yaml
Now, that the db has stabilized in the namespace, we are able to add it to the deployment and showcase app.
- Fixes #?
> Add postgres db to showcase

- app-config.production.yaml
- app-config.yaml
- manifests/base/deployment.yaml
- manifests/base/ingress.yaml
- manifests/base/service.yaml
- packages/app/src/App.test.tsx
- packages/app/src/App.tsx
- packages/backend/src/plugins/auth.ts
Reverts janus-idp/backstage-showcase#150
> Revert "Keycloak auth"

- app-config.yaml
Fix a small typo in the comments
> fix: comments Typo

- catalog-entities/components/showcase.yaml
Change Showcase link to showcase.janus-idp.io
- Fixes https://github.com/janus-idp/backstage-showcase/issues/200
> Change Showcase link to showcase.janus-idp.io

- app-config.yaml
- packages/backend/package.json
- packages/backend/src/index.ts
- packages/backend/src/plugins/sonarqube.ts
- showcase-docs/getting-started.md
- yarn.lock
* The data is showing on the Overview page
* Add the SonarQube backend
* Make the plugin configurable to avoid a startup crash if the values were required
- Fixes #164 
> Fix the SonarQube plugin integration

- packages/app/public/homepage/data.json
- packages/app/public/learning-paths/data.json
- packages/app/src/App.tsx
- packages/app/src/common.tsx
- packages/app/src/components/Root/Root.tsx
- packages/app/src/components/home/HomePage.tsx
- packages/app/src/components/learningPaths/LearningPathsPage.tsx
- Create a dedicated learning paths page
- Move some shared components by the home page to `common.tsx` 
- Fixes #211
Screenshots in the comments.
> feat: Create learning paths page

- app-config.yaml
- catalog-entities/all.yaml
- catalog-entities/apis.yaml
- catalog-entities/apis/petstore.yaml
- packages/app/src/components/catalog/EntityPage/Pages/Api.tsx
- packages/backend/package.json
- packages/backend/src/plugins/catalog.ts
- yarn.lock
Add Petstore API component
N/A
> Add Petstore API component

- app-config.yaml
- catalog-entities/apis/petstore.yaml
> Fix Petstore API

- packages/app/src/components/learningPaths/LearningPathsPage.tsx
Make links in learning paths page to open in a new tab.
- Fixes #224 
> feat: Open learning path link in a new tab

- packages/app/public/learning-paths/data.json
- packages/app/src/components/learningPaths/LearningPathsPage.tsx
Update the `data.json` file with more learning paths. The data was generated using a scraper available at https://github.com/SamoKopecky/rh-learning-paths-scraper
- Fixes none
Screenshot
> chore: Add more learning paths

- package.json
> remove unused script

- Dockerfile
> Remove echo in dockerfile

- .github/workflows/ci.yaml
- .github/workflows/docker-build.yaml
> Add workflow dispatch to ci and docker build actions

- Dockerfile
- packages/backend/package.json
> Fix dockerfile

- packages/app/package.json
- yarn.lock
This PR updates the version of `@janus-idp/backstage-plugin-topology` from
1.5.1 -> 1.5.3
> Update topology plugin version

- packages/app/public/homepage/data.json
- packages/app/public/homepage/icons/keycloak.svg
Adds Keycloak link to Showcase Homepage
- Fixes https://github.com/janus-idp/backstage-showcase/issues/179
> Add Keycloak link to Showcase Homepage

- app-config.yaml
- showcase-docs/getting-started.md
Removes duplicated environment variables in the app-config.yaml
- Fixes https://github.com/janus-idp/backstage-showcase/issues/218
> Remove duplicated environment variables in the app-config.yaml

- .changeset/honest-swans-flow.md
- README.md
- app-config.yaml
- packages/app/package.json
- packages/app/src/components/catalog/EntityPage/Content/CI.tsx
- packages/app/src/components/catalog/EntityPage/Content/Issues.tsx
- packages/app/src/components/catalog/EntityPage/Content/PullRequests.tsx
- showcase-docs/getting-started.md
- yarn.lock
- Adds the Jira plugin
- Changes GitHub cards to be the lowest priority on `<EntitySwitch />`s
- Fixes https://github.com/janus-idp/backstage-showcase/issues/171
> Add Jira plugin

- .github/workflows/ci.yaml
- .github/workflows/docker-build.yaml
- .github/workflows/techdocs.yaml
Updates paths-ignore to include .changeset/**
N/A
> Update paths-ignore to include .changeset/**

- .github/workflows/ci.yaml
- .github/workflows/codeql.yaml
- .github/workflows/docker-build.yaml
Ignores changeset-release/** branches on GH actions
N/A
> Ignore changeset-release/** branches on GH actions

- packages/app/src/components/catalog/EntityPage/Content/Issues.tsx
Be able to view the GitHub Issues
- Fixes #?
> Re add the GitHub Issues in the tab

- .github/workflows/ci.yaml
- Dockerfile
- README.md
- app-config.basic.yaml
- app-config.yaml
- github-app-backstage-showcase-credentials.yaml
- package.json
- packages/app/package.json
- packages/app/src/apis.ts
- showcase-docs/getting-started.md
- yarn.lock
- Fixes https://github.com/janus-idp/backstage-showcase/issues/165
> Add Segment Analytics to Showcase

- mkdocs.yaml
Now that we have a few pages with documentation, we don't need to show the 'section in progress'
- Fixes #?
> Remove the 'section in progress'

- packages/app/src/App.tsx
- packages/app/src/components/catalog/EntityPage/Content/Issues.tsx
- yarn.lock
> Fix issues tab

- .github/workflows/ci.yaml
- Dockerfile
Update dockerfile and update ci workflow
- Fixes #?
> Update dockerfile and update ci workflow

- packages/app/package.json
- packages/app/src/App.tsx
- packages/app/src/components/catalog/EntityPage/Pages/Resource.tsx
- packages/backend/package.json
- packages/backend/src/plugins/catalog.ts
- yarn.lock
Update OCM plugin to v3 including UI view changes as per https://github.com/janus-idp/backstage-plugins/issues/107
- Closes https://github.com/janus-idp/backstage-plugins/issues/368
> feat(ocm): update to v3.0.x of OCM

- package.json
- yarn.lock
Pins package resolutions
Required in downstream
> fix(deps): pin package resolutions

- app-config.example.yaml
- app-config.production.yaml
- app-config.yaml
Fixes indenting and quotations in app-config for consistency
N/A
> style: fix app-config indenting

- .github/renovate.json
Adds renovate bot
@christophe-f can you enable the renovate bot on the showcase?
- Fixes https://github.com/janus-idp/backstage-showcase/issues/316
> feat(renovate): add renovate bot

- catalog-entities/components/showcase.yaml
A small PR to update the showcase catalog component for the ROSA cluster. Without these changes, the Kubernetes plugin is unable to find the showcase resources in the cluster.
- Fixes #?
> Update showcase catalog for ROSA

- packages/app/public/homepage/data.json
- packages/app/public/homepage/icons/podman_logo.svg
- packages/app/src/App.tsx
- packages/app/src/components/catalog/EntityPage/Pages/Component.tsx
> UX updates

- app-config.example.yaml
- app-config.yaml
- packages/app/public/homepage/data.json
- packages/app/src/App.tsx
- packages/app/src/components/home/HomePage.tsx
- packages/app/src/themes/theme.ts
> Minor UX updates

- .changeset/famous-insects-warn.md
- .changeset/popular-files-mix.md
- README.md
- app-config.example.yaml
- app-config.yaml
- packages/app/package.json
- packages/app/src/App.tsx
- packages/app/src/components/Root/Root.tsx
- packages/app/src/components/catalog/EntityPage/Content/CD.tsx
- packages/app/src/components/catalog/EntityPage/Content/CI.tsx
- packages/app/src/components/catalog/EntityPage/Content/Dependencies.tsx
- packages/app/src/components/catalog/EntityPage/Content/Docs.tsx
- packages/app/src/components/catalog/EntityPage/Content/EntityWarning.tsx
- packages/app/src/components/catalog/EntityPage/Content/ImageRegistry.tsx
- packages/app/src/components/catalog/EntityPage/Content/Issues.tsx
- packages/app/src/components/catalog/EntityPage/Content/Overview.tsx
- packages/app/src/components/catalog/EntityPage/Content/PullRequests.tsx
- packages/app/src/components/catalog/EntityPage/Content/SecurityInsights.tsx
- packages/app/src/components/catalog/EntityPage/Pages/Component.tsx
- packages/app/src/components/catalog/utils.tsx
- packages/backend/package.json
- showcase-docs/getting-started.md
- yarn.lock
Add the Lighthouse Plugin
- Fixes #261 
> feat(app): add lighthouse plugin

- packages/app/config.d.ts
- packages/app/package.json
- packages/app/src/api/index.ts
- packages/app/src/apis.ts
- packages/app/src/components/home/HomePage.tsx
- packages/app/src/hooks/useQuickAccess.ts
- packages/app/src/lib/CustomTechRadar.ts
- packages/app/src/types/types.ts
1. data powering the home page for quick access link is in code itself (https://github.com/janus-idp/backstage-showcase/blob/main/packages/app/public/homepage/data.json) which ideally should be configurable.
2. data powering the techRadar plugin is in code itself (https://github.com/janus-idp/backstage-showcase/blob/main/packages/app/public/tech-radar/data-default.json) which ideally should be configurable.
As part of this PR made the data for the home page configurable so that can be passed in `app-config.yaml `as a proxy. API url will return the data in JSON in the expected format/signature and fallback to the local data if api call fails or not configured.
For Home page(Quick Access links, the base URL at target should serve and for tech radar then svc URL should be `/tech-radar`
- Add …
> feat(app): fetch customization data from remote

- package.json
- Fixes https://github.com/janus-idp/backstage-showcase/issues/310
> fix(scripts): add start-backend

- Dockerfile
Updated the dockerfile to use relative paths when referencing `$REMOTE_SOURCES_DIR` after setting the `WORKDIR` to `$REMOTE_SOURCES_DIR/`
- Fixes https://github.com/janus-idp/backstage-showcase/issues/373
> chore(docker): update dockerfile to use relative paths

- packages/backend/package.json
- packages/backend/src/plugins/scaffolder.ts
- yarn.lock
Add Gitlab Scaffolder actions
- Fixes #389 
Gitlab actions available on backstage
> feat(backend): add gitlab scaffolder

- app-config.example.yaml
- yarn.lock
Adds a placeholder dynatrace baseUrl configuration in `app-config.example.yaml` so that no errors occur when running the built image.
https://github.com/backstage/backstage/blob/master/plugins/dynatrace/config.d.ts
- Fixes #418 
> chore: update app-config.example.yaml with dynatrace config

- .github/workflows/techdocs.yaml
- docs/index.md
Updates the TechDocs CI to remove the AWS_ENDPOINT variable as it is no longer needed for AWS S3.
- Fixes #416 
> chore: Techdocs cli

- .github/ISSUE_TEMPLATE/blank.md
- .github/ISSUE_TEMPLATE/config.yml
Added a blank issue template.
Updated the issue template config to link to the community slack invite link so that new users can join.
- Fixes #420 
> chore: add blank issue template

- packages/app/public/learning-paths/data.json
- packages/app/src/components/learningPaths/LearningPathsPage.tsx
Removed Learning Paths that no longer exist on https://developers.redhat.com/
Updated the duration of each Learning Path to display the time in hours and minutes.
Updated the number of paths for the Learning Paths.
- Fixes #396
- Fixes #398 
> chore: update learning path cards

- catalog-entities/apis.yaml
- catalog-entities/apis/nexus-repo-manager-3.yaml
- catalog-entities/apis/nexus-swagger.json
- catalog-entities/apis/petstore.yaml
Added the Nexus Repository Manager 3 OpenAPI spec to the catalog entities
- Fixes #423 ?
> chore: Add nexus repo manager 3 openapi spec to catalog

- .changeset/purple-files-lick.md
- app-config.example.yaml
- app-config.yaml
- packages/backend/package.json
- packages/backend/src/plugins/catalog.ts
- showcase-docs/getting-started.md
- yarn.lock
Add gitlab discovery capabilities to the showcase
Updated the `getting-started` documentation to show how to configure the app to enable gitlab discovery (as well as provide some recommendations on how to configure it)
- Fixes #422 
> feat: Add gitlab discovery

- .github/actions/docker-build/action.yaml
- .github/workflows/nightly.yaml
- .github/workflows/release.yaml
- .github/workflows/techdocs.yaml
- Fixes https://github.com/janus-idp/backstage-showcase/issues/456
> feat(actions): add nightly build

- .github/workflows/ci.yaml
- .github/workflows/nightly.yaml
- .github/workflows/release.yaml
- .github/workflows/techdocs.yaml
- package.json
> Fix actions

- .github/workflows/release.yaml
> feat(release): add push tag

- docker/Dockerfile
- Fixes https://github.com/janus-idp/backstage-showcase/issues/432
> fix(dockerfile): pygments vulnerable to ReDoS

- .changeset/pretty-kangaroos-impress.md
> fix(showcase): fix app-config.yaml

- .github/workflows/release.yaml
> fix(ci): remote git fetch tags

- .github/workflows/release.yaml
> Update release.yaml - make tag fetch and use more verbose

- .github/workflows/release.yaml
> Update release.yaml - pull commits and fetch changes; list recent tags

- .github/workflows/sync-renovate-changeset.yaml
- Fixes https://github.com/janus-idp/backstage-showcase/issues/505
> feat(renovate): autogenerate changesets for renovate bump PRs

- .changeset/tame-nails-wait.md
- README.md
- app-config.yaml
- packages/app/src/components/catalog/EntityPage/Pages/Resource.tsx
- packages/backend/package.json
- packages/backend/src/plugins/catalog.ts
- showcase-docs/getting-started.md
- yarn.lock
Adds AAP (Ansible automation platform) backend plugin to the Showcase App.
- Fixes https://github.com/janus-idp/backstage-showcase/issues/496
> feat: add AAP backend plugin

- .changeset/few-rocks-remember.md
- packages/backend/src/index.ts
* Adds `/healthcheck` endpoint
- Fixes #565 
Accessing `http://localhost:7007/healthcheck` should return the following:
```
{
"status": "ok"
}
```
> feat(backend): add healthcheck endpoint

- .github/workflows/pr-docker-build.yaml
> fix(ci): fix pr-docker-build action

- docker/install-dynamic-plugins.py
- dynamic-plugins.default.yaml
- showcase-docs/dynamic-plugins.md
Allow including files and overriding their content in the list of dynamic plugins 
- Fixes #641
> chore: support `includes` in `dynamic-plugins.yaml`

- .github/workflows/sync-renovate-changeset.yaml
> fix(ci): fix changeset renovate sync action

- .github/actions/docker-build/action.yaml
- .github/workflows/ci.yaml
- .github/workflows/next-docker-build.yaml
- .github/workflows/pr-docker-build.yaml
- .github/workflows/versioned-docker-build.yaml
chore: fix copyrights to be consistent with other files
The Janus IDP Authors instead of just Janus Authors
N/A
N/A
> chore: fix copyrights to be consistent with other files

- docker/Dockerfile
- docker/brew.Dockerfile
update docker/brew.Dockerfile for changes needed to build downstream; apply similar small tweaks to upstream
N/A
https://issues.redhat.com/browse/RHIDP-429
N/A
> update docker/brew.Dockerfile for changes needed to build downstream; apply similar small tweaks to upstream

- packages/app/src/common.tsx
- yarn.lock
Fixes the following error.
```log
The inferred type of 'fetcher' cannot be named without a reference to 'node/node_modules/undici-types'. This is likely not portable. A type annotation is necessary.
```
> fix(tsc): fix tsc compile error

- .changeset/hip-apples-clap.md
- packages/app/package.json
- yarn.lock
> chore(deps): update @mui/icons-material

- .github/workflows/next-docker-build.yaml
- .github/workflows/pr-docker-build.yaml
> feat(docker): add new tag for each PR commit

- .github/workflows/pr-docker-build.yaml
> fix(ci): fetch the correct sha on PR image builds

- docker/install-dynamic-plugins.py
Fix a bug in the dynamic plugin package integrity check that prevents disabling this feature as expected.
No issue number. Issue fixed while working on some other task.
> fix: fix dynamic plugin package integrity verification

- .gitignore
chore: remove dupe entries in .gitignore
N/A
N/A
> chore: remove dupe entries in .gitignore

- .changeset/chilly-ghosts-own.md
- showcase-docs/getting-started.md
Adds simple documentation for setting up the RBAC plugin within showcase
- Fixes #489 
- Dependent on #588 
> docs(app): add documentation for RBAC backend plugin

- showcase-docs/dynamic-plugins.md
fix formating to make prettier happy 
- Fixes #?
> chore(docs): fix formatting

- .changeset/perfect-balloons-repeat.md
- showcase-docs/dynamic-plugins.md
Update and complete the dynamic-plugins docs.
No issue
> docs(dynamic-plugins): update and complete the docs

- .changeset/hot-paws-grab.md
- app-config.dynamic-plugins.yaml
- dynamic-plugins.default.yaml
- packages/app/config.d.ts
- packages/app/src/components/catalog/EntityPage/index.tsx
- packages/app/src/components/catalog/Grid/Grid.tsx
- packages/app/src/components/catalog/tab/tab.tsx
Fixes regression of missing responsive UI to smaller screens
Resolves: https://github.com/janus-idp/backstage-showcase/issues/727
> fix: bring back responsive layout

- .changeset/wild-planes-move.md
- packages/backend/src/index.ts
Add more static plugins to the RBAC list. These plugins are required to retrieve plugin permissions and condition rules, providing them to the frontend via REST.
- Fixes #?
> fix(rbac): add more static plugins to RBAC list

- .changeset/strong-flies-jam.md
- app-config.dynamic-plugins.yaml
- dynamic-plugins.default.yaml
This PR updates topology layout config to fix topology view layout issues
- Fixes #745 
> fix(topology): fix topology view layout

- .changeset/rotten-dolls-relate.md
- packages/app/src/components/SignInPage/SignInPage.tsx
Updates the OIDC sign in page title
N/A
> update OIDC sign in page title

- .changeset/tasty-badgers-give.md
- package.json
- packages/app/src/components/DynamicRoot/DynamicRoot.test.tsx
- packages/app/src/components/DynamicRoot/DynamicRoot.tsx
- packages/app/src/components/DynamicRoot/DynamicRootContext.tsx
- packages/app/src/components/catalog/tab/tab.tsx
- packages/app/src/components/home/HomePage.tsx
- packages/app/src/utils/dynamicUI/bindAppRoutes.ts
- packages/app/src/utils/dynamicUI/extractDynamicConfig.test.ts
- packages/app/src/utils/dynamicUI/extractDynamicConfig.ts
- packages/app/src/utils/dynamicUI/getMountPointData.ts
- packages/app/src/utils/dynamicUI/initializeRemotePlugins.ts
Hardening, error handling, fixes and test coverage for `appIcons`, `dynamicRoutes` and `mountPoints` dynamic extensions. `routeBindings` will be covered separately, since this is more complicated to test/fix and use (as I've just discovered)
Resolves: https://github.com/janus-idp/backstage-showcase/issues/726
> fix(dynamic-frontend): loader code hardening

- .changeset/fluffy-carpets-hug.md
- packages/backend/src/index.ts
- Fixes https://github.com/janus-idp/backstage-showcase/issues/713
> fix(logging): call toString method on UrlReader

- docker/install-dynamic-plugins.py
PR https://github.com/janus-idp/backstage-showcase/pull/768 was not complete. This PR provides the missing piece
- Fixes #?
> fix: use the 'tar' filter to remove warnings (2) 

- docker/Dockerfile
- docker/brew.Dockerfile
bump base images to latest released versions
N/A
N/A
> bump base images to latest released versions

- package.json
- tsconfig.json
- yarn.lock
> fix: add skipLibCheck and remove wrap-ansi resolution

- package.json
- yarn.lock
This PR moves the required midstream dependencies upstream. 
- Fixes https://issues.redhat.com/browse/RHIDP-642?focusedId=23482063&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-23482063
> chore(deps): move midstream deps to upstream

- docker/Dockerfile
- docker/brew.Dockerfile
chore: combine dockerfile commands; disable docker and shellcheck (hadolint) warnings
N/A
N/A
> chore: combine dockerfile commands; disable docker and shellcheck (hadolint) warnings

- .changeset/seven-icons-jam.md
- dynamic-plugins/imports/package.json
Update dynamic-plugin peer dependencies to ~~add 3scale and~~ update AAP, Keycloak, and OCM backends to include these two PRs:
* https://github.com/janus-idp/backstage-plugins/pull/938
* https://github.com/janus-idp/backstage-plugins/pull/945
* Fixes #756 to include https://github.com/janus-idp/backstage-plugins/issues/629
> chore(deps): Update aap, keycloak and ocm backends

- .changeset/pretty-trainers-appear.md
- dynamic-plugins.default.yaml
- dynamic-plugins/imports/package.json
Add scaffolder actions for quay, regex, sonarqube, servicenow
Per https://redhat-internal.slack.com/archives/C05HGAR2DT5/p1700654673164509?thread_ts=1700250550.958579&cid=C05HGAR2DT5
fixes https://github.com/janus-idp/backstage-showcase/issues/629
> feat: add scaffolder actions plugins

- .changeset/rare-roses-attack.md
- dynamic-plugins.default.yaml
- dynamic-plugins/imports/package.json
Bring in 3scale plugin as dynamic plugin.
~Waiting for `1.3.6` to be released.~
N/A
> feat: add 3scale plugin

- dynamic-plugins.default.yaml
SSIA, packages were not found
https://github.com/janus-idp/backstage-showcase/issues/813
> fix: typo in backend package names missing -dynamic suffix

- OWNERS
Initial OWNERS file for Prow integrations.
This matches the list of the people with write access to this repo.
- Fixes #?
> add initial OWNERS file

- docker/prow.Dockerfile
fix the image to work on Prow 
- Fixes #?
> udpate prow.Dockerfile to make it compatible with prow

- showcase-docs/dynamic-plugins.md
chore: bump version of @janus-idp/cli to ^1.4.7 in showcase-docs/dynamic-plugins.md examples
Signed-off-by: RHDH Build (rhdh-bot) <rhdh-bot@redhat.com>
N/A
N/A
> chore: bump version of @janus-idp/cli to ^1.4.7 (latest version) in showcase-docs/dynamic-plugins.md examples

- .ibm/pipelines/openshift-tests.sh
- e2e-tests/README.md
- e2e-tests/playwright/e2e/plugins/keycloak/catalog-users.spec.ts
- e2e-tests/playwright/e2e/plugins/quick-access-and-tech-radar.spec.ts
- e2e-tests/playwright/support/pages/TechRadar.ts
- e2e-tests/playwright/utils/UIhelper.ts
- e2e-tests/playwright/utils/keycloak/keycloak.ts
- Fixes https://issues.redhat.com/browse/RHIDP-1074 and https://issues.redhat.com/browse/RHIDP-1075
> Fixing RHIDP-1075, RHIDP-1073

- e2e-tests/playwright/e2e/instance-health-check.spec.ts
[Test automation] Verify instance healthcheck endpoint status
https://issues.redhat.com/browse/RHIDP-794
> [Test automation] Verify instance healthcheck endpoint status

- scripts/update-backstage.mjs
> fix(script): fix the upgrade script

- showcase-docs/dynamic-plugins.md
- showcase-docs/monitoring-and-logging.md
chore: move https://github.com/janus-idp/helm-backstage -> https://github.com/redhat-developer/rhdh-chart [ci skip]
N/A
https://issues.redhat.com/browse/RHIDP-1020
N/A
> chore: move helm-backstage repo to redhat-developer/rhdh-chart 

- dynamic-plugins.default.yaml
See https://github.com/janus-idp/backstage-showcase/pull/948
JIRA: https://issues.redhat.com/browse/RHIDP-1030
Fixes https://github.com/janus-idp/backstage-showcase/issues/849
This is a PR to adopt Hugo's suggestions, see: https://github.com/janus-idp/backstage-showcase/pull/948#issuecomment-1927575321
Merge with: https://github.com/janus-idp/backstage-plugins/pull/1173
> fix(3scale): modify 3scale environment variables - using THREESCALE

- .ibm/pipelines/openshift-tests.sh
- .ibm/pipelines/value_files/values_showcase.yaml
[PR check]Update Helm Repository from 'janus-idp/helm-backstage' to 'redhat-developer/rhdh-chart'
[e2e tests] Implement Enhanced Backstage Service Availability Check in Deployment Script
https://issues.redhat.com/browse/RHIDP-1194
https://issues.redhat.com/browse/RHIDP-1213
> [PR check] Update Helm Repo to redhat-developer/rhdh-chart

- .changeset/strange-sheep-obey.md
- dynamic-plugins.default.yaml
- dynamic-plugins/imports/package.json
- packages/app/src/components/admin/AdminPage.tsx
- packages/backend/package.json
- yarn.lock
This change adds a tweak to the AdminPage to support components with sub-routes that provide entire page layouts rather than just tab contents.
This facilitates these views:
- Part of https://github.com/janus-idp/backstage-plugins/issues/1165
This PR brings in the latest updates to the RBAC plugin as well, so just this configuration is needed assuming these two plugins are present in the `dynamic-plugins-root`:
```yaml
frontend:
janus-idp.backstage-plugin-dynamic-plugins-info:
dynamicRoutes:
- path: /admin/plugins
importName: DynamicPluginsInfo
mountPoints:
- mountPoint: admin.page.plugins/cards
importName: DynamicPluginsInfo
config:
layout:
gridColumn: "1 / -1"
width: 100vw
janus-idp.backstage-plugin-rbac: …
```
> feat(AdminPage): support full page components

- dynamic-plugins/wrappers/backstage-plugin-azure-devops-backend-dynamic/dist-dynamic/yarn.lock
- dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-server/dist-dynamic/yarn.lock
- dynamic-plugins/wrappers/backstage-plugin-jenkins-backend-dynamic/dist-dynamic/yarn.lock
- dynamic-plugins/wrappers/backstage-plugin-kubernetes-backend-dynamic/dist-dynamic/yarn.lock
- dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-github-dynamic/dist-dynamic/yarn.lock
- dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-gitlab-dynamic/dist-dynamic/yarn.lock
- dynamic-plugins/wrappers/backstage-plugin-sonarqube-backend-dynamic/dist-dynamic/yarn.lock
- dynamic-plugins/wrappers/backstage-plugin-techdocs-backend-dynamic/dist-dynamic/yarn.lock
- dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab-backend-dynamic/dist-dynamic/yarn.lock
- dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd-backend-dynamic/dist-dynamic/yarn.lock
- dynamic-plugins/wrappers/roadiehq-scaffolder-backend-argocd-dynamic/dist-dynamic/yarn.lock
> fix(plugins): fix plugin wrapper yarn locks

- .ibm/OWNERS
add OWNERS file for .ibm directory 
The file is the same as for e2e-tests
- Fixes #?
> chore: add OWNERS for .ibm

- packages/app/src/components/admin/AdminPage.test.tsx
Add unit test for AdminPage merged in #989 
> fix(rbac): added unit test for AdminPage

- .ibm/pipelines/openshift-tests.sh
Clean up unused code. ${TAG_NAME} is passed from the CI. This fixes a failure when triggering tests manually
- Fixes https://issues.redhat.com/browse/RHIDP-1436
> [Test infra] Remove unused code

- scripts/update-backstage.mjs
- Fixes https://issues.redhat.com/browse/RHIDP-1414
> fix(scripts): add prettier step to update script

- e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
- e2e-tests/playwright/support/pages/rbac.ts
- Enabled Create and Edit roles e2e tests
- Added test for guest user
https://issues.redhat.com/browse/RHIDP-1441
> [rbac]: enable skipped e2e tests

- dynamic-plugins/wrappers/backstage-plugin-techdocs-backend-dynamic/dist-dynamic/yarn.lock
- dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd-backend-dynamic/dist-dynamic/package.json
- dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd-backend-dynamic/dist-dynamic/yarn.lock
- dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd-backend-dynamic/package.json
- dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd/package.json
- dynamic-plugins/wrappers/roadiehq-backstage-plugin-datadog/package.json
- dynamic-plugins/wrappers/roadiehq-backstage-plugin-github-insights/package.json
- dynamic-plugins/wrappers/roadiehq-backstage-plugin-github-pull-requests/package.json
- dynamic-plugins/wrappers/roadiehq-backstage-plugin-jira/package.json
- dynamic-plugins/wrappers/roadiehq-backstage-plugin-security-insights/package.json
- dynamic-plugins/wrappers/roadiehq-scaffolder-backend-argocd-dynamic/dist-dynamic/package.json
- dynamic-plugins/wrappers/roadiehq-scaffolder-backend-argocd-dynamic/dist-dynamic/yarn.lock
- dynamic-plugins/wrappers/roadiehq-scaffolder-backend-argocd-dynamic/package.json
- dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-utils-dynamic/dist-dynamic/package.json
- dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-utils-dynamic/package.json
- packages/backend/package.json
- yarn.lock
> chore(deps): update packages

- .ibm/pipelines/openshift-tests.sh
- .ibm/pipelines/resources/config_map/configmap-app-config-rhdh.yaml
- .ibm/pipelines/resources/pipeline-run/hello-world-pipeline-run.yaml
- .ibm/pipelines/resources/pipeline-run/hello-world-pipeline.yaml
- .ibm/pipelines/resources/pipeline-run/pipelines-operator.yaml
- .ibm/pipelines/value_files/values_showcase.yaml
- e2e-tests/playwright.config.ts
- e2e-tests/playwright/e2e/guest-signin-happy-path.spec.ts
- e2e-tests/playwright/e2e/plugins/ocm.spec.ts
- e2e-tests/playwright/e2e/plugins/quay/quay.spec.ts
- e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
- e2e-tests/playwright/e2e/plugins/tekton/tekton.spec.ts
- e2e-tests/playwright/e2e/techdocs.spec.ts
- e2e-tests/playwright/utils/Common.ts
- e2e-tests/playwright/utils/UIhelper.ts
- e2e-tests/playwright/utils/tekton/tekton.ts
https://issues.redhat.com/browse/RHIDP-777
- Fixes #?
Relates to Jira: RHIDP-777
> RHIDP-777 [Test automation] Verify Tekton is a supported plugin

- .ibm/pipelines/functions.sh
Upload Playwright reports to the same location as logs are uploaded and add a link to view and download the report to the PR. (see: https://github.com/janus-idp/backstage-showcase/pull/1068#issuecomment-1987268797)
- Fixes #?
> E2E: upload Playwright report and add view report link to PR

- dynamic-plugins/imports/package.json
There was a recent [fix](https://github.com/janus-idp/backstage-plugins/pull/1324) applied to the OCM backend plugin.
- Fixes [RHDHBUGS-12](https://issues.redhat.com/browse/RHDHBUGS-12)
> feat(ocm): update the ocm backend plugin

- .ibm/pipelines/openshift-tests.sh
- e2e-tests/package.json
Add test case names always in the test log even when tests are passed successfully. Currently, PR test log contains test cases name only for the failed test cases.
- Fixes https://issues.redhat.com/browse/RHIDP-1465
> add list of tests in the test log

- packages/app/src/components/Root/Root.tsx
- Outlined the nav sidebar icons
- updated some of the icons as per [Figma](https://www.figma.com/file/6ORS1mhUaxeyTBjMmE95Rn/Home-page-redesign?type=design&node-id=0-1&mode=design&t=hqJzxgFD3d3S83S5-0)
- Fixes https://issues.redhat.com/browse/RHIDP-1423
> update icons on the nav sidebar to make them outlined

- dynamic-plugins/imports/package.json
- dynamic-plugins/wrappers/backstage-plugin-azure-devops-backend-dynamic/dist-dynamic/yarn.lock
- dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-cloud/dist-dynamic/yarn.lock
- dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-server/dist-dynamic/yarn.lock
- dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-dynamic/dist-dynamic/yarn.lock
- dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-org-dynamic/dist-dynamic/yarn.lock
- dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-dynamic/dist-dynamic/yarn.lock
- dynamic-plugins/wrappers/backstage-plugin-jenkins-backend-dynamic/dist-dynamic/yarn.lock
- dynamic-plugins/wrappers/backstage-plugin-kubernetes-backend-dynamic/dist-dynamic/yarn.lock
- dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-azure-dynamic/dist-dynamic/yarn.lock
- dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-bitbucket-cloud-dynamic/dist-dynamic/yarn.lock
- dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-bitbucket-server-dynamic/dist-dynamic/yarn.lock
- dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-gerrit-dynamic/dist-dynamic/yarn.lock
- dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-github-dynamic/dist-dynamic/yarn.lock
- dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-gitlab-dynamic/dist-dynamic/yarn.lock
- dynamic-plugins/wrappers/backstage-plugin-sonarqube-backend-dynamic/dist-dynamic/yarn.lock
- dynamic-plugins/wrappers/backstage-plugin-techdocs-backend-dynamic/dist-dynamic/yarn.lock
- dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab-backend-dynamic/dist-dynamic/yarn.lock
- dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd-backend-dynamic/dist-dynamic/yarn.lock
- dynamic-plugins/wrappers/roadiehq-scaffolder-backend-argocd-dynamic/dist-dynamic/yarn.lock
- dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-utils-dynamic/dist-dynamic/yarn.lock
- yarn.lock
- Fixes CVE-2024-28849 - follow redirects (med, SLA of 90 days)
> chore(deps): regen lockfiles to fix cves

- dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd/package.json
- yarn.lock
> chore(deps): fix package resolutions

- packages/app/src/themes/componentOverrides.ts
- plugins/auth-backend-module-oidc-provider/src/module.test.ts
- Fixes 1.1.x typescript build issues. 
> fix(ts): fix ts compile issues

- packages/app/src/themes/componentOverrides.ts
- yarn.lock
This commit brings the yarn.lock file forward from a commit where the tests passed to use as a basis for the current set of declared package.json dependencies to fix the tests.  This change also removes a ts-error annotation that isn't needed with this set of dependencies.
- Fixes https://issues.redhat.com/browse/RHIDP-1750
> chore(deps): fix tests (1.1.x)

- .ibm/images/Dockerfile
- .ibm/pipelines/openshift-ci-tests.sh
Update and Deploy Custom Playwright Image for OpenShift CI Integration
https://issues.redhat.com/browse/RHIDP-1791 
> Update and Deploy Custom Playwright Image for OpenShift CI Integration

- packages/backend/src/logger/customLogger.ts
- Updates the audit log format to json.
- Fixes https://issues.redhat.com/browse/RHIDP-1632
> chore(audit): update audit log format to json

- OWNERS
- Add additional owners for NA coverage.  
- Removed @tumido since he no longer works on the project (required for annual access re-validation)
- Fixes #?
> chore(owners): add NA roster

- .gitignore
- e2e-tests/.gitignore
- e2e-tests/package.json
- e2e-tests/playwright.config.ts
Add a JUnit reporter for Playwright e2e tests.
- Prerequisite for Logilica and ReportPortal onboarding.
> RHIDP-428 Add JUnit test results reporter

- .ibm/pipelines/openshift-ci-tests.sh
add [a missing condition check](https://github.com/janus-idp/backstage-showcase/pull/1216) for the nightly rbac test
- Fixes #?
> add a missing condition check for the nightly rbac test

- scripts/update-metadata.mjs
chore: fix: generate a date in an OS-agnostic way
N/A
N/A
> chore: fix: generate a date in an OS-agnostic way

- .github/renovate.json
automerge is in place in the backstage-plugins repo.  Make the config consistent.  
- Fixes #?
- https://issues.redhat.com/browse/RHIDP-1737
> chore(renovate): automerge devdependencies

- .github/workflows/next-docker-build.yaml
- .github/workflows/pr-docker-build.yaml
- .husky/pre-commit
- .rhdh/docker/Dockerfile
- docker/Dockerfile
- packages/app/src/build-metadata.json
- scripts/update-metadata.mjs
chore: update the build time before the yarn build 
+ generate 'Last Commit' info from the GH action context instead of a simple timestamp; then append the build time during the docker build 
TODO:
* in mid and downstream sync, add repo + SHA for upstream and midstream repos
N/A
[RHIDP-1502](https://issues.redhat.com//browse/RHIDP-1502)
N/A
> chore: update the build time before the yarn build RHIDP-1502

- .ibm/pipelines/env_variables.sh
- e2e-tests/playwright/e2e/google-signin-happy-path.spec.ts
Update google authentication credentials from vault. 
Helps fixing [RHIDP-2265](https://issues.redhat.com/browse/RHIDP-2265) 
> [e2e] update google authentication credentials from ci vault

- e2e-tests/playwright/e2e/plugins/dynamic-plugins-info/dynamic-plugins-info.spec.ts
To extend the current dynamic-plugins-info e2e tests to include updates to the table
- Fixes [RHIDP-1861](https://issues.redhat.com/browse/RHIDP-1861)
> feat(admin): extended e2e tests

- .rhdh/docker/Dockerfile
chore: [RHIDP-1502](https://issues.redhat.com//browse/RHIDP-1502) for downstream use 'Upstream' instead of 'Last Commit', as we are inserting up and midstream SHAs
N/A
N/A
> chore: RHIDP-1502 for downstream use 'Upstream' instead of 'Last Commit', as we are inserting up and midstream SHAs

- .ibm/images/Dockerfile
- .ibm/pipelines/env_variables.sh
- .ibm/pipelines/openshift-ci-tests.sh
- e2e-tests/data_router/data_router_metadata_template.json
Add Data Router (`droute`) to Dockerfile. Send PR test results to ReportPortal.
- Fixes https://issues.redhat.com/browse/RHIDP-428
> RHIDP-428 Send PR test results to ReportPortal

- e2e-tests/playwright/e2e/google-signin-happy-path.spec.ts
Skip google sign in test until [RHIDP-2265](https://issues.redhat.com/browse/RHIDP-2265) is fixed
- Fixes #?
> Skip google-signin-happy-path.spec.ts

- packages/app/package.json
- yarn.lock
Update RHDH theme to include:
- https://github.com/redhat-developer/red-hat-developer-hub-theme/pull/8
- https://github.com/redhat-developer/red-hat-developer-hub-theme/pull/10
- https://github.com/redhat-developer/red-hat-developer-hub-theme/pull/11
- 8 fixes https://issues.redhat.com/browse/RHIDP-2289
- 10 fixes https://issues.redhat.com/browse/RHIDP-2290
- 11 fixes https://issues.redhat.com/browse/RHIDP-2300
> chore(deps): update RHDH theme

- .ibm/pipelines/env_variables.sh
- .ibm/pipelines/openshift-ci-tests.sh
Fix URL for nightly job.
Move couple of URLs to secrets.
- Fixes https://issues.redhat.com/browse/RHIDP-428
> RHIDP-428 RP Fix nightly URL and hostnames to secrets

- dynamic-plugins/imports/package.json
- packages/backend/package.json
- yarn.lock
This PR updates rbac and rbac-backend plugin versions
- Fixes https://issues.redhat.com/browse/RHIDP-2252
> chore(rbac): update rbac and rbac-backend plugin versions

- dynamic-plugins.default.yaml
- dynamic-plugins/imports/package.json
- e2e-tests/playwright/e2e/plugins/dynamic-plugins-info/dynamic-plugins-info.spec.ts
Add the [scaffolder relation processor plugin](https://github.com/janus-idp/backstage-plugins/pull/1591) into the showcase and enable by default as it does not require any additional configurations.
- Fixes [RHIDP-2222](https://issues.redhat.com/browse/RHIDP-2222)
> feat: add the scaffolder relation processor plugin

- showcase-docs/getting-started.md
chore: updates from privacy-legal team [RHIDP-58](https://issues.redhat.com//browse/RHIDP-58)
N/A
N/A
> chore: updates from privacy-legal team RHIDP-58

- .github/renovate.json
Trying to reduce the noise and break up the PRs into smaller changes
- Fixes #?
https://issues.redhat.com/browse/RHIDP-2883
> chore(renovate): separate test and dev deps, disable backstage updates

- dynamic-plugins/wrappers/backstage-plugin-kubernetes-backend-dynamic/dist-dynamic/yarn.lock
- yarn.lock
Update the `ws` dependencies to 7.5.10 and 8.17.1
- Fixes [CVE-2024-37890](https://access.redhat.com/security/cve/CVE-2024-37890)
> deps: update ws dependency in yarn.lock

- yarn.lock
chore(deps): clean out old tar-6.2.0 in favour of tar-6.2.1 from yarn.lock
N/A
https://issues.redhat.com/browse/RHIDP-2806
N/A
> chore(deps): clean out old tar-6.2.0 in favour of tar-6.2.1 from yarn.lock (RHIDP-2806)

- dynamic-plugins/wrappers/backstage-plugin-kubernetes-backend-dynamic/dist-dynamic/yarn.lock
- dynamic-plugins/wrappers/backstage-plugin-techdocs-backend-dynamic/dist-dynamic/yarn.lock
- yarn.lock
Update the `yarn.lock` to resolve [CVE-2024-35255](https://github.com/advisories/GHSA-m5vv-6r4h-3vj9)
- Fixes [RHIDP-2735](https://issues.redhat.com/browse/RHIDP-2735)
> chore(deps): update yarn.lock to resolve CVE-2024-35255

- yarn.lock
- Fixes #?
- https://issues.redhat.com/browse/RHIDP-3080
> chore(deps): fix CVE-2024-39008

- OWNERS
- Fixes #?
- https://issues.redhat.com/browse/RHIDP-3124
> chore(owners): add new reviewers

- dynamic-plugins/imports/package.json
Bump  the argocd version to the latest
cc: @nickboldt
> chore(deps): bump argocd version to 1.2.3

- e2e-tests/package.json
- package.json
- packages/app/src/build-metadata.json
chore: bump showcase to 1.2.2 so it's correctly shown in the settings page ([RHIDP-2961](https://issues.redhat.com//browse/RHIDP-2961))
N/A
N/A
> chore: bump showcase to 1.2.2 so it's correctly shown in the settings page (RHIDP-2961)

- dynamic-plugins/imports/package.json
- packages/app/package.json
- packages/backend/package.json
- yarn.lock
This is a manual cherry-pick of https://github.com/janus-idp/backstage-showcase/pull/1415
- Fixes https://issues.redhat.com/browse/RHIDP-3038
> chore(rbac): update rbac rbac-backend and rbac-common plugins versions

- packages/app/config.d.ts
- packages/app/package.json
- yarn.lock
This is backport of #1418 for 1.2.x. It updates the RHDH theme package to 0.1.7.
The theme is much more customizable with this update. Before we provided 4 options, but now the user can customize many MUI and RHDH parameters.
Before:
https://github.com/user-attachments/assets/33661435-f2e3-4baa-a327-6d1dd17e2c61
With this PR (shows a subset of customization parameters in this video):
https://github.com/user-attachments/assets/7881d8df-0f85-48b3-920a-5890c63d9ab4
- Epic: [RHIDP-2358](https://issues.redhat.com/browse/RHIDP-2358) RHDH Theme customization and improvements for 1.2.2
- update incl. Story [RHIDP-2545](https://issues.redhat.com/browse/RHIDP-2545) [UI] Enable complete theme customization
- update incl. Story [RHIDP-2943](https://issues.redhat.com/browse/RHIDP-2943) [UI] Allow …
> chore(deps): update rhdh theme package

- e2e-tests/playwright/utils/Common.ts
- e2e-tests/playwright/utils/UIhelper.ts
[e2e] Fix Frequent 2FA Code Reuse Issue in github test case
https://issues.redhat.com/browse/RHIDP-3237
> [e2e] Fix Frequent 2FA Code Reuse Issue in github test case

- packages/app/src/components/learningPaths/LearningPathsPage.tsx
Fixes: https://issues.redhat.com/browse/RHIDP-3249
This is a manual backport of #1426
* Removed an extra layer of Grid that wasn't necessary.
* Replaced the custom CSS rule `textDecoration: 'none'` with a Link prop `.underline="none"`
Some history:
And this might happen if we update @mui/material in the future for any reason.
The issue affects the main branch after #1379 updates @mui/material from 5.15.21 to 5.16.0.
- Fixes TODO
> RHIDP-3249: fix(learningpath): restore spacing between cards

- catalog-entities/components/showcase.yaml
See https://github.com/janus-idp/backstage-showcase/issues/1272#issuecomment-2218135101
- Fixes #?
> chore(nuff): replace link to broken janus slack with backstage discord

- e2e-tests/playwright/e2e/learning-path-page.spec.ts
- e2e-tests/playwright/utils/Common.ts
[e2e] Investigate and fix Learning path, rbac and key-clock test failures.
https://issues.redhat.com/browse/RHIDP-3387
> [e2e] Fix Learning Path test case

- e2e-tests/playwright/utils/Common.ts
back porting one of the change from : https://github.com/janus-idp/backstage-showcase/pull/1456
https://issues.redhat.com/browse/RHIDP-3387
> [e2e] Fix: Increase beforeAll hook timeout

- dynamic-plugins/wrappers/backstage-plugin-kubernetes-backend-dynamic/dist-dynamic/yarn.lock
- dynamic-plugins/wrappers/backstage-plugin-techdocs-backend-dynamic/dist-dynamic/yarn.lock
- yarn.lock
regen yarn.lock so patched version (v4.4.1) of fast-xml-parser is picked up 
- Fixes #?
https://issues.redhat.com/browse/RHIDP-3452
> chore:[1.2.x] fix CVE-2024-41818

- .ibm/pipelines/value_files/values_showcase.yaml
- e2e-tests/playwright/e2e/plugins/tekton/tekton.spec.ts
- e2e-tests/playwright/e2e/plugins/topology/topology.spec.ts
- e2e-tests/playwright/support/pages/Catalog.ts
- e2e-tests/playwright/utils/Common.ts
- e2e-tests/playwright/utils/UIhelper.ts
- e2e-tests/playwright/utils/tekton/tekton.ts
Test Automation for https://issues.redhat.com/browse/RHIDP-2640 
- Fixes #?
> RHIDP-3437 Include VMs in the topology view

- e2e-tests/playwright/e2e/plugins/quay/quay.spec.ts
Temporarily disable Quay.io plugin tests by adding `describe.skip`.
- Fixes #?
> Skip Quay.io plugin tests

- dynamic-plugins/wrappers/backstage-plugin-techdocs-backend-dynamic/dist-dynamic/yarn.lock
- yarn.lock
- Fixes #?
- https://issues.redhat.com/browse/RHIDP-3645
> chore: fix CVE-2024-39338

- .rhdh/docker/requirements-build.in
- .rhdh/docker/requirements-build.txt
- .rhdh/docker/requirements.in
- .rhdh/docker/requirements.txt
Backport of https://github.com/janus-idp/backstage-showcase/pull/1333
- Fixes #?
- https://issues.redhat.com/browse/RHIDP-3252
> chore(deps): [1.2.x] update dependency urllib3 to v2.2.2 [security]

- dynamic-plugins/wrappers/backstage-plugin-techdocs-backend-dynamic/dist-dynamic/yarn.lock
- yarn.lock
- Fixes #?
- https://issues.redhat.com/browse/RHIDP-3644
> chore: [1.2.x] fix CVE-2024-39338

- yarn.lock
CVE-2024-42461
- Fixes #?
https://issues.redhat.com/browse/RHIDP-3528
> chore: update elliptic - CVE-2024-42461

- package.json
- packages/app/src/build-metadata.json
chore: bump to 1.1.5 - [RHIDP-3693](https://issues.redhat.com//browse/RHIDP-3693) [RHIDP-3692](https://issues.redhat.com//browse/RHIDP-3692)
N/A
N/A
> chore: bump to 1.1.5 - RHIDP-3693 RHIDP-3692

- e2e-tests/playwright/e2e/catalog-scaffoldedfromLink.spec.ts
- e2e-tests/playwright/e2e/catalog-timestamp.spec.ts
- e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
- e2e-tests/playwright/support/pages/rbac.ts
- e2e-tests/playwright/utils/UIhelper.ts
> Fixing e2e tests

- OWNERS
Adding @debsmita1 @divyanshiGupta and myself :ninja: as owners to merge plugins update.
/cc @invincibleJai @kadel @nickboldt
> chore: add some more owners

- app-config.dynamic-plugins.yaml
- dynamic-plugins.default.yaml
chore: correct string configuration fix
https://issues.redhat.com/browse/RHIDP-3548?focusedId=25460749&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-25460749
> chore: correct string configuration fix

- .github/workflows/pr-docker-build.yaml
chore(pr checks): get latst commits from main before building PR ([RHIDP-2313](https://issues.redhat.com//browse/RHIDP-2313))
N/A
N/A
> chore(pr checks): get latst commits from main before building PR (RHIDP-2313)

- dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd/dist-dynamic/package.json
- dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd/package.json
- yarn.lock
> chore(deps): update argocd plugin version

- dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-dynamic/dist-dynamic/package.json
- dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-dynamic/package.json
- dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-org-dynamic/dist-dynamic/package.json
- dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-org-dynamic/package.json
We have doc'd and tested these two plugins so we can declare their support level as prod
- Fixes #?
- https://issues.redhat.com/browse/RHIDP-3953
> upgrade GH plugin support to prod

- .github/ISSUE_TEMPLATE/config.yml
chore(issue tracking): direct people to report janus plugin issues in JIRA, not BCP ([RHIDP-3678](https://issues.redhat.com//browse/RHIDP-3678))
N/A
N/A
> chore(issue tracking): direct people to report janus plugin issues in JIRA, not BCP (RHIDP-3678)

- dynamic-plugins/wrappers/roadiehq-backstage-plugin-github-pull-requests/package.json
Update @roadiehq/backstage-plugin-github-pull-requests version.
- Fixes [RHIDP-3159](https://issues.redhat.com/browse/RHIDP-3159)
> chore(deps): update github-pull-requests plugin version

- .sonarcloud.properties
- e2e-tests/playwright/e2e/audit-log/Log.ts
- e2e-tests/playwright/e2e/audit-log/LogUtils.ts
- e2e-tests/playwright/e2e/audit-log/catalog.spec.ts
- e2e-tests/playwright/e2e/audit-log/scaffold.spec.ts
- e2e-tests/playwright/support/pages/CatalogImport.ts
- e2e-tests/playwright/utils/UIhelper.ts
Test Automation for Audit Log events
- Fixes #?
> RHIDP-3716 - Test Automation / Audit Log

- dynamic-plugins/imports/package.json
Changelog:
- https://github.com/janus-idp/backstage-plugins/pull/2163
&mdash;
/cc @subhashkhileri
> chore(deps): bump bulk import backend plugin to 1.5.2

- dynamic-plugins/imports/package.json
See: https://github.com/janus-idp/backstage-plugins/pull/2162
- Pick up security fixes from the ocm-backend plugin.  
- Bulk import bump is handled [here](https://github.com/janus-idp/backstage-showcase/pull/1605) 
- Needs to be cherry picked to 1.3.x.  
- 1.2.x backport will be handled in a separate PR since that's an entirely manual step
- Fixes #?
- https://issues.redhat.com/browse/RHIDP-3917
- https://issues.redhat.com/browse/RHIDP-3945
> chore(deps): bump ocm-backend

- packages/app/src/components/Root/Root.tsx
- packages/app/src/utils/dynamicUI/extractDynamicConfigFrontend.test.ts
- packages/app/src/utils/dynamicUI/extractDynamicConfigFrontend.ts
- showcase-docs/dynamic-plugins.md
Update the menuItem key and path mapping logic.
- Fixes menu items mapping issue.
Run unit test
```
cd packages/app
yarn test extractDynamicConfigFrontend
```
> fix(ui): updated menu item key and path mapping logic

- .ibm/pipelines/openshift-ci-tests.sh
- e2e-tests/playwright/e2e/catalog-timestamp.spec.ts
- e2e-tests/playwright/e2e/plugins/keycloak/catalog-users.spec.ts
- e2e-tests/playwright/e2e/plugins/ocm.spec.ts
[1.3.x] Fix e2e-tests ci and test issues
- Fixes #?
> [1.3.x] Fix e2e-tests ci and test issues

- packages/app/package.json
- yarn.lock
Upgrade rhdh theme package version to 0.3.0
- Fixes "Card background color being too bright" issue.
> chore: Upgrade rhdh theme package version

- OWNERS
Add @JessicaJHee and @04kash as approvers and remove @Zaperex 
- Fixes #?
- N/A
> chore(owners): update approvers

- dynamic-plugins/imports/package.json
Pulls in the fix from https://github.com/janus-idp/backstage-plugins/pull/2178
- Fixes https://issues.redhat.com/browse/RHIDP-4021
> chore(deps): bump bulk-import-backend-plugin to 1.5.3

- packages/backend/src/modules/authProvidersModule.ts
Updating the existing message to include action items
- Fixes #?
- https://issues.redhat.com/browse/RHIDP-4032
> chore(msg): update sign-in error message

- dynamic-plugins/imports/package.json
- Pick up plugin version which has the [CVE-2024-43796](https://redirect.github.com/expressjs/express/security/advisories/GHSA-qw6h-vgh9-j6wx) fix
- Fixes #?
- N/A
> chore(deps): bump up keycloak-backend

- dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd-common/dist-dynamic/package.json
- dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd-common/package.json
- dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd/dist-dynamic/package.json
- dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd/package.json
- yarn.lock
Bump redhat-argocd and redhat-argocd-common plugins.
> chore(deps): bump argocd and argocd-common plugins

- dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd-common/dist-dynamic/package.json
- dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd-common/package.json
- dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd/dist-dynamic/package.json
- dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd/package.json
- yarn.lock
This is manual cherry-pick of https://github.com/janus-idp/backstage-showcase/pull/1633
> [1.3.x] chore(deps): bump argocd and argocd-common plugins

- dynamic-plugins/imports/package.json
- packages/backend/package.json
- yarn.lock
Fixes: https://issues.redhat.com/browse/RHIDP-4046
Bump RBAC plugin
> chore(deps): bump rbac plugin

- dynamic-plugins/imports/package.json
- packages/backend/package.json
- yarn.lock
Fixes: https://issues.redhat.com/browse/RHIDP-4046
Bump RBAC plugin
> [1.3.x] chore(deps): bump rbac plugin

- yarn.lock
Updates to transitive dependencies affecting multiple CVEs:
High:
CVE-2024-45801
CVE-2024-21529
CVE-2024-37890
Moderate:
CVE-2024-43788
CVE-2024-4067
CVE-2024-37168
CVE-2024-28849
- Fixes #?
- https://issues.redhat.com/browse/RHIDP-3926
- https://issues.redhat.com/browse/RHIDP-3727
> chore(deps): resolve dependabot findings

- dynamic-plugins/imports/package.json
This is to match the version that will be pushed in the 1.3.x branch of the plugins repo [1]
[1] https://github.com/janus-idp/backstage-plugins/pull/2204
&mdash;
/cc @PatAKnight
> chore(deps): bump bulk-import-backend-plugin to 1.5.4

- packages/backend/package.json
- yarn.lock
Manual cherrypick of #1577 as the openshift cherrypick robot failed to automatically create a cherrypick PR.
- Fixes https://issues.redhat.com/browse/RHIDP-3612 and https://issues.redhat.com/browse/RHIDP-2409
/cc @nickboldt @AndrienkoAleksandr
> [1.3.x] manual cherrypick #1577 update rbac and scaffolder module annotator

- .ibm/pipelines/openshift-ci-tests.sh
Temp: change to enable e2e on release-1.3. Revert once /pj-rehearse auto-ack pass on relase PR:56923
- Fixes #?
> Temp change to enable e2e on release-1.3

- e2e-tests/playwright/e2e/plugins/keycloak/catalog-users.spec.ts
> Enabling keycloak tests again

- package.json
- yarn.lock
https://issues.redhat.com/browse/RHIDP-3916
- Fixes #?
> chore(deps): bump to body-parser@^1.20.3

- .ibm/pipelines/value_files/values_showcase-rbac.yaml
- .ibm/pipelines/value_files/values_showcase.yaml
fixed e2e test configuration that was broken after renaming plugin directory in #1701
- Fixes #?
> chore(e2e): fix configuration to reflect changes from #1701

- app-config.dynamic-plugins.yaml
- plugins/dynamic-plugins-info/src/components/DynamicPluginsTable/DynamicPluginsTable.test.tsx
- plugins/dynamic-plugins-info/src/components/InternalPluginsMap.tsx
This PR fixs configuration to reflect changes from #1701.
- Fixes #?
> chore: rename acr plugin directory references

- e2e-tests/playwright/e2e/plugins/dynamic-plugins-info/dynamic-plugins-info.spec.ts
- plugins/dynamic-plugins-info/src/components/DynamicPluginsTable/DynamicPluginsTable.test.tsx
- plugins/dynamic-plugins-info/src/components/InternalPluginsMap.tsx
Updated configuration to reflect changes from #1514 
- Fixes #?
> chore: rename 3scale plugin paths to reflect the one in community-plugins

- package.json
- yarn.lock
https://issues.redhat.com/browse/RHIDP-4114
https://issues.redhat.com/browse/RHIDP-4115
https://issues.redhat.com/browse/RHIDP-4116
https://issues.redhat.com/browse/RHIDP-4117
> chore(deps): bump @backstage/plugin-techdocs-backend to 1.10.13

- package.json
- yarn.lock
https://issues.redhat.com/browse/RHIDP-4114
https://issues.redhat.com/browse/RHIDP-4115
https://issues.redhat.com/browse/RHIDP-4116
https://issues.redhat.com/browse/RHIDP-4117
> chore(deps): [release-1.3] bump @backstage/plugin-techdocs-backend t0 1.10.13

- package.json
- yarn.lock
https://issues.redhat.com/browse/RHIDP-3925
> chore(deps): bump dset to 3.1.4

- packages/app/src/utils/dynamicUI/extractDynamicConfigFrontend.ts
- plugins/dynamic-home-page/app-config.janus-idp.yaml
- plugins/dynamic-home-page/src/hooks/useHomePageMountPoints.ts
- plugins/dynamic-home-page/src/plugin.ts
1. Fix 3 tiny sonarcloud issues:
2. Improved example in (unused) plugins/dynamic-home-page/app-config.janus-idp.yaml
3. Marked properties in `useHomePageMountPoints.ts` as optional, also if its used optional chaining there already.
- Fixes #?
* #1532 should still work
/cc @ciiay @invincibleJai
> RHIDP-4133: fix(homepage): fix some sonarcloud issues

- packages/app/package.json
- plugins/dynamic-home-page/package.json
- yarn.lock
Update rhdh-theme to include this PRs:
* https://github.com/redhat-developer/red-hat-developer-hub-theme/pull/43
* https://github.com/redhat-developer/red-hat-developer-hub-theme/pull/44
* https://github.com/redhat-developer/red-hat-developer-hub-theme/pull/45
* https://github.com/redhat-developer/red-hat-developer-hub-theme/pull/46
* [RHIDP-3938](https://issues.redhat.com/browse/RHIDP-3938) Custom theme can causes runtime JavaScript errors
* [RHIDP-3139](https://issues.redhat.com/browse/RHIDP-3139) Theme enhancements to the menu's selected item theme
* [RHIDP-3430](https://issues.redhat.com/browse/RHIDP-3430) Change checkbox and tab color to match PatternFly (RHDH Theme)
> chore(deps): update rhdh-theme to 0.4.0

- package.json
- yarn.lock
corresponding pr: https://github.com/janus-idp/backstage-showcase/pull/1752/files 
- Fixes #? https://issues.redhat.com/browse/RHIDP-4116
> chore(deps): undo bump @backstage/plugin-techdocs-backend to 1.10.13

- yarn.lock
- Fixes #?
https://issues.redhat.com/browse/RHIDP-4417
> chore(deps): update elliptic to fix CVE-2024-48949

- package.json
- packages/app/package.json
- yarn.lock
Corresponding PR: https://github.com/janus-idp/backstage-showcase/pull/1728
- Fixes #?  https://issues.redhat.com/browse/RHIDP-2733
> chore(deps): CVE-2024-37890 force ws resolution to 8.17.1 [1.3]

- e2e-tests/playwright.config.ts
Lowering the general e2e test timeout
None
> [e2e] reduce test timeout

- e2e-tests/playwright/e2e/plugins/dynamic-plugins-info/dynamic-plugins-info.spec.ts
- plugins/dynamic-plugins-info/src/components/DynamicPluginsTable/DynamicPluginsTable.test.tsx
- plugins/dynamic-plugins-info/src/components/InternalPluginsMap.tsx
Updated configuration to reflect changes from https://github.com/janus-idp/backstage-showcase/pull/1514
- Fixes #?
> chore: [release-1.3] update 3scale references in dynamic-plugins-info

- packages/app/src/utils/dynamicUI/extractDynamicConfigFrontend.test.ts
- packages/app/src/utils/dynamicUI/extractDynamicConfigFrontend.ts
Backport of https://github.com/janus-idp/backstage-showcase/pull/1690 to `release-1.3`
> RHIDP-4544: fix(ui): hide menu items with no title in sidebar nav (#1690)

- OWNERS
/cc @invincibleJai @debsmita1 @divyanshiGupta @ciiay @its-mitesh-kumar 
/assign @invincibleJai
> chore: update my github username (owners file)

- .ibm/pipelines/resources/cluster_role_binding/cluster-role-binding-ocm.yaml
Clean up the SercvieAccount list by removing a duplicated entry. 
- Fixes https://issues.redhat.com/browse/RHIDP-4610
> [1.3] Clean up SercvieAccount list for OCM test

- dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab-backend-dynamic/dist-dynamic/package.json
fix(CVE): explicitly remove body-parser 1.20.2 in favour of 1.20.3 ([RHIDP-3917](https://issues.redhat.com//browse/RHIDP-3917))
N/A
N/A
> fix(CVE): explicitly remove body-parser 1.20.2 in favour of 1.20.3 (RHIDP-3917)

- .github/workflows/update-backstage.yaml
- .github/workflows/versioned-build-image.yaml
- scripts/update-backstage.mjs
> chore: add workflow to automate backstage updates

- .github/workflows/update-backstage.yaml
- scripts/update-backstage.mjs
> fix: add --no-immutable flag in update-backstage script

- scripts/update-backstage.mjs
> fix: rework update-backstage script

- .github/workflows/update-backstage.yaml
- packages/app/.prettierignore
> fix: ignore src/build-metadata.json and fix pr title

- packages/app/src/components/DynamicRoot/DynamicRoot.tsx
The runtime error
https://github.com/user-attachments/assets/5c0dbcf7-e741-401a-9fac-161117a099ed
- Fixes the runtime error
https://github.com/user-attachments/assets/f39ec71c-f945-4527-a042-7dbad5ea5ea8
> fix(ui): added null check to fix runtime error

- .ibm/pipelines/openshift-ci-tests.sh
- e2e-tests/playwright/e2e/plugins/tekton/tekton.spec.ts
Temporary measure to fix namespace termination issue
https://issues.redhat.com/browse/RHIDP-4752
> fix(e2e): disable tekton plugins and tekton tests

- dynamic-plugins/wrappers/backstage-community-plugin-acr/src/index.ts
- dynamic-plugins/wrappers/backstage-community-plugin-nexus-repository-manager/src/index.ts
- dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd/src/index.ts
- dynamic-plugins/wrappers/backstage-plugin-azure-devops/src/index.ts
- dynamic-plugins/wrappers/backstage-plugin-dynatrace/src/index.ts
- dynamic-plugins/wrappers/backstage-plugin-github-actions/src/index.ts
- dynamic-plugins/wrappers/backstage-plugin-github-issues/src/index.ts
- dynamic-plugins/wrappers/backstage-plugin-jenkins/src/index.ts
- dynamic-plugins/wrappers/backstage-plugin-kubernetes/src/index.ts
- dynamic-plugins/wrappers/backstage-plugin-lighthouse/src/index.ts
- dynamic-plugins/wrappers/backstage-plugin-sonarqube/src/index.ts
- dynamic-plugins/wrappers/backstage-plugin-tech-radar/src/index.ts
- dynamic-plugins/wrappers/backstage-plugin-techdocs/src/index.ts
- dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab/src/index.ts
- dynamic-plugins/wrappers/janus-idp-backstage-plugin-analytics-provider-segment/src/index.ts
- dynamic-plugins/wrappers/janus-idp-backstage-plugin-bulk-import/src/index.ts
- dynamic-plugins/wrappers/janus-idp-backstage-plugin-jfrog-artifactory/src/index.ts
- dynamic-plugins/wrappers/janus-idp-backstage-plugin-ocm/src/index.ts
- dynamic-plugins/wrappers/janus-idp-backstage-plugin-quay/src/index.ts
- dynamic-plugins/wrappers/janus-idp-backstage-plugin-rbac/src/index.ts
- dynamic-plugins/wrappers/janus-idp-backstage-plugin-tekton/src/index.ts
- dynamic-plugins/wrappers/janus-idp-backstage-plugin-topology/src/index.ts
- dynamic-plugins/wrappers/pagerduty-backstage-plugin/src/index.ts
- dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd/src/index.ts
- dynamic-plugins/wrappers/roadiehq-backstage-plugin-datadog/src/index.ts
- dynamic-plugins/wrappers/roadiehq-backstage-plugin-github-insights/src/index.ts
- dynamic-plugins/wrappers/roadiehq-backstage-plugin-github-pull-requests/src/index.ts
- dynamic-plugins/wrappers/roadiehq-backstage-plugin-jira/src/index.ts
- dynamic-plugins/wrappers/roadiehq-backstage-plugin-security-insights/src/index.ts
> fix(wrappers): export * instead of default from frontend plugins

- .ibm/pipelines/openshift-ci-tests.sh
Improved the namespace deletion function to handle scenarios where the namespace is stuck in a 'Terminating' state. Added functions to remove 'blockOwnerDeletion' from resources and force delete namespaces in such states. This ensures smoother and more reliable namespace cleanup in OpenShift CI tests.
- Fixes #?
> chore(e2e): enhance namespace deletion handling

- docs/dynamic-plugins/dynamic-plugins.md
- docs/dynamic-plugins/versions.md
- Fixes https://issues.redhat.com/browse/RHIDP-4487
> chore(docs): version matrix for dynamic plugins

- .ibm/pipelines/openshift-ci-tests.sh
- e2e-tests/playwright/e2e/plugins/tekton/tekton.spec.ts
Temporarily disable Tekton plugin tests using `test.describe.skip` and comment out the steps for installing and running the pipeline in the OpenShift CI script. This change is potentially to troubleshoot or isolate issues related to the Tekton plugin or pipeline setup.
- Fixes #?
> Disable Tekton plugin tests and comment pipeline setup steps

- docs/dynamic-plugins/dynamic-plugins.md
This change adds documentation for a few changes to the frontendi application that have been available, namely the ability to add additional custom context menu items to the entity page from a dynamic plugin, the ability to supply a custom sidebar item component from a dynamic plugin and finally the changes related to how API factories can be discovered from a frontend dynamic plugin if it exports it's plugin object vs. the need to explicitly configure frontend API factories.
- Fixes https://issues.redhat.com/browse/RHIDP-2561
> chore(docs): fill in some missing documentation

- dynamic-plugins/imports/package.json
Update keycloak-backend for RHDH 1.3.1
- Fixes https://issues.redhat.com/browse/RHIDP-3785
- Fixes https://issues.redhat.com/browse/RHIDP-4391
> chore(release): update keycloak-backend for RHDH 1.3.1

- .github/workflows/pr-build-image.yaml
chore: make PR link prettier/clickable
N/A
N/A
> chore: make PR link prettier/clickable

- dynamic-plugins/wrappers/backstage-community-plugin-tech-radar-backend-dynamic/package.json
Fixes export-dynamic:clean in tech-radar-backend
- Related to: https://issues.redhat.com/browse/RHIDP-4835 
> chore: fix export-dynamic:clean in tech-radar-backend

- e2e-tests/playwright.config.ts
Temp fix for github login rate limit issue
- Fixes #?
> chore(e2e): temp fix for github login rate limit issue

- e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
Implemented test to check download users link.
- Fixes [RHIDP-3892](https://issues.redhat.com/browse/RHIDP-3892)
> feat(e2e): implemented test to check download users link

- plugins/dynamic-home-page/docs/headline.md
- plugins/dynamic-home-page/package.json
- plugins/dynamic-home-page/src/components/Markdown.tsx
- plugins/dynamic-home-page/src/components/Placeholder.tsx
- plugins/dynamic-home-page/src/components/QuickAccessCard.tsx
- plugins/dynamic-home-page/src/components/ReadOnlyGrid.tsx
- plugins/dynamic-home-page/src/components/SearchBar.tsx
- yarn.lock
Updates the dynamic home page cards from MUI v4 to v5. It replaces #1667 with the necessary code changes.
- Fixes [RHIDP-4309](https://issues.redhat.com/browse/RHIDP-4309)
> chore(deps): update dynamic home page from mui v4 to v5

- .ibm/pipelines/openshift-ci-tests.sh
- e2e-tests/playwright/e2e/plugins/tekton/tekton.spec.ts
Disabling Tekton config and tests until namespace deletion fix is confirmed
https://issues.redhat.com/browse/RHIDP-4752
> fix(e2e): [1.2.x] disable tekton

- yarn.lock
- Fixes #?
https://issues.redhat.com/browse/RHIDP-4864
> chore(deps): release-1.3 fix CVE-2024-21538

- e2e-tests/playwright/utils/Common.ts
https://issues.redhat.com/browse/RHIDP-4931
- Fixes [RHIDP-4931](https://issues.redhat.com//browse/RHIDP-4931)
> test(e2e): hotfix for reauth github problem 

- .ibm/pipelines/openshift-ci-tests.sh
> fix: hide commands related to tokens

- e2e-tests/playwright/e2e/verify-tls-config-health-check.spec.ts
Deployment name for RHDH deployment changed, preventing some tests from passing.
[RHIDP-2915](https://issues.redhat.com/browse/RHIDP-2915)
> fix(e2e): fix Verify TLS config with Postgres in Amazon RDS using Helm

- .ibm/images/Dockerfile
- .ibm/pipelines/cluster/osd-gcp/README.md
- .ibm/pipelines/cluster/osd-gcp/create-osd.sh
- .ibm/pipelines/cluster/osd-gcp/destroy-osd.sh
- .ibm/pipelines/openshift-ci-tests.sh
- .ibm/pipelines/utils.sh
1. Added OSD cluster management scripts (create-osd.sh, destroy-osd.sh)
2. Updated test infrastructure to use OSD GCP cluster
3. Added Documentation.
[RHIDP-4023](https://issues.redhat.com/browse/RHIDP-4023)
> chore(e2e): rhdh deployment on openshift dedicated (osd) on gcp using helm chart

- dynamic-plugins/wrappers/backstage-community-plugin-ocm-backend-dynamic/dist-dynamic/yarn.lock
- yarn.lock
regen yarn.locks
- Fixes #?
- https://issues.redhat.com/browse/RHIDP-4864
> chore(deps): fix CVE-2024-21538

- dynamic-plugins/wrappers/backstage-community-plugin-tech-radar/src/index.ts
Export tech radar icon from backstage-community-plugin-tech-radar. 
- Fixes #?
> chore: export tech radar icon from wrapper

- .ibm/pipelines/openshift-ci-tests.sh
- .ibm/pipelines/resources/cluster_role_binding/cluster-role-binding-ocm.yaml
- .ibm/pipelines/utils.sh
Currently, PR tests for the main branch are executed sequentially, causing significant delays with 13-15 PRs in the waiting queue. Implementing a parallel testing solution using multiple namespaces to improve efficiency.
**Proposed Solution**
- Implement parallel PR testing using namespace pools
- Initially support 3-4 concurrent PR tests (expandable to 5)
- Leverage existing IBM pr-os cluster.
https://issues.redhat.com/browse/RHIDP-4946
> chore(e2e): implement parallel PR testing for backstage showcase main branch

- .ibm/pipelines/openshift-ci-tests.sh
https://issues.redhat.com/browse/RHIDP-4946
> chore(e2e): rhdh e2e pr check parallel fix

- docs/customization.md
- docs/dynamic-plugins/dynamic-plugins.md
- docs/dynamic-plugins/index.md
- Relates to https://issues.redhat.com/browse/RHIDP-4791
> chore(docs): dynamic plugins index

- .ibm/pipelines/cluster/aks/deployment.sh
- .ibm/pipelines/cluster/gke/deployment.sh
> chore(ci): fix GKE and AKS value-file artifact

- .ibm/pipelines/value_files/values_showcase.yaml
- dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-http-request-dynamic/dist-dynamic/package.json
- dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-http-request-dynamic/dist-dynamic/yarn.lock
- dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-http-request-dynamic/package.json
- dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-http-request-dynamic/src/index.ts
- dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-utils-dynamic/dist-dynamic/package.json
- dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-utils-dynamic/dist-dynamic/yarn.lock
- dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-utils-dynamic/package.json
- dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-utils-dynamic/src/index.ts
- e2e-tests/playwright/e2e/plugins/http-request.spec.ts
- yarn.lock
During all of the recent updates, we realized that a couple of the roadie scaffolder backend modules were broken. This PR updates them after they have been fixed upstream. There was also a disabled test that has now been re-enabled. 
- Fixes [RHIDP-4838](https://issues.redhat.com/browse/RHIDP-4838)
- Fixes [RHIDP-4837](https://issues.redhat.com/browse/RHIDP-4837)
> chore(deps): update roadie scaffolder modules

- docs/dynamic-plugins/debugging.md
- docs/dynamic-plugins/export-derived-package.md
- docs/dynamic-plugins/frontend-plugin-wiring.md
- docs/dynamic-plugins/installing-plugins.md
- docs/dynamic-plugins/local.md
- docs/dynamic-plugins/override-core-services.md
- docs/dynamic-plugins/packaging-dynamic-plugins.md
- e2e-tests/README.md
fixes typos, grammar and adds some small style improvements 
- Fixes #?
> docs: fix grammar and style issues

- OWNERS
Update owners file with more approvers
- Fixes #?
- N/A
> chore(owners): add more approvers

- yarn.lock
fix version of jsonpath-plus  is now in v10.2.0
- Fixes #?
- https://issues.redhat.com/browse/RHIDP-4440
> chore(deps): 1.4 fix CVE-2024-21534

- .ibm/images/Dockerfile
https://issues.redhat.com/browse/RHIDP-4956
Optimized the Dockerfile by combining multiple RUN commands into a single layer to reduce the size and improve build efficiency. Set essential environment variables together, consolidated installations, and added comments for clarity. This refactor enhances maintainability and performance of the Docker build process.
> chore(e2e):  optimize .ibm Dockerfile for Improved Build Performance and Dependency Updates

- packages/app/package.json
- plugins/dynamic-home-page/package.json
- plugins/dynamic-plugins-info/package.json
- plugins/licensed-users-info-backend/package.json
- yarn.lock
Replaces https://github.com/janus-idp/backstage-showcase/pull/1713
- Fixes #?
> fix(deps): update dependencies (non-major)

- packages/backend/package.json
- yarn.lock
update rbac-backend plugin
- Fixes https://issues.redhat.com/browse/RHIDP-4734
> fix(rbac): update rbac-backend plugin

- .rhdh/docker/Dockerfile
> chore: switch SEGMENT_WRITE_KEY in release-1.4

- yarn.lock
- Fixes #?
- https://issues.redhat.com/browse/RHIDP-4519
> chore(deps): update mysql2

- .ibm/pipelines/openshift-ci-tests.sh
- e2e-tests/playwright/e2e/catalog-scaffoldedfromLink.spec.ts
- e2e-tests/playwright/e2e/github-happy-path.spec.ts
- e2e-tests/playwright/e2e/plugins/analytics/analytics-disabled-rbac.spec.ts
- e2e-tests/playwright/e2e/plugins/rbac/rbac-api.spec.ts
- e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
- e2e-tests/playwright/support/pageObjects/global-obj.ts
Disabled some tests as a workaround until they are stable enough.
First errors from a random ([this](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/janus-idp_backstage-showcase/1991/pull-ci-janus-idp-backstage-showcase-main-e2e-tests/1861647696121565184)) build log:
```
✘  5 [showcase] › e2e/catalog-scaffoldedfromLink.spec.ts:42:3 › Link Scaffolded Templates to Catalog Items › Register an Template (0ms)
...
✘  37 [showcase] › e2e/plugins/http-request.spec.ts:24:3 › Testing scaffolder-backend-module-http-request to invoke an external request › Create a software template using http-request plugin (28.5s)
✘  44 [showcase] › e2e/github-happy-path.spec.ts:84:3 › GitHub Happy path › Click login on the login popup and verify that Overview tab renders (22.1s)
...
✘  47 …
```
> fix(e2e): disable broken/flaky tests and add support for MUI v5 buttons in playwright tests

- packages/app/src/utils/dynamicUI/initializeRemotePlugins.ts
I'm sorry. I don't know exactly when I need this this week, but it helped me understand a dynamic plugin misconfiguration. I think it's good to log the underlying error to the browser console.
- Fixes #?
Misconfigure a dynamic plugin :D
> fix(dynamic plugins): log plugin load errors

- dynamic-plugins/wrappers/backstage-community-plugin-rbac/package.json
- yarn.lock
update rbac frontend to incl. at least
* https://github.com/backstage/community-plugins/pull/1985
* https://github.com/backstage/community-plugins/pull/2061
* https://github.com/backstage/community-plugins/pull/2067
- Fixes https://issues.redhat.com/browse/RHIDP-4307
> feat(rbac): update rbac plugin to 1.33.2

- dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-bulk-import-backend-dynamic/dist-dynamic/package.json
- dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-bulk-import-backend-dynamic/dist-dynamic/yarn.lock
- dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-bulk-import-backend-dynamic/package.json
- dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-bulk-import/package.json
- yarn.lock
Updates the bulk import plugin.
- Fixes [RHIDP-3931](https://issues.redhat.com/browse/RHIDP-3931)
- Fixes [RHIDP-4144](https://issues.redhat.com/browse/RHIDP-4144)
> chore(deps): update bulk import plugins

- .ibm/pipelines/openshift-ci-tests.sh
- .ibm/pipelines/value_files/diff-values_showcase_AKS.yaml
- .ibm/pipelines/value_files/diff-values_showcase_GKE.yaml
- e2e-tests/playwright.config.ts
- e2e-tests/playwright/e2e/configuration-test/config-map.spec.ts
- e2e-tests/playwright/e2e/plugins/http-request.spec.ts
Export NAME_SPACE in CI script and use it in test scripts to make namespace dynamic. Additionally, update the function call in http-request.spec.ts to pass a second boolean argument.
- Fixes #?
> chore(e2e): fixing k8's nightly tests.

- e2e-tests/playwright/e2e/plugins/topology/topology.spec.ts
- e2e-tests/playwright/utils/ui-helper.ts
Added tests for the Topology plugin
This PR focuses on tests with most of the steps included in the issue [RHIDP-778](https://issues.redhat.com/browse/RHIDP-778) 
Will be creating another PR for for the remaining few tests.
[video.webm](https://github.com/user-attachments/assets/58115aeb-5b2d-4b06-9f63-3eb5df4952f0)
- Fixes [RHIDP-778
](https://issues.redhat.com/browse/RHIDP-778)
> chore(e2e-test): [Test automation] Verify Topology is a supported plugin and E2E scenario

- dynamic-plugins/wrappers/backstage-plugin-kubernetes-backend-dynamic/dist-dynamic/yarn.lock
- dynamic-plugins/wrappers/roadiehq-scaffolder-backend-argocd-dynamic/dist-dynamic/yarn.lock
* CVE updates on missed plugins
- Fixes #?
[RHIDP-5074](https://issues.redhat.com/browse/RHIDP-5074)
[RHIDP-5080](https://issues.redhat.com/browse/RHIDP-5080)
[RHIDP-5078](https://issues.redhat.com/browse/RHIDP-5078)
[RHIDP-5077](https://issues.redhat.com/browse/RHIDP-5077)
> chore(deps): [1.2.x] update ws and express packages

- .ibm/pipelines/openshift-ci-tests.sh
- e2e-tests/playwright.config.ts
> chore(e2e): fix e2e tests and increase timeouts

- e2e-tests/playwright/support/pageObjects/global-obj.ts
> chore(e2e): fix mui v5 button locator

- e2e-tests/playwright/e2e/catalog-scaffolded-from-link.spec.ts
- packages/backend/package.json
- packages/backend/src/index.ts
- yarn.lock
…
`@backstage-community/plugin-scaffolder-backend-module-annotator` migrated to Backstage Commmunity plugins.
- Fixes #?
> chore: update location of @backstage-community/plugin-scaffolder-backend-module-annotator

- e2e-tests/playwright/e2e/catalog-scaffolded-from-link.spec.ts
> chore(e2e): fix catalog scaffolded test

- .ibm/pipelines/cluster/aks/deployment.sh
- .ibm/pipelines/cluster/gke/deployment.sh
- .ibm/pipelines/jobs/aks.sh
- .ibm/pipelines/jobs/gke.sh
- .ibm/pipelines/jobs/main.sh
- .ibm/pipelines/jobs/ocp-v4-15.sh
- .ibm/pipelines/jobs/ocp-v4-16.sh
- .ibm/pipelines/jobs/operator.sh
- .ibm/pipelines/jobs/periodic.sh
- .ibm/pipelines/openshift-ci-tests.sh
- .ibm/pipelines/utils.sh
- e2e-tests/playwright.config.ts
- e2e-tests/playwright/e2e/plugins/topology/topology.spec.ts
> refactor: modularize OpenShift CI script for better maintainability - new

- .ibm/pipelines/utils.sh
> chore(e2e): reconfigure namespace setup in deployment script

- e2e-tests/playwright/e2e/catalog-scaffoldedfromLink.spec.ts
https://issues.redhat.com/browse/RHIDP-5199
> chore(e2e): fix e2e tests scaffolded

- packages/backend/package.json
- packages/backend/src/index.ts
- yarn.lock
cherrypick of https://github.com/janus-idp/backstage-showcase/pull/2060
- Fixes
> chore: [release-1.4] update location of @backstage-community/plugin-scaffolder-backend-module-annotator

- .rhdh/docker/Dockerfile
- docker/Dockerfile
This is a manual replacement of the renovate [PR](https://github.com/janus-idp/backstage-showcase/pull/1748) 
Updates all images except for the ones used in test which may be the reason why the renovate PR is failing
- Fixes #?
> chore(deps): update dockerfile image

- .ibm/pipelines/value_files/values_showcase.yaml
- dynamic-plugins/_utils/src/wrappers.test.ts
- e2e-tests/playwright/e2e/catalog-scaffolded-from-link.spec.ts
- e2e-tests/playwright/e2e/catalog-timestamp.spec.ts
- e2e-tests/playwright/e2e/configuration-test/config-map.spec.ts
- e2e-tests/playwright/e2e/github-happy-path.spec.ts
- e2e-tests/playwright/e2e/github-integration-org-fetch.spec.ts
- e2e-tests/playwright/e2e/plugins/dynamic-plugins-info/dynamic-plugins-info.spec.ts
- e2e-tests/playwright/e2e/plugins/http-request.spec.ts
- e2e-tests/playwright/e2e/plugins/ocm.spec.ts
- e2e-tests/playwright/e2e/plugins/quick-access-and-tech-radar.spec.ts
- e2e-tests/playwright/support/pages/tech-radar.ts
- e2e-tests/playwright/utils/common.ts
- e2e-tests/playwright/utils/ui-helper.ts
> chore(e2e): rhidp-5094 - [Test automation] restore skipped e2e tests nov2024

- e2e-tests/playwright/e2e/verify-tls-config-with-external-postgres-db.spec.ts
fixing a small timeout in the "verify TLS configuration with external Postgres DB" test case
- Fixes #?
> fix: [e2e-tests] - fix verify TLS configuration with external Postgres DB test case

- .ibm/pipelines/jobs/periodic.sh
Tech radar tests are failing for nightly tests only.
[RHIDP-5314](https://issues.redhat.com/browse/RHIDP-5314)
> chore(e2e): fix tech radar tests for nightly

- e2e-tests/playwright/e2e/configuration-test/config-map.spec.ts
- e2e-tests/playwright/utils/kube-client.ts
- Fixes https://issues.redhat.com/browse/RHIDP-5296
> chore(e2): rhidp-5296 e2e - main nightly job failing on runtime configuration change step

- e2e-tests/package.json
- package.json
- packages/app/src/build-metadata.json
> chore: tagRelease.sh: bump to 1.3.4 in release-1.3 branch

- .ibm/pipelines/jobs/periodic.sh
- .ibm/pipelines/value_files/sanity-check-plugins.yaml
- Fixes
https://issues.redhat.com/browse/RHIDP-5301
> chore(e2e): rhidp-5301 Plugins Sanity Checks

- .ibm/pipelines/utils.sh
> chore(ci): re-enable `droute`

- e2e-tests/playwright/e2e/configuration-test/config-map.spec.ts
> chore(e2e): skip "Change app-config" e2e test case.

- .ibm/pipelines/README.md
Documentation for RHDH setup in ephemeral env using OCP.
https://issues.redhat.com/browse/RHIDP-4764
> chore(ci-doc): documentation for RHDH setup in ephemeral env using OCP.

- .ibm/pipelines/resources/config_map/rbac-policy.csv
- e2e-tests/playwright/data/rbac-constants.ts
- e2e-tests/playwright/e2e/plugins/bulk-import.spec.ts
- e2e-tests/playwright/utils/ui-helper.ts
unskip and fix bulk import test case
https://issues.redhat.com/browse/RHIDP-5258
> chore(e2e): fix bulk import test case

- .ibm/pipelines/jobs/operator.sh
- .ibm/pipelines/resources/cluster_role_binding/cluster-role-binding-ocm.yaml
- .ibm/pipelines/utils.sh
> chore(e2e): cleanup operator e2e script and config

- .ibm/pipelines/utils.sh
Apply recent Data Router improvements & fixes from main.
- Fixes [RHIDP-5392](https://issues.redhat.com/browse/RHIDP-5392)
> chore(ci): improvements & fix for Data Router

- .github/actions/docker-build/action.yaml
- .github/workflows/next-build-image.yaml
- .github/workflows/pr-build-image.yaml
- .github/workflows/techdocs.yaml
- .github/workflows/update-backstage.yaml
- .github/workflows/versioned-build-image.yaml
chore: misc fixes as part of migration (RHIDP-1022)
N/A
[RHIDP-1022](https://issues.redhat.com/browse/RHIDP-1022)
N/A
> chore: misc fixes as part of migration (RHIDP-1022)

- .ibm/pipelines/openshift-ci-tests.sh
- e2e-tests/playwright/e2e/audit-log/catalog.spec.ts
> chore(e2e): temporarily disable a failing test

- .github/workflows/pr-build-image.yaml
> chore: update GitHub Actions workflow to skip builds for changes in specific folders

- .ibm/pipelines/jobs/periodic.sh
fix test results not found issue in nightly job
https://issues.redhat.com/browse/RHIDP-5595
> chore(e2e): fix test results not found issue in nightly job

- .ibm/pipelines/jobs/operator.sh
rh-pre-commit.version: 2.3.2
rh-pre-commit.check-secrets: ENABLED
Fix operator e2e flakiness
[RHIDP-5588](https://issues.redhat.com/browse/RHIDP-5588)
> chore(e2e): fix backstage operator being deployed before its ready

- .github/workflows/pr-build-image.yaml
Replace `janus-idp/backstage-showcase` references with  `rhdh-community/rhdh` in pr.yaml
> chore: replace-showcase-references

- e2e-tests/playwright/e2e/plugins/ocm.spec.ts
> test(e2e): make ocm non serial

- CONTRIBUTING.md
- docs/audit-log.md
- docs/auth.md
- docs/dynamic-plugins/debugging.md
- docs/e2e-tests/CI.md
- docs/index.md
- docs/monitoring-and-logging.md
- docs/patch-package.md
- dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-catalog-backend-module-marketplace-dynamic/package.json
- dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace-backend-dynamic/package.json
- dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace/package.json
- scripts/update-backstage.mjs
I updated just some other doc titles and references from showcase to RHDH.
- Part of https://issues.redhat.com/browse/RHIDP-5574
> docs: replace more showcase references with RHDH

- e2e-tests/playwright/utils/quay/quay.ts
chore(e2e): fix quay image validation
https://issues.redhat.com/browse/RHIDP-5690 
> chore(e2e): fix quay image validation

- .github/workflows/pr-build-image.yaml
- .ibm/pipelines/openshift-ci-tests.sh
Add image existence check and refine change detection logic
Introduced a step to check if a PR-related image already exists in the registry to avoid unnecessary builds. Additionally, streamlined the change detection process to flag whether relevant files require triggering a build.
- Fixes #?
> chore: git workflow build image

- .rhdh/docker/Dockerfile
- docker/Dockerfile
Manual cherry pick of Renovate [PR](https://github.com/redhat-developer/rhdh/pull/2226) in main
- Fixes #?
- N/A
> chore: [release 1.4] update dockerfile images

- OWNERS
Add @JessicaJHee as an approver.  Remove others who are no longer on the team
- Fixes #?
> chore: [release-1.3] update approvers

- .rhdh/docker/Dockerfile
- docker/Dockerfile
Manual cherry pick of Renovate [PR](https://github.com/redhat-developer/rhdh/pull/2226) in main
- Fixes #?
- N/A
> chore: [release-1.3] update dockerfile images

- .rhdh/docker/Dockerfile
- docker/Dockerfile
Updates the python version in the runner image to 3.11
https://issues.redhat.com/browse/RHIDP-5582
> chore: update python version - RHIDP-5582 [release-1.4]

- packages/backend/package.json
- yarn.lock
- Fixes https://issues.redhat.com/browse/RHIDP-5259
> fix(rbac): fix edit rbac operations for high availability

- app-config.example.yaml
- app-config.yaml
- catalog-info.yaml
- mkdocs.yaml
- packages/app/public/manifest.json
1. Update software catalog title for RHDH => Red Hat Developer Hub
2. Update techdocs title as well
> chore: update catalog-info and docs title

- docs/e2e-tests/CI.md
docs: add instructions for triggering optional nightly jobs on PRs
https://issues.redhat.com/browse/RHIDP-5726
> chore(e2e-docs): add instructions for triggering optional nightly jobs on PRs

- e2e-tests/playwright/utils/quay/quay.ts
chore(e2e): fix quay flaky test
https://issues.redhat.com/browse/RHIDP-5744
> chore(e2e): fix quay flaky test

- dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-global-header/turbo.json
- dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace-backend-dynamic/package.json
- Added missing turbo.json file to `red-hat-developer-hub-backstage-plugin-global-header`
- Updated supported version to 1.35.0 in `red-hat-developer-hub-backstage-plugin-marketplace-backend-dynamic`
> chore: misc wrapper fixes

- packages/backend/package.json
- yarn.lock
Manual cherry pick of https://github.com/redhat-developer/rhdh/pull/2224 to bump undici to v6.21.1
- Fixes #?
- [RHIDP-5740](https://issues.redhat.com/browse/RHIDP-5740)
[CVE-2025-22150](https://redirect.github.com/nodejs/undici/security/advisories/GHSA-c76h-2ccp-4975)
> chore: [release-1.4] fix CVE-2025-22150

- dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-dynamic-home-page/package.json
- yarn.lock
Update the dynamic-home-page plugin
From https://github.com/redhat-developer/rhdh-plugins/blob/main/workspaces/homepage/plugins/dynamic-home-page/CHANGELOG.md:
- 4d622ad: - Added support to show also the the username (`displayName` from the user catalog entity) in the header title.
- Added additional options to show the local time and a worldclock to the header.
- Added a new `WorldClock` card based on the Home plugin `HeaderWorldClock` component to show additional clocks/timezones also in the home page content area.
- c376011: Upgrade Backstage from 0.32.0 to 1.35.0
- 34c138c: Updated dependency `react-router-dom` to `6.28.2`.
- bc85b86: Updated dependency `tss-react` to `4.9.15`.
- f627fd2: Updated dependency `@mui/icons-material` to `5.16.13`.
Updated dependency `@mui/material` to …
> feat(homepage): update plugin that includes Backstage 1.35.0 and latest home page improvements

- e2e-tests/playwright/e2e/plugins/bulk-import.spec.ts
chore(e2e): skip bulk import test case on osd helm nighlty job.
- Fixes #?
> chore(e2e): skip bulk import test case on osd helm nighlty job.

- .ibm/pipelines/cluster/osd-gcp/destroy-osd.sh
- .ibm/pipelines/jobs/operator.sh
- e2e-tests/playwright/e2e/plugins/bulk-import.spec.ts
- e2e-tests/playwright/e2e/plugins/dynamic-plugins-info/dynamic-plugins-info.spec.ts
- e2e-tests/playwright/e2e/plugins/topology/topology.spec.ts
- e2e-tests/playwright/utils/ui-helper.ts
chore(e2e): fix gcp osd operator job
- Fixes #?
> chore(e2e): fix gcp osd operator job

- docker/install-dynamic-plugins.py
- showcase-docs/dynamic-plugins.md
This is a manual cherry-pick of https://github.com/redhat-developer/rhdh/pull/2285
Automated cherry-pick failed: https://github.com/redhat-developer/rhdh/pull/2285#issuecomment-2648230335
- Fixes https://issues.redhat.com/browse/RHIDP-5833
/assign @gazarenkov
> [release-1.3] feat: avoid dynamic-plugins writing conflicts (#2285)

- app-config.dynamic-plugins.yaml
- dynamic-plugins.default.yaml
Add VisitListener component to home page plugin
- Fixes https://issues.redhat.com/browse/RHIDP-4235
> feat: add VisitListener to home page plugin

- .rhdh/docker/Dockerfile
Signed-off-by: RHDH Build (rhdh-bot) <rhdh-bot@redhat.com>
> chore: switch SEGMENT_WRITE_KEY in release-1.5

- dynamic-plugins/wrappers/backstage-community-plugin-3scale-backend-dynamic/package.json
- dynamic-plugins/wrappers/backstage-community-plugin-analytics-provider-segment/package.json
- dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-keycloak-dynamic/package.json
- dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-pingidentity-dynamic/package.json
- dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-scaffolder-relation-processor-dynamic/package.json
- dynamic-plugins/wrappers/backstage-community-plugin-jfrog-artifactory/package.json
- dynamic-plugins/wrappers/backstage-community-plugin-nexus-repository-manager/package.json
- dynamic-plugins/wrappers/backstage-community-plugin-ocm-backend-dynamic/package.json
- dynamic-plugins/wrappers/backstage-community-plugin-ocm/package.json
- dynamic-plugins/wrappers/backstage-community-plugin-scaffolder-backend-module-kubernetes-dynamic/package.json
- dynamic-plugins/wrappers/backstage-community-plugin-scaffolder-backend-module-regex-dynamic/package.json
- dynamic-plugins/wrappers/backstage-community-plugin-scaffolder-backend-module-servicenow-dynamic/package.json
- dynamic-plugins/wrappers/backstage-community-plugin-scaffolder-backend-module-sonarqube-dynamic/package.json
- yarn.lock
Use plugins updated to backstage 1.35:
- @backstage-community/scaffolder-backend-module-regex@2.4.0
pr: https://github.com/backstage/community-plugins/pull/2807
- @backstage-community/plugin-3scale-backend@3.2.0
pr: https://github.com/backstage/community-plugins/pull/2788
- @backstage-community/plugin-scaffolder-backend-module-sonarqube@2.4.0
pr: https://github.com/backstage/community-plugins/pull/2787
- @backstage-community/plugin-analytics-provider-segment@1.12.0
pr: https://github.com/backstage/community-plugins/pull/2759
- @backstage-community/plugin-scaffolder-backend-module-kubernetes@2.4.0
pr: https://github.com/backstage/community-plugins/pull/2726
- @backstage-community/plugin-catalog-backend-module-pingidentity@0.2.0
pr: https://github.com/backstage/community-plugins/pull/2810
- …
> chore(deps): use some plugins updated to backstage 1.35

- docs/auth.md
- packages/app/config.d.ts
- packages/backend/src/modules/authProvidersModule.ts
- packages/backend/src/transitiveGroupOwnershipResolver.test.ts
- packages/backend/src/transitiveGroupOwnershipResolver.ts
Transitive fits better in this case because group hierarchical relationships are persistent.
* Provides update to [this PR](https://github.com/redhat-developer/rhdh/pull/2210)
- Fixes [RHIDP-5506](https://issues.redhat.com/browse/RHIDP-5506)
> chore: update GroupOwnershipResolver and config name

- e2e-tests/playwright/e2e/audit-log/scaffold.spec.ts
- e2e-tests/playwright/e2e/github-happy-path.spec.ts
- e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
- e2e-tests/playwright/support/pageObjects/page-obj.ts
- e2e-tests/playwright/support/pageObjects/rbac-po.ts
- e2e-tests/playwright/support/pages/home-page.ts
- e2e-tests/playwright/support/pages/rbac.ts
- e2e-tests/playwright/utils/ui-helper.ts
- Fixes https://issues.redhat.com/browse/RHIDP-5964
> chore(e2e): fix rbac `users, groups` with regex

- e2e-tests/playwright.config.ts
- e2e-tests/playwright/e2e/github-integration-org-fetch.spec.ts
- e2e-tests/playwright/e2e/plugins/bulk-import.spec.ts
- e2e-tests/playwright/e2e/plugins/topology/topology.spec.ts
- e2e-tests/playwright/support/pageObjects/rbac-po.ts
- e2e-tests/playwright/utils/common.ts
- e2e-tests/playwright/utils/ui-helper.ts
Fix k8s specific config that is overriding the `default defineConfig`.
- Fixes [RHIDP-5965](https://issues.redhat.com/browse/RHIDP-5965)
> chore(e2e): update k8s specific config

- .ibm/pipelines/utils.sh
- Temporary until [RHIDP-6064](https://issues.redhat.com/browse/RHIDP-6064) is fixed
> chore(ci): don't fail pipeline when `droute` error

- e2e-tests/playwright/e2e/authProviders/basic-authentication.spec.ts
- e2e-tests/playwright/e2e/authProviders/github-provider.spec.ts
- e2e-tests/playwright/e2e/authProviders/microsoft-provider.spec.ts
Adjust timeouts in auth providers e2e tests
- Fixes #?
> fix: fix auth providers timeouts

- e2e-tests/playwright/e2e/audit-log/scaffold.spec.ts
- e2e-tests/playwright/e2e/plugins/quay/quay.spec.ts
- e2e-tests/playwright/utils/quay/quay.ts
- e2e-tests/playwright/utils/ui-helper.ts
> chore(e2e): rhidp-5634 Update audit log messages for e2e tests.

- docs/monitoring-and-logging.md
> fix: replace a dead link with a valid one

- .ibm/pipelines/value_files/sanity-check-plugins.yaml
- .ibm/pipelines/value_files/values_showcase.yaml
- e2e-tests/playwright/e2e/techdocs.spec.ts
- e2e-tests/playwright/support/pages/catalog.ts
- e2e-tests/playwright/utils/ui-helper.ts
Introduces techdocs addon tests for ReportIssue.
Adds entity tab techdocs test.
- Fixes [RHIDP-5223](https://issues.redhat.com/browse/RHIDP-5223)
> chore(e2e): techdocs addons tests

- dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-bulk-import-backend-dynamic/package.json
- dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-bulk-import/package.json
- e2e-tests/playwright/support/pages/bulk-import.ts
- yarn.lock
Updates the bulk import plugins to ensure that we grab the latest changes.
- Fixes [RHIDP-5721](https://issues.redhat.com/browse/RHIDP-5721)
> chore: update bulk import plugins

- e2e-tests/playwright/e2e/github-happy-path.spec.ts
> chore(ci): fix GH test where there is only one issue

- e2e-tests/OWNERS
Align OWNERS of e2e-tests for `release-1.3` with `main`
- Fixes #?
> chore(e2e): update owners for e2e-tests

- e2e-tests/playwright.config.ts
Added a new test project named "any-test" in the Playwright configuration. This allows running any test file matching the "*.spec.ts" pattern, improving test execution flexibility. No existing configurations were altered.
- Fixes #?
> chore(e2e): add new test project to Playwright config for flexibility

- e2e-tests/playwright/e2e/authProviders/basic-authentication.spec.ts
- e2e-tests/playwright/e2e/authProviders/github-provider.spec.ts
- e2e-tests/playwright/e2e/authProviders/microsoft-provider.spec.ts
- e2e-tests/playwright/e2e/authProviders/rhsso-76-provider.spec.ts
Fix broken signout flow in auth providers e2e
- Fixes [RHIDP-6129](https://issues.redhat.com/browse/RHIDP-6129) 
> fix: fix signout

- .ibm/pipelines/utils.sh
- Fixes [RHIDP-6064](https://issues.redhat.com/browse/RHIDP-6064)
> chore(ci): fix rsync interference & droute re-enable (#2414)

- e2e-tests/playwright/e2e/smoke-test.spec.ts
Switched the login method from Keycloak user to guest user in the smoke test setup
- Fixes #?
> chore(e2e): update smoke test to login as guest user

- e2e-tests/playwright.config.ts
> chore(e2e): add new test project configuration for generic test runs

- e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
> test(e2e): fix rbac nightly test on 1.4

- e2e-tests/playwright/e2e/authProviders/basic-authentication.spec.ts
- e2e-tests/playwright/e2e/authProviders/github-provider.spec.ts
- e2e-tests/playwright/e2e/authProviders/microsoft-provider.spec.ts
- e2e-tests/playwright/e2e/authProviders/rhsso-76-provider.spec.ts
Fix e2e signout in auth providers tests
- Fixes [RHIDP-6129](https://issues.redhat.com/browse/RHIDP-6129) 
> fix: fix e2e signout in auth providers tests

- docker/install-dynamic-plugins.py
This change adds a `pullPolicy` configuration to better support floating tags for OCI artifacts.  This variable is similar to `forceDownload` but is intended to bring behavior that is more consistent with other platforms that deal with image containers.  The possible settings for `pullPolicy` are:
- `Always`: install-dynamic-plugins.py will compare the image digest in the remote registry and download the artifact if it has changed, regardless if the plugin has been downloaded already.
- `IfNotPresent`: install-dynamic-plugins.py will not compare image digests and instead only download the artifact if it is not present already in the dynamic-plugins-root folder.
These settings have also been applied to the NPM downloading method, however `Always` will always download the remote artifact …
> fix(init): proper floating tag support

- dynamic-plugins/wrappers/backstage-community-plugin-rbac/package.json
- e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
- e2e-tests/playwright/support/pageObjects/page-obj.ts
- e2e-tests/playwright/support/pageObjects/rbac-po.ts
- yarn.lock
Cherry-picking updates to rbac version and e2e updates with the fix for bulk import
- Fixes #?
> [release-1.5] chore(e2e): update RBAC plugin version, add E2E tests to Showcase/RHDH

- .ibm/images/Dockerfile
add Operator SDK into e2e-runner image
- Needed for [RHIDP-4550](https://issues.redhat.com/browse/RHIDP-4550) and [RHIDP-2155](https://issues.redhat.com/browse/RHIDP-2155)
> chore(ci): add Operator SDK into e2e-runner image

- .ibm/pipelines/resources/config_map/app-config-rhdh.yaml
- .ibm/pipelines/value_files/values_showcase-rbac.yaml
- .ibm/pipelines/value_files/values_showcase.yaml
- dynamic-plugins/wrappers/backstage-community-plugin-rbac/package.json
- e2e-tests/playwright/e2e/audit-log/scaffold.spec.ts
- e2e-tests/playwright/e2e/authProviders/basic-authentication.spec.ts
- e2e-tests/playwright/e2e/authProviders/github-provider.spec.ts
- e2e-tests/playwright/e2e/authProviders/microsoft-provider.spec.ts
- e2e-tests/playwright/e2e/authProviders/rhsso-76-provider.spec.ts
- e2e-tests/playwright/e2e/default-global-header.spec.ts
- e2e-tests/playwright/e2e/github-happy-path.spec.ts
- e2e-tests/playwright/e2e/google-signin-happy-path.spec.ts
- e2e-tests/playwright/e2e/guest-signin-happy-path.spec.ts
- e2e-tests/playwright/e2e/plugins/analytics/analytics-disabled-rbac.spec.ts
- e2e-tests/playwright/e2e/plugins/dynamic-plugins-info/dynamic-plugins-info.spec.ts
- e2e-tests/playwright/e2e/plugins/http-request.spec.ts
- e2e-tests/playwright/e2e/plugins/kubernetes-actions/kubernetes-actions.spec.ts
- e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
- e2e-tests/playwright/support/pages/bulk-import.ts
- e2e-tests/playwright/utils/custom-theme/theme-verifier.ts
- e2e-tests/playwright/utils/ui-helper.ts
Cherry pick commits of global header e2e tests.
> [release-1.5] chore(e2e-tests): cherry pick global header e2e tests commits

- .ibm/pipelines/resources/config_map/dynamic-global-header-config.yaml
- .ibm/pipelines/utils.sh
- .ibm/pipelines/value_files/values_showcase.yaml
- dynamic-plugins/_utils/src/wrappers.test.ts
- e2e-tests/playwright/e2e/header-mount-points.spec.ts
Cherry pick commits of global header mount points e2e tests.
> [release-1.5] chore(e2e-tests): add e2e tests for header mount points

- .ibm/pipelines/resources/config_map/app-config-rhdh.yaml
- e2e-tests/playwright/e2e/verify-redis-cache.spec.ts
Update Redis tests: removing useRedisSets optino (no lnger supported), validate key format
- Fixes [RHIDP-5183](https://issues.redhat.com/browse/RHIDP-5183)
> test: update redis tests

- e2e-tests/playwright/e2e/plugins/topology/topology.spec.ts
> chore(e2e): fix topology plugin test

- dynamic-plugins/wrappers/backstage-community-plugin-rbac/package.json
- e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
- yarn.lock
- Fixes #https://issues.redhat.com/browse/RHIDP-6062
- Fixes #https://issues.redhat.com/browse/RHIDP-6063
- Fixes #https://issues.redhat.com/browse/RHIDP-6029
> chore(rbac): update RBAC frontend plugin

- e2e-tests/playwright/e2e/audit-log/log-utils.ts
- e2e-tests/playwright/e2e/verify-redis-cache.spec.ts
- e2e-tests/playwright/utils/quay/quay.ts
https://issues.redhat.com/browse/RHIDP-6245 
> chore(e2e): fix flaky e2e tests

- dynamic-plugins/wrappers/backstage-community-plugin-azure-devops-backend-dynamic/package.json
- dynamic-plugins/wrappers/backstage-community-plugin-azure-devops/package.json
- dynamic-plugins/wrappers/backstage-community-plugin-dynatrace/package.json
- dynamic-plugins/wrappers/backstage-community-plugin-github-actions/package.json
- dynamic-plugins/wrappers/backstage-community-plugin-github-issues/package.json
- dynamic-plugins/wrappers/backstage-community-plugin-jenkins-backend-dynamic/package.json
- dynamic-plugins/wrappers/backstage-community-plugin-jenkins/package.json
- dynamic-plugins/wrappers/backstage-community-plugin-lighthouse/package.json
- dynamic-plugins/wrappers/backstage-community-plugin-scaffolder-backend-module-quay-dynamic/package.json
- dynamic-plugins/wrappers/backstage-community-plugin-sonarqube-backend-dynamic/package.json
- dynamic-plugins/wrappers/backstage-community-plugin-sonarqube/package.json
- dynamic-plugins/wrappers/backstage-community-plugin-tech-radar-backend-dynamic/package.json
- dynamic-plugins/wrappers/backstage-community-plugin-tech-radar/package.json
- dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab-backend-dynamic/package.json
- dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab/package.json
- dynamic-plugins/wrappers/roadiehq-backstage-plugin-datadog/package.json
- dynamic-plugins/wrappers/roadiehq-backstage-plugin-github-insights/package.json
- dynamic-plugins/wrappers/roadiehq-backstage-plugin-github-pull-requests/package.json
- dynamic-plugins/wrappers/roadiehq-backstage-plugin-jira/package.json
- dynamic-plugins/wrappers/roadiehq-backstage-plugin-security-insights/package.json
- dynamic-plugins/wrappers/roadiehq-scaffolder-backend-argocd-dynamic/package.json
- dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-http-request-dynamic/package.json
- dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-utils-dynamic/package.json
- yarn.lock
Bump some of the @backstage-community, @immobiliarelabs and roadie plugins version to backstage v1.35.1.
Fixes: https://issues.redhat.com/browse/RHIDP-6271
> chore(deps): update some @backstage-community and roadie plugins to 1.35

- e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
- Fixes https://issues.redhat.com/browse/RHIDP-6295
> test(e2e): add wait for animations

- e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
same as https://github.com/redhat-developer/rhdh/pull/2519
- Fixes https://issues.redhat.com/browse/RHIDP-6295
> test(e2e): add waitForAnimations uihelper main

- .github/workflows/push-e2e-runner.yaml
- .ibm/images/README
> chore(e2e): rhidp-6297 Automate E2E Runner Image Build and Push to Quay via GitHub Actions

- dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-catalog-backend-module-marketplace-dynamic/package.json
- yarn.lock
Bump catalog-backend-module 0.2.2 to include missing annotations fix.
- https://issues.redhat.com/browse/RHIDP-6365 
> fix(marketplace): bump catalog-backend-module

- .dockerignore
- .ibm/images/Dockerfile
- Fixes https://issues.redhat.com/browse/RHIDP-6351
> chore(e2e): install pinned version of yarn v3 using corepack, instead of v1

- docs/customization.md
- docs/index.md
Updated `Customizing the Sidebar Menu Items` section in customization.md
> fix(docs): updated customization.md

- .rhdh/docker/Dockerfile
- docker/Dockerfile
Update to the latest versions
- Fixes #?
- https://issues.redhat.com/browse/RHIDP-6417
> chore: [release-1.5] update dockerfile images

- dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-global-floating-action-button/package.json
Updated the keywords in the FAB wrapper's package.json
- Fixes https://issues.redhat.com/browse/RHIDP-6406
> fix: make FAB plugin RH supported

- .ibm/pipelines/jobs/upgrade.sh
- .ibm/pipelines/utils.sh
Fix config namespace issue in the upgrade test.
- Fixes [RHIDP-6444](https://issues.redhat.com/browse/RHIDP-6444)
> fix(e2e): config namespace issue in upgrade test

- e2e-tests/playwright/e2e/extensions.spec.ts
- e2e-tests/playwright/support/pages/extensions.ts
- e2e-tests/playwright/utils/ui-helper.ts
Added e2e tests for Marketplace Plugin
[video1.webm](https://github.com/user-attachments/assets/c70cb0b7-1f7d-40b3-abe0-19f710f11414)
[video2.webm](https://github.com/user-attachments/assets/106f64f3-6607-4045-b539-e6d6ca4181a8)
[video3.webm](https://github.com/user-attachments/assets/fda89e38-5f29-484f-b4d7-a251a30a942f)
- Fixes [RHIDP-5323](https://issues.redhat.com/browse/RHIDP-5323)
> chore(e2e): add marketplace e2e tests to rhdh

- docs/dynamic-plugins/frontend-plugin-wiring.md
- packages/app/config.d.ts
- packages/app/src/components/DynamicRoot/DynamicRootContext.tsx
- packages/app/src/utils/dynamicUI/extractDynamicConfig.test.ts
- packages/app/src/utils/dynamicUI/extractDynamicConfig.ts
- packages/app/src/utils/dynamicUI/extractDynamicConfigFrontend.test.ts
- packages/app/src/utils/dynamicUI/extractDynamicConfigFrontend.ts
Fixes: https://issues.redhat.com/browse/RHIDP-6230
This PR introduces a clean way to remove sidebar items by adding a new key enabled which when set to false for a sidebar item then that sidebar item will be removed from the sidebar. This also maintains backward compatibility.
https://github.com/user-attachments/assets/0242309a-38f1-4d9f-9507-4b0880cd671f
https://github.com/user-attachments/assets/4b3edb1c-2439-4861-a393-a6d1fb3c085c
> feat(sidebar): sidebar items can be removed by setting enabled:false

- e2e-tests/playwright/e2e/authProviders/github-provider.spec.ts
- e2e-tests/playwright/e2e/authProviders/microsoft-provider.spec.ts
- e2e-tests/playwright/e2e/authProviders/rhsso-76-provider.spec.ts
- e2e-tests/playwright/utils/common.ts
Adds tests to each provider to check that `sessionDuration` is set corrected and reflected in the cookie age in the browser
- Fixes [RHIDP-6370](https://issues.redhat.com/browse/RHIDP-6370)
> chore(e2e): add tests to 'sessionDuration' auth config

- .ibm/pipelines/utils.sh
- Fixes https://issues.redhat.com/browse/RHIDP-6445
> chore(ci): fix droute error handling

- dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-bulk-import-backend-dynamic/package.json
- yarn.lock
Updates the bulk import backend plugin to include the new auditor updates
- Fixes [RHIDP-5988](https://issues.redhat.com/browse/RHIDP-5988)
> chore(deps): update bulk import backend plugin

- dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-keycloak-dynamic/package.json
- yarn.lock
Update keycloak version for 1.6 to include https://github.com/backstage/community-plugins/pull/3269 and https://github.com/backstage/community-plugins/pull/3445
- Fixes https://issues.redhat.com/browse/RHIDP-6087
> chore: update keycloak version for 1.6

- yarn.lock
* ran `yarn up -R xml-crypto` to update the dependency
- Fixes #?
- https://issues.redhat.com/browse/RHIDP-6635
> chore: fix CVE-2025-29775

- .github/actions/check-image-and-changes/action.yaml
- .github/workflows/pr-build-image.yaml
> Update workflow to use SHORT_SHA from environment variables

- .ibm/pipelines/utils.sh
- e2e-tests/playwright/e2e/plugins/kubernetes-actions/kubernetes-actions.spec.ts
- Fixes https://issues.redhat.com/browse/RHIDP-6445
> chore(ci): droute with bastion pod - switch contexts and enhanced waiting in retries (#2599)

- e2e-tests/playwright/e2e/verify-tls-config-health-check.spec.ts
https://issues.redhat.com/browse/RHIDP-6693
- Fixes #?
> chore(e2e): fix failing e2e tests - Operator Postgres DB with TLS

- packages/app/public/index.html
- packages/app/src/components/AppBase/AppBase.tsx
backport of https://github.com/redhat-developer/rhdh/pull/2408
fixes https://issues.redhat.com/browse/RHIDP-6664
> [release-1.5] fix(favicon): re-embed dynamic favicon into index.html

- .github/actions/check-image-and-changes/action.yaml
- .github/workflows/pr-build-image.yaml
Ensure SHORT_SHA is exported for context reuse and update the image tagging strategy for PR builds
- Fixes #?
> chore: add SHORT_SHA handling and refine PR image tagging logic

- e2e-tests/playwright/utils/common.ts
Backporting [fix](https://github.com/redhat-developer/rhdh/pull/2536) 
- Fixes https://issues.redhat.com/browse/RHIDP-6331 
> test: fix displayName null in auth-providers

- .github/actions/check-image-and-changes/action.yaml
- .github/workflows/pr-build-image.yaml
> chore: fixed GH action Check Image and Relevant Changes

- e2e-tests/playwright/e2e/plugins/keycloak/catalog-users.spec.ts
> chore(e2e): skip keycloak test

- e2e-tests/playwright/utils/common.ts
Fix Github login in auth providers tests.
- Fixes [RHIDP-6759](https://issues.redhat.com/browse/RHIDP-6759)
> test: fix Github login in auth providers tests

- dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-catalog-backend-module-marketplace-dynamic/package.json
- dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace-backend-dynamic/package.json
- dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace/package.json
- yarn.lock
Update marketplace packages version to include the new install page feature.
- For [RHIDP-6170](https://issues.redhat.com/browse/RHIDP-6170)
> feat(marketplace): introduce the install page

- dynamic-plugins/wrappers/backstage-community-plugin-nexus-repository-manager/package.json
- yarn.lock
For [RHIDP-6529](https://issues.redhat.com/browse/RHIDP-6529)
> chore(nexus-repo-manager): update package version 

- dynamic-plugins/wrappers/backstage-community-plugin-nexus-repository-manager/package.json
- yarn.lock
Manual cherry pick changes for PR #2695 
> chore(nexus-repo-manager): update package version

- .ibm/pipelines/resources/config_map/dynamic-plugins-config.yaml
- e2e-tests/playwright/e2e/plugins/frontend/sidebar.spec.ts
Add e2e for sidebar config to hide menu-items
- Fixes [RHIDP-6596](https://issues.redhat.com/browse/RHIDP-6596)
> chore(e2e): e2e for sidebar config to hide

- e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
https://issues.redhat.com/browse/RHIDP-6912
> chore(e2e): fix rbac test failure due to animation

- python/requirements-build.in
- python/requirements-build.txt
- python/requirements.in
- python/requirements.txt
chore(deps): remove playwright + its deps pyee and greenlet, as we no longer need these downstream
N/A
RHIDP-6561, [RHIDP-6756](https://issues.redhat.com//browse/RHIDP-6756)
N/A
> chore(deps): remove playwright + its deps pyee and greenlet, as we no longer need these downstream (RHIDP-6561, RHIDP-6756)

- .github/renovate.json
Disable Zod updates due to breaking changes
- Fixes #?
https://issues.redhat.com/browse/RHIDP-6960
> chore: add renovate config to ignore zod updates

- dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-bulk-import/package.json
- dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-global-floating-action-button/package.json
- dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-global-header/src/index.ts
- e2e-tests/playwright/e2e/plugins/global-floating-button.spec.ts
- yarn.lock
Manual cherry-pick of https://github.com/redhat-developer/rhdh/pull/2673
> [release-1.6] chore: update plugin wrappers

- packages/app/package.json
- yarn.lock
Manual cherry pick #2741 , closes [RHIDP-6603](https://issues.redhat.com/browse/RHIDP-6603)
Test on RHDH local
Test on cluster:
> [release-1.6] chore(theme): cherry pick theme update

- python/cachito_hash.sh
chore(deps): add missing python/cachito_hash.sh to main (already in 1.6 branch)
N/A
N/A
> chore(deps): add missing python/cachito_hash.sh to main (already in 1.6 branch)

- .ibm/pipelines/resources/config_map/app-config-rhdh.yaml
- .ibm/pipelines/value_files/values_showcase.yaml
- e2e-tests/playwright/e2e/plugins/keycloak/catalog-users.spec.ts
- e2e-tests/playwright/utils/kube-client.ts
- Fixes https://issues.redhat.com/browse/RHIDP-6621
> feat(e2e): add keycloak metrics test

- dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd/package.json
- dynamic-plugins/wrappers/backstage-community-plugin-tekton/package.json
- dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-dynamic-home-page/package.json
- yarn.lock
Update tekton, argocd, home-page wrappers to backstage@1.36
- Fixes #[RHIDP-6310](https://issues.redhat.com//browse/RHIDP-6310)
> feat(wrappers): update tekton, argocd, home-page

- .ibm/pipelines/resources/config_map/rbac-policy.csv
- dynamic-plugins/wrappers/backstage-community-plugin-rbac/package.json
- e2e-tests/playwright/data/rbac-constants.ts
- e2e-tests/playwright/utils/authenticationProviders/constants.ts
- packages/app/package.json
- packages/app/src/components/Root/Root.tsx
- packages/backend/package.json
- plugins/licensed-users-info-backend/package.json
- scripts/rhdh-openshift-setup/resources/rbac-policies.yaml
- yarn.lock
Updates the rbac plugins to use the new conditional rule `IsOwner`
- Fixes [RHIDP-6270](https://issues.redhat.com/browse/RHIDP-6270)
> chore(deps): update the RBAC plugins

- dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-bulk-import/package.json
- dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-global-floating-action-button/package.json
- dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-global-header/package.json
- dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace/package.json
- e2e-tests/playwright/e2e/default-global-header.spec.ts
- e2e-tests/playwright/e2e/extensions.spec.ts
- e2e-tests/playwright/support/pages/extensions.ts
- yarn.lock
Include plugin changes:
- d5cc14d: added MUI class generator
From https://github.com/redhat-developer/rhdh-plugins/blob/main/workspaces/global-floating-action-button/plugins/global-floating-action-button/CHANGELOG.md
- 8c2bdd9: add inline div styles to the FloatingButton element
- 038f03e: render fab on document body when the target element is not found
- 51c4635: fix fab position to append to Backstage-Root
From https://github.com/redhat-developer/rhdh-plugins/blob/main/workspaces/global-header/plugins/global-header/CHANGELOG.md
- 72cf928: Add keyboard navigation support to global header menu items
- 41ebaf4: remove search bar underline
- ba8628d: Added a new application launcher dropdown to the global header which can be used to configure application links and quick links.
- d49d965: …
> [release-1.6] chore: update bulk-import frontend, global-fab, global-header and marketplace plugins

- .ibm/pipelines/resources/config_map/rbac-policy.csv
- dynamic-plugins/wrappers/backstage-community-plugin-rbac/package.json
- e2e-tests/playwright/data/rbac-constants.ts
- e2e-tests/playwright/utils/authenticationProviders/constants.ts
- packages/app/package.json
- packages/app/src/components/Root/Root.tsx
- packages/backend/package.json
- plugins/licensed-users-info-backend/package.json
- scripts/rhdh-openshift-setup/resources/rbac-policies.yaml
- yarn.lock
Updates the rbac plugins to use the new conditional rule `IsOwner`. Manual cherry pick of #2765 
- Fixes [RHIDP-6270](https://issues.redhat.com/browse/RHIDP-6270)
> [release-1.6] chore(deps): update the RBAC plugins

- .ibm/pipelines/resources/config_map/app-config-rhdh-rbac.yaml
- .ibm/pipelines/value_files/values_showcase-rbac.yaml
- e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
- e2e-tests/playwright/e2e/plugins/topology/topology-rbac.spec.ts
- e2e-tests/playwright/e2e/plugins/topology/topology.spec.ts
- e2e-tests/playwright/support/pageObjects/rbac-po.ts
- e2e-tests/playwright/support/pages/rbac.ts
- e2e-tests/playwright/support/pages/topology.ts
- e2e-tests/playwright/utils/helper.ts
Introduces tests for newly added Topology permissions with RBAC.
- Fixes [RHIDP-6384](https://issues.redhat.com/browse/RHIDP-6384)
> test(topology): introduce e2e tests for Topology with RBAC

- packages/app/package.json
- yarn.lock
For [RHIDP-6603](https://issues.redhat.com/browse/RHIDP-6603)
RHDH local test
Cluster test
> fix(theme): fix outline button on bulk import add page and extensions install page

- .ibm/pipelines/openshift-ci-tests.sh
- e2e-tests/playwright/e2e/plugins/quay/quay.spec.ts
cherry-pick quay test fix from main into 1.5 release from PR : https://github.com/redhat-developer/rhdh/pull/2383/files#diff-8fcabf4014f75ebe991889102e4ee615635945c7122f34e99a5895c17e191ef3 
- Fixes #?
> chore(e2e): cherry-pick quay test fix from main into 1.5 release from PR#2383

- e2e-tests/playwright/e2e/plugins/keycloak/catalog-users.spec.ts
> feat(e2e): increase route timeout for keycloak metrics

- dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace/package.json
- yarn.lock
Update extension/marketplace plugin to include https://github.com/redhat-developer/rhdh-plugins/pull/682
For screenshots see the rhdh-plugins change
- Fixes https://issues.redhat.com/browse/RHIDP-6688
Use this test catalog plugin:
```yaml
catalog:
locations:
- type: url
target: https://github.com/redhat-developer/rhdh-plugins/blob/main/workspaces/marketplace/examples/plugins/no-icon-no-description.yaml
rules:
- allow: [Plugin]
```
> fix(extensions): show a no-icon-icon when the icon is missing in the plugin metadata

- packages/app/package.json
- packages/app/src/components/DynamicRoot/DynamicRoot.tsx
- packages/app/src/components/DynamicRoot/Loader.tsx
- yarn.lock
- For [RHIDP-6601](https://issues.redhat.com/browse/RHIDP-6601)
Know issues:
1. Searchbar underline when focused: will be fixed in #2750 
2. Bulk import button misplaced: will be fixed in #2750
https://github.com/user-attachments/assets/f5613195-51a1-4da3-bdfb-bd836d42954b
> feat(theme): replace theme package with rhdh-plugins theme plugin

- .rhdh/docker/Dockerfile
- docker/Dockerfile
> chore: fix yarn-install.log

- .rhdh/docker/Dockerfile
- docker/Dockerfile
> [release-1.6] chore: fix yarn-install.log

- .github/workflows/link-checker.config.json
update linkchecker configuration to retry on 429 Too Many Requests
status code
> chore(ci): linkchecker: retry on 429

- .rhdh/docker/Dockerfile
- docker/Dockerfile
Updating to the latest [ubi9/nodejs-20](https://catalog.redhat.com/software/containers/ubi9/nodejs-20/64770ac7a835530172eee6a9?image=6811ea5e1262d0c8c55d5237) and [ubi9/nodejs-20-minimal](https://catalog.redhat.com/software/containers/ubi9/nodejs-20-minimal/64770ddd0e699534bb564b3b?image=6811fceef254c8a343817caf) images
- Fixes #?
> chore: release-1.5: update dockerfiles

- .ibm/pipelines/jobs/operator.sh
- .ibm/pipelines/resources/rhdh-operator/rhdh-start-rbac.yaml
- .ibm/pipelines/resources/rhdh-operator/rhdh-start.yaml
This is an cherry-pick of https://github.com/redhat-developer/rhdh/pull/2858
- Fixes #?
> [release-1.5] chore(e2e): fix rhdh operator nightly job hardcoded image tag with dynamic release tag.

- catalog-entities/marketplace/packages/red-hat-developer-hub-backstage-plugin-global-header.yaml
- dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-global-header/package.json
- dynamic-plugins/yarn.lock
Updates the global-header wrapper version so that it displays the correct user name in the profile dropdown when the user logs in via OIDC auth
- Fixes https://issues.redhat.com/browse/RHIDP-7057
Screenshot:
> chore: update global-header wrapper version

- dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-dynamic-home-page/package.json
- dynamic-plugins/yarn.lock
Fixes : https://issues.redhat.com/browse/RHIDP-7009
https://github.com/user-attachments/assets/2cb962a7-8cb4-4c49-817f-a6ad704362a2
https://github.com/user-attachments/assets/230aba53-532e-4e02-b90e-e59cc2e49f34
> fix(homepage): update dynamic-home-page-version to 1.3.1

- .ibm/pipelines/utils.sh
- .ibm/pipelines/value_files/values_showcase-rbac.yaml
- e2e-tests/playwright/e2e/verify-tls-config-with-external-postgres-db.spec.ts
> chore(e2e): disable external postgres-db test

- catalog-entities/marketplace/packages/red-hat-developer-hub-backstage-plugin-global-header.yaml
- dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-global-header/package.json
- yarn.lock
Updates the global-header wrapper version so that it displays the correct user name in the profile dropdown when the user logs in via OIDC auth
Manual cherry-pick of https://github.com/redhat-developer/rhdh/pull/2844
- Fixes https://issues.redhat.com/browse/RHIDP-7380
> [release-1.6] chore: update global-header wrapper version

- .ibm/pipelines/openshift-ci-tests.sh
- .ibm/pipelines/reporting.sh
- .ibm/pipelines/utils.sh
This pull request, accompanied by PR https://github.com/openshift/release/pull/65448, enables advanced reporting in a separate step of OpenShift CI for increased resilience.
- Fixes #?
> chore(ci): move enhanced reporting to post step

- .ibm/images/Dockerfile
- .ibm/pipelines/clear-database.sh
- .ibm/pipelines/jobs/periodic.sh
- .ibm/pipelines/openshift-ci-tests.sh
- .ibm/pipelines/utils.sh
- e2e-tests/playwright/e2e/configuration-test/config-map.spec.ts
- e2e-tests/playwright/e2e/verify-tls-config-health-check.spec.ts
- e2e-tests/playwright/utils/kube-client.ts
> chore(e2e): rhidp-7172 Plugin 'permission' fails during startup

- .ibm/pipelines/reporting.sh
- .ibm/pipelines/utils.sh
> chore(ci): fix reporting

- yarn.lock
issued a yarn up -R tar-fs on the root yarn.lock file
- Fixes #?
https://issues.redhat.com/browse/RHIDP-7701
> chore: release-1.6: update tar-fs to fix CVE-2025-48387

- dynamic-plugins/yarn.lock
- yarn.lock
issued a `yarn up -R tar-fs` on the root and dynamic-plugins yarn.lock files
- Fixes #?
https://issues.redhat.com/browse/RHIDP-7735
> chore: update tar-fs to fix CVE-2025-48387

- docs/dynamic-plugins/export-derived-package.md
Remove broken that makes GH actions fail
- Fixes #?
> docs: remove broken link

- e2e-tests/playwright/utils/authentication-providers/rhdh-deployment.ts
Fix wrong tag in auth providers job
- Fixes #?
> test: set image tag in CR from envs

- .ibm/pipelines/value_files/diff-values_showcase-sanity-plugins.yaml
- e2e-tests/playwright/e2e/default-global-header.spec.ts
- e2e-tests/playwright/e2e/verify-tls-config-health-check.spec.ts
- e2e-tests/playwright/support/api/notifications.ts
- e2e-tests/playwright/utils/ui-helper.ts
- Added a new method in the UI helper to mark all notifications as read if visible.
- Updated the notifications API to include a method for marking notifications as read.
- Fixes https://issues.redhat.com/browse/RHIDP-7859
> refactor(e2e): comment out existing tests and enhance notification handling

- e2e-tests/playwright/e2e/authProviders/github-happy-path.spec.ts
- e2e-tests/playwright/e2e/plugins/quay/quay.spec.ts
- e2e-tests/playwright/e2e/techdocs.spec.ts
- e2e-tests/playwright/e2e/verify-redis-cache.spec.ts
Our backstage showcase catalog entity was updated to better reflect the transition to RHDH. However, this has led to some test failures. This PR aims to fix the references in the e2e tests.
- Fixes #?
> fix(e2e): update backstage-showcase refs to rhdh

- dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-http-request-dynamic/package.json
- dynamic-plugins/yarn.lock
- Fixes https://issues.redhat.com/browse/RHIDP-7908
> chore: update @roadiehq/scaffolder-backend-module-http-request

- e2e-tests/playwright/e2e/authProviders/microsoft.spec.ts
Add default environment variables for msgraph
- Fixes #?
> test: add default msgraph envs 

- .ibm/pipelines/cluster/aks/auto-label/create-azure-tag-policy.sh
[RHIDP-8042](https://issues.redhat.com//browse/RHIDP-8042) Create Azure Policy to Enforce Default Tags for RHDH QE Subscription
https://issues.redhat.com/browse/RHIDP-8042
> chore(e2e): rhidp-8042 Create Azure Policy to Enforce Default Tags for RHDH QE Subscription

- catalog-entities/marketplace/packages/immobiliarelabs-backstage-plugin-gitlab-backend.yaml
- catalog-entities/marketplace/packages/immobiliarelabs-backstage-plugin-gitlab.yaml
- catalog-entities/marketplace/packages/pagerduty-backstage-plugin-backend.yaml
- catalog-entities/marketplace/packages/pagerduty-backstage-plugin.yaml
- catalog-entities/marketplace/packages/parfuemerie-douglas-scaffolder-backend-module-azure-repositorie.yaml
- catalog-entities/marketplace/packages/roadiehq-backstage-plugin-argo-cd-backend.yaml
- catalog-entities/marketplace/packages/roadiehq-backstage-plugin-datadog.yaml
- catalog-entities/marketplace/packages/roadiehq-backstage-plugin-github-insights.yaml
- catalog-entities/marketplace/packages/roadiehq-backstage-plugin-github-pull-requests.yaml
- catalog-entities/marketplace/packages/roadiehq-backstage-plugin-jira.yaml
- catalog-entities/marketplace/packages/roadiehq-backstage-plugin-security-insights.yaml
- catalog-entities/marketplace/packages/roadiehq-scaffolder-backend-argocd.yaml
- catalog-entities/marketplace/packages/roadiehq-scaffolder-backend-module-http-request.yaml
- catalog-entities/marketplace/packages/roadiehq-scaffolder-backend-module-utils.yaml
- dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab-backend-dynamic/package.json
- dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab/package.json
- dynamic-plugins/wrappers/pagerduty-backstage-plugin-backend-dynamic/package.json
- dynamic-plugins/wrappers/pagerduty-backstage-plugin/package.json
- dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd-backend-dynamic/package.json
- dynamic-plugins/wrappers/roadiehq-backstage-plugin-datadog/package.json
- dynamic-plugins/wrappers/roadiehq-backstage-plugin-github-insights/package.json
- dynamic-plugins/wrappers/roadiehq-backstage-plugin-github-pull-requests/package.json
- dynamic-plugins/wrappers/roadiehq-backstage-plugin-jira/package.json
- dynamic-plugins/wrappers/roadiehq-backstage-plugin-security-insights/package.json
- dynamic-plugins/wrappers/roadiehq-scaffolder-backend-argocd-dynamic/package.json
- dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-utils-dynamic/package.json
- dynamic-plugins/yarn.lock
Round of third party plugin updates for the Backstage 1.39.1 update
- Fixes [RHIDP-7152](https://issues.redhat.com/browse/RHIDP-7152)
> chore(deps): bump third party plugins to 1.39.1

- yarn.lock
This is a corresponding fix to https://github.com/redhat-developer/rhdh/pull/3038 on the root yarn.lock file
- Fixes #?
> chore: update pbkdf2 to v3.1.3

- .ibm/pipelines/reporting.sh
- .ibm/pipelines/utils.sh
- e2e-tests/playwright/e2e/default-global-header.spec.ts
- e2e-tests/playwright/e2e/plugins/bulk-import.spec.ts
Quickly skip the tests until we fix them to unblock PRs.
- Fixes #?
- Relates to https://issues.redhat.com/browse/RHDHBUGS-1870 and https://issues.redhat.com/browse/RHDHBUGS-1869
> chore(e2e): skip failing bulk-import and global-header

- .ibm/pipelines/value_files/diff-values_showcase-sanity-plugins.yaml
Disable msgraph plugin in sanity-check until https://issues.redhat.com/browse/RHDHBUGS-1871 is fixed
- Fixes #?
> chore(e2e): skip plugin in sanity-check

- .ibm/pipelines/utils.sh
- .ibm/pipelines/value_files/values_showcase-rbac.yaml
Adds Orchestrator deployment to flow with RBAC
- Additional part of FLPATH-2318.
> chore: add orchestrator deployment to RBAC deployment

- dynamic-plugins/package.json
- dynamic-plugins/wrappers/parfuemerie-douglas-scaffolder-backend-module-azure-repositories-dynamic/package.json
- dynamic-plugins/yarn.lock
Removes the following resolution from the dynamic-plugins package.json
Removes the resolution for "@rjsf/utils": "=5.24.12" since it's now been [resolved](https://github.com/backstage/community-plugins/issues/3253#issuecomment-2820068759)
- Fixes #?
https://issues.redhat.com/browse/RHDHBUGS-1875
> chore: remove resolution from dynamic-plugins

- dynamic-plugins.default.yaml
chore: add missing group headings
N/A
N/A
> chore: add missing group headings in dynamic-plugins.default.yaml

- catalog-entities/marketplace/packages/backstage-community-plugin-acr.yaml
- catalog-entities/marketplace/packages/red-hat-developer-hub-backstage-plugin-lightspeed-backend.yaml
- catalog-entities/marketplace/packages/red-hat-developer-hub-backstage-plugin-lightspeed.yaml
Fix some marketplace entities
- Fixes #?
> fix(marketplace): fix some marketplace entities

- e2e-tests/playwright/e2e/plugins/kubernetes-actions/kubernetes-actions.spec.ts
> chore: remove Portuguese comments from kubernetes-actions.spec.ts

- .ibm/pipelines/resources/rhdh-operator/rhdh-start.yaml
Adds the global-floating-button config to the backstage resource
- Fixes https://issues.redhat.com/browse/RHDHBUGS-699
> fix(e2e): modify operator e2e tests to add the fab config

- e2e-tests/playwright/e2e/authProviders/github-happy-path.spec.ts
- e2e-tests/playwright/e2e/github-integration-org-fetch.spec.ts
- Fixes https://issues.redhat.com/browse/RHDHBUGS-1911
> chore(e2e): fix double names

- dynamic-plugins/yarn.lock
- yarn.lock
- Fixes #?
https://issues.redhat.com/browse/RHIDP-8315
> chore: update form-data to fix CVE-2025-7783

- .ibm/pipelines/value_files/diff-values_showcase-sanity-plugins.yaml
> fix(e2e): sanity plugins failing on microsoft provider (#3206)

- e2e-tests/playwright/e2e/custom-theme.spec.ts
- e2e-tests/playwright/e2e/github-happy-path.spec.ts
Skip from https://github.com/redhat-developer/rhdh/pull/3233 and fix for the e2e
- Fixes [RHDHBUGS-1914](https://issues.redhat.com/browse/RHDHBUGS-1914), [RHDHBUGS-1919](https://issues.redhat.com/browse/RHDHBUGS-1919)
> fix(e2e): fix quick start e2e and skip GitHub Happy path

- catalog-entities/marketplace/packages/dynatrace-backstage-plugin-dql-backend.yaml
- catalog-entities/marketplace/packages/dynatrace-backstage-plugin-dql.yaml
Updated Dynatrace commercial images to use official 1.7 OCI images.
Updated version.
Updated Dynatrace backend config.
- Fixes https://issues.redhat.com/browse/RHIDP-8360
> [release-1.7] fix(dynatrace-commercial): update dynatrace commercial images

- catalog-entities/marketplace/packages/dynatrace-backstage-plugin-dql-backend.yaml
- catalog-entities/marketplace/packages/dynatrace-backstage-plugin-dql.yaml
Updated Dynatrace commercial images to use official 1.7 OCI images.
Updated version.
Updated Dynatrace backend config.
- Fixes https://issues.redhat.com/browse/RHIDP-8360
> fix(dynatrace-commercial): update dynatrace commercial images

- e2e-tests/playwright/e2e/plugins/kubernetes-actions/kubernetes-actions.spec.ts
- e2e-tests/playwright/utils/common.ts
- Fixes  https://issues.redhat.com/browse/RHDHBUGS-1912
> chore(e2e): fix Kubernetes Actions plugin by adding wait (#3226)

- OWNERS
Removed coreydaley from owner file since he's no longer part of the team
- Fixes #?
> chore: update OWNER file to remove coreydaley

- .rhdh/docker/Dockerfile
- docker/Dockerfile
Manual cherrypick of https://github.com/redhat-developer/rhdh/pull/3272
- Fixes #?
> chore: release-1.7 update dockerfiles

- e2e-tests/playwright/e2e/plugins/gitlab/gitlab-discovery.spec.ts
> test: skip gitlab discovery UI tests due to RHDHBUGS-1977

- catalog-entities/marketplace/plugins/servicenow.yaml
Address [RHDH 1.7 Test Day Feedback/issues sheet row 12 issue](https://docs.google.com/spreadsheets/d/14O4IpU3NomiqorkS8Pd8FD7trLm18ZSQg2C9L1C8O2A/edit?gid=88072381#gid=88072381).
- Fixes [RHDHBUGS-1937](https://issues.redhat.com/browse/RHDHBUGS-1937)
> fix(extensions): remove verified badge of servicenow tile

- dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-msgraph-dynamic/package.json
This plugin is well-tested in [microsoft.spec.ts](https://github.com/redhat-developer/rhdh/blob/main/e2e-tests/playwright/e2e/authProviders/microsoft.spec.ts) and documented in the product docs under [Provisioning users from Microsoft Azure to the software catalog](https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.6/html/authentication_in_red_hat_developer_hub/assembly-authenticating-with-microsoft-azure#enabling-authentication-with-microsoft-azure).
- Relates to [RHIDP-7224](https://issues.redhat.com/browse/RHIDP-7224)
> chore: declare production support for msgraph plugin

- .ibm/pipelines/README.md
- .ibm/pipelines/ocp-cluster-claim-login.sh
fix: update namespace validation to support any version in cluster login script
- Fixes #?
> fix: update namespace validation to support any version in cluster login script

- .ibm/pipelines/utils.sh
https://issues.redhat.com/browse/RHDHBUGS-1987
> chore(e2e): fix Operator Installation Failure - No Endpoints Available for Webhook

- yarn.lock
- Fixes #?
https://issues.redhat.com/browse/RHIDP-8684
https://issues.redhat.com/browse/RHIDP-8678
CVE-2025-9288 
CVE-2025-9287
> chore: fix CVE-2025-9288 and CVE-2025-9287

- .rhdh/docker/Dockerfile
- docker/Dockerfile
chore(dockerfile): add missing continuation line to remove warning
N/A
Fixes this warning in GH log:
```
[0m NoEmptyContinuationEmpty continuation line (line 50)
```
N/A
> chore(dockerfile): add missing continuation line to remove warning

- OWNERS
Adds me as a PR approver for prow
- Fixes #?
> chore: add Zaperex as approver for prow

- .github/workflows/pr-podman-push.yaml
Fix typo and also removes redundant check so PR podman push PR comments work now
- Fixes #?
> fix: remove redundant check and fix typo in pr-podman-push

- .github/actions/check-author/action.yaml
- .github/workflows/pr-docker-build.yaml
Adds `authorize` job to the `pr-docker-build.yaml` workflow for security purposes
- Fixes #?
> [release-1.3] chore: add authorize job for pr build image workflow

- packages/app/src/components/DynamicRoot/DynamicRoot.tsx
- packages/app/src/translations/core-components/core-components-en.ts
- packages/app/src/translations/core-components/core-components.ts
Manual backport of #3387 to verify quickly if this solves our problems on RHDH 1.7.
- Fixes https://issues.redhat.com/browse/RHDHBUGS-1976
> [release-1.7] fix(core-components): add missing translations for some core components

- .github/workflows/e2e-tests-lint.yaml
- docs/dynamic-plugins/debugging.md
- docs/proxy.md
- e2e-tests/.lintstagedrc.js
- e2e-tests/.lintstagedrc.json
- e2e-tests/package.json
Introduce TypeScript compiler checks for lint-staged and the GitHub workflow.
- [issues.redhat.com/browse/RHIDP-6736](https://issues.redhat.com/browse/RHIDP-6736)
> chore(e2e): introduce TSC check for e2e-tests

- .ibm/pipelines/cluster/gke/gcloud.sh
- .ibm/pipelines/reporting.sh
- .ibm/pipelines/utils.sh
This PR fixes OCP 4.19, see https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/redhat-developer_rhdh/3453/pull-ci-redhat-developer-rhdh-main-e2e-tests-nightly-ocp-v4-19/1970832751217086464
- Fixes https://issues.redhat.com/browse/RHDHBUGS-2069
> chore(ci): fix OCP 4.19 & GKE error handling

- dynamic-plugins.default.yaml
- packages/app/config.d.ts
This PR adds comprehensive localization support for quickstart steps that can be configured through both `dynamic-plugins.default.yaml` and `app-config.yaml`. The implementation enables translation keys for all quickstart  steps properties including titles, descriptions, and call-to-action buttons.
1. Pull the changes of  https://github.com/redhat-developer/rhdh-plugins/pull/1514 to RHDH by running
```
cd workspaces/quickstart
yarn
yarn tsc
cd plugins/quickstart/
yarn
npx --yes @janus-idp/cli package export-dynamic-plugin --dynamic-plugins-root <path-to-your-rhdh>/dynamic-plugins-root --dev
```
2.  Add below config in `aap-config.yaml`
```
i18n:
locales:
- en
- de
overrides:
- ../../allTranslations.json
app:
quickstart:
- title: Set up authentication123
titleKey: …
```
> feat(quickstart): adding localization support for quickstart steps configured through dynamic-plugins.deafult or app-config

- .ibm/pipelines/openshift-ci-tests.sh
- .ibm/pipelines/reporting.sh
- Fixes https://issues.redhat.com/browse/RHIDP-9040
> chore(ci): update for job rename (#3429)

- e2e-tests/playwright/e2e/github-happy-path.spec.ts
Workaround for failing test 
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/redhat-developer_rhdh/3483/pull-ci-redhat-developer-rhdh-main-e2e-ocp-helm/1973013377349324800/artifacts/e2e-ocp-helm/redhat-developer-rhdh-ocp-helm/artifacts/showcase/index.html#?testId=d49d675e7afa73fe2c07-3a5d104a7e180a0061a3&q=s:failed
- Fixes #?
> fix(e2e): github-happy-path workaround for failing test

- OWNERS
Update OWNERS - remove dominika and mitesh as default reviewers
- Fixes #?
> chore: remove dominika and mitesh as default reviewers

- e2e-tests/playwright/e2e/github-happy-path.spec.ts
- e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
- e2e-tests/playwright/e2e/plugins/topology/topology.spec.ts
> chore: disable flaky tests

- dynamic-plugins.default.yaml
- dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-adoption-insights-backend-dynamic/package.json
- dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-adoption-insights/package.json
- dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-analytics-module-adoption-insights-dynamic/package.json
- dynamic-plugins/yarn.lock
- e2e-tests/playwright/e2e/plugins/adoption-insights/adoption-insights.spec.ts
- e2e-tests/playwright/support/pages/adoption-insights.ts
This PR bumps the adoption insights plugin versions and includes the translation resources to RHDH.
- Fixes #?
https://issues.redhat.com/browse/RHIDP-9101
> chore(deps): bump adoption insights plugins version

- e2e-tests/playwright/e2e/github-happy-path.spec.ts
- e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
- e2e-tests/playwright/e2e/plugins/topology/topology.spec.ts
Follow up to https://github.com/redhat-developer/rhdh/pull/3501 to skip the tests with `fixme` (recommended approach for tests that are supposed to be skipped until fixed) and add links to Jira.
Code was formatted by linter.
- Fixes #?
> chore(e2e): link Jira to fixme tests skipped in #3501

- catalog-entities/marketplace/plugins/lightspeed.yaml
Correcting the product name - should be Developer Lightspeed For Red Hat Developer Hub
- Fixes #?
> fix(catalog-entities): update lightspeed.yaml
