redhat-developer/rhdh

manifests/base/externalsecret.yaml
This PR adds the external secret to the manifests to allow the ability to retrieve secrets from vault during deployment.
Fixes #?
=> Add external secret to manifest

app-config.yaml, manifests/base/externalsecret.yaml, packages/app/package.json, packages/app/src/App.tsx, packages/app/src/components/Root/Root.tsx, packages/app/src/components/catalog/EntityPage.tsx, packages/app/src/components/catalog/utils.tsx, packages/backend/package.json, packages/backend/src/index.ts, packages/backend/src/plugins/catalog.ts, packages/backend/src/plugins/ocm.ts, yarn.lock
Install the OCM plugin and all of the fronted components. Discovered clusters are converted to catalog entities with kind `resource`.
Fixes #7
The secret `moc_infra_token` is located in vault in `moc/smaug/service-catalog/k8s-plugin-tokens`. The added external secret will create a secret in the `janus-idp` namespace and will get consumed.
=> feat(ocm): Install and configure the ocm plugin

manifests/base/deployment.yaml, manifests/base/ingress.yaml, manifests/base/service.yaml
Adding the label `backstage.io/kubernetes-id: janus-idp` to the backstage deployment, ingress, and service will allow these resources to be discovered by the Kubernetes plugin. Also, the cluster token has already been fixed.
Fixes #?
=> Add backstage label for Kubernetes

manifests/base/kustomization.yaml
It looks like the update to use 
```
labels:
- pairs:
app.kubernetes.io/name: backstage
app.kubernetes.io/instance: backstage
includeSelectors: false
```
is causing a sync issue in ArgoCD. Reverting back to the use of the `commonLabels` in an attempt to fix the sync issue.
Fixes #?
=> Revert to commonLabels

catalog-entities/components.yaml, manifests/base/certificate.yaml, manifests/base/ingress.yaml, manifests/base/kustomization.yaml
This is to update the Ingress with the new domain that was created. Also updates the URL for the showcase app in the `component.yaml` 
Additionally, there was an issue with the Keycloak missing from the kustomize file leading to it not being deployed.
Fixes #?
=> Update the ingress with new domain

app-config.yaml, catalog-entities/components.yaml, packages/app/package.json, packages/app/src/components/catalog/EntityPage.tsx, yarn.lock
Install and configure the quay plugin. Add a new tab to website/service entities, see the screenshot bellow.
Fixes #60
For now I just added the `janus-idp/redhat-backstage-build` since we don't have an image for this showcase on the janus quay repo.
=> feat: Add quay plugin to website/service components

manifests/base/deployment.yaml, manifests/base/keycloak/certificate.yaml, manifests/base/keycloak/ingress.yaml, manifests/base/kustomization.yaml, manifests/overlays/dev/kustomization.yaml, manifests/overlays/prod/kustomization.yaml
This PR is meant to update the manifests for the Backstage Showcase app
First is to add multiple environments that will be used for deployment
* This will allow us to test new changes in a dev environment without affect what is currently deployed in the prod environment
Second is to add a readiness probe to the deployment resource
* This is to fix the issue of bringing down the app whenever there is a failing deployment
* The cluster will first check if the new pod is ready before scaling down the old pod
Third is to fix an issue with the Keycloak cert
* Renamed to avoid conflict 
* Shortened the URL to avoid the issue of it being too long for certification
Fixes #?
=> Manifest changes

app-config.yaml, docs/getting-started.md
Updated the hard coded ArgoCD URL to now be a variable to allow for more customization. 
- Fixes #100
=> Change ArgoCD URL to be a variable

app-config.yaml, docs/getting-started.md, packages/backend/package.json, packages/backend/src/index.ts, packages/backend/src/plugins/argocd.ts, packages/backend/src/plugins/scaffolder.ts, yarn.lock
This PR adds the scaffolder ArgoCD action for creating ArgoCD resources as well as the ArgoCD backend plugin. 
- Fixes #101 
I added another variable for the url ARGOCD_INSTANCE1_URL. The reasoning is because the frontend plugin requires `api/v1` to be added to the URL, while the backend plugin will throw an error if `api/v1` is on the tail end of the URL. This way we can add the ARGOCD_INSTANCE1_URL and then remove / update the ARGOCD_URL variable whenever the changes go live.
=> Argocd backend plugin

packages/backend/src/plugins/auth.ts
enabled default github identity resolver. This change worked for me. But it may need some conditional logic to coexist with other identity resolved. Basically one can assume that given how a user was authenticated, there is an identity resolved that applies better than others. And then perhaps have a default one (the one I commented out).
Not sure how to write that conditional logic. This is better tested only after #120 is merged and it needs that data to do the mapping.
- Fixes #116 
=> enabled default github identity resolver

.github/workflows/techdocs.yaml, app-config.yaml, showcase-docs/getting-started.md
Second half of the Techdocs PR. This PR adds the GitHub actions to build and publish the Techdocs to the OBC that was created in the [previous PR](https://github.com/janus-idp/backstage-showcase/pull/117). Also adds the ability to pull in the the documentation from the OBC by updating the app-config to point to the bucket. 
- Fixes #58 
=> Techdocs CI

packages/backend/src/plugins/auth.ts
Reverts janus-idp/backstage-showcase#121
As it was breaking the GitHub authentication and many plugins are not working anymore.
=> Revert "enabled default github identity resolver"

.github/workflows/docker-build.yaml
- Fixes docker build workflow - Apparently you need git context for every event even though the documentation says [otherwise](https://github.com/docker/build-push-action#git-context).
N/A
=> Fix docker build workflow

manifests/base/kustomization.yaml
Applies the patchesJson6902 to remove some labels in the labelSelector field. Currently, the labels defined within kustomize.yaml are being added to the labelSelector field in the Keycloak service. This is leading to the Keycloak deploymentconfig not being able to pick up the service.
- Fixes #?
Will need this merged before the Keycloak auth PR is merged. The Keycloak auth PR will need information from Keycloak.
=> Apply patch to Keycloak service

app-config.yaml, catalog-entities/all.yaml, catalog-entities/components.yaml, catalog-entities/components/showcase.yaml, catalog-entities/groups.yaml, catalog-entities/groups/janus-authors.yaml, catalog-entities/resources.yaml, catalog-entities/resources/argocd.yaml, catalog-entities/resources/github.yaml, catalog-entities/resources/keycloak.yaml, catalog-entities/resources/obc.yaml, catalog-entities/resources/pgdb.yaml, catalog-entities/systems.yaml, catalog-entities/systems/janus-idp.yaml
Update the Janus Showcase data by adding:
- Individual locations for all kinds 
- A single `all` location to aggregate all other locations
- Remove `catalog-info.yaml` file since it was a duplicate of the component `showcase`
- Add resources for `argocd`, `obc`, `postgres db`, `keycloak` and `github`
- Add all of the resources as the dependencies for the `showcase` component
- Create `janus-idp` system that contains all of the resources, components and groups
- Fixes #143
I wasn't sure what was meant by the resource `gitops repo` so I didn't add that one. If you could elaborate on what you meant by that @christophe-f, I can add also add that one as an additional resource.
=> feat: Update Janus Showcase data

Dockerfile, app-config.production.yaml, manifests/base/deployment.yaml, manifests/base/kustomization.yaml, manifests/base/postgres.yaml, manifests/components/postgres-db/kustomization.yaml, manifests/components/postgres-db/operator-group.yaml, manifests/components/postgres-db/sub.yaml
Add a deployment for a postgres database which includes:
- a postgres `component` for adding the operator
- a `PostgresCluster` which is the actual database instance
- the database will automatically backup to a storage volume every week with a full backup and every 6 days with a differential backup
- Fixes #141
=> feat: Add postgres database to deployment

Dockerfile, app-config.yaml
Adds a URL pointing to the `all.yaml` within our catalog entities directory for the catalog. This will fix the of the data not showing up within the catalog. 
The issue is happening because we currently have to account for whether the Showcase app is running in a container or locally. This requires us to declare the location twice whenever we point to a local directory. The first declaration is if the app is running locally `./catalog-entities/` and the second is whenever it is running in a container `../../catalog-entities/`
- Fixes #178
- Add a screenshot if the change is …
=> Showcase data

manifests/base/deployment.yaml, manifests/base/kustomization.yaml, manifests/base/postgres.yaml, manifests/components/postgres-db/kustomization.yaml, manifests/components/postgres-db/operator-group.yaml, manifests/components/postgres-db/sub.yaml
Adds the manifest files to deploy a postgres database in our OpenShift namespace. This is the first step in adding the postgres database to the backstage showcase.
We had some issues with deployment to the OpenShift cluster when we merged #157. So now we are going to try doing this in steps to see if we can get it to work. 
- Fixes #?
=> Add postgres database manifests files

manifests/base/postgres.yaml
This PR adds limits to the sidecars within a PostgresCluster resource. Operate First's cluster automatically assigns limits to pods and their sidecars that are running. This is an issue as the PostgresCluster resource will spin up two pods each with a number of sidecars that will require limits. As such we run out of our allocated limits before the resource can finish deploying. 
- Fixes #?
=> Add limits to sidecars for postgres

catalog-entities/components/showcase.yaml, packages/app/public/homepage/data.json
We've been notified via email that https://showcase.janus-idp.io/ is using an expired Slack invite link. This PR changes it to the same invite used in https://janus-idp.io (or `README.md` in this repo).
N/A
N/A
N/A
=> fix: update slack invite link

app-config.production.yaml, app-config.yaml, manifests/base/deployment.yaml, manifests/base/ingress.yaml, manifests/base/service.yaml, packages/app/src/App.test.tsx, packages/app/src/App.tsx, packages/backend/src/plugins/auth.ts
Adds Keycloak Authentication to the showcase app. Will also deploy an OAuth2 Proxy sidecar container. Also includes the ability to switch from the `ProxiedSignInPage` to the `SignInPage` whenever the `auth.environment` is set to development. This means that a developer will not need to have Keycloak and Oauth2 Proxy set up to be able to run the app locally.
- Fixes #107 
This will require PR #149 and the logout issue from upstream to be handled before we can merge this PR. The logout issue involves not being able to logout in Backstage whenever you are using an OAuth2 Proxy.
=> Keycloak auth

app-config.yaml, packages/app/package.json, packages/backend/package.json, packages/backend/src/plugins/catalog.ts, showcase-docs/getting-started.md, yarn.lock
Update the `ocm` plugins to the latest versions. This includes some breaking changes:
- The configuration schema for the plugin moved to the catalog providers
- An `owner` field was added which automatically adds an owner to the discovered clusters
- Multiple hub environments can now be specified
- None
None
=> chore: Bump ocm plugins to the latest version

packages/app/package.json, yarn.lock
Signed-off-by: Oleg S <97077423+RobotSail@users.noreply.github.com>
This PR updates the version of `@janus-idp/backstage-plugin-quay` from 
`1.2.0` -> `1.2.1`.
Fixes #219
=> Update Quay Plugin Version

app-config.yaml, packages/app/package.json, packages/app/src/App.tsx, packages/app/src/components/catalog/EntityPage/Content/Overview.tsx, packages/backend/package.json, packages/backend/src/index.ts, packages/backend/src/plugins/jenkins.ts, showcase-docs/getting-started.md, yarn.lock
Signed-off-by: Oleg S <97077423+RobotSail@users.noreply.github.com>
This pull request adds the Jenkins plugin to 
the backstage showcase code. The user can 
configure their Jenkins instance via 
`app-config.yaml` by providing their:
- `JENKINS_URL`
- `JENKINS_USERNAME`
- `JENKINS_API_TOKEN`
The Jenkins plugin adds a history of runs to 
the CI/CD page and an overview of the jenkins 
entity to the overview page.
Fixes #173
=> Add Jenkins plugin to Showcase

.husky/post-checkout, .husky/post-merge, .husky/post-rewrite, .husky/scripts/sync-node-modules, package.json
Add post merge hook to run `yarn install` when any `package.json` is out of date.
N/A
=> Add post merge and post checkout hooks

Dockerfile, app-config.example.production.yaml, app-config.example.yaml, manifests/base/deployment.yaml, showcase-docs/getting-started.md
Chasing https://github.com/janus-idp/book/issues/14 we want to be able to run this image "as is" which should enable users to replicate a default Showcase setup. That means: most custom features are disabled because of missing credentials, but the pod starts and runs fine.
Therefore I'm proposing:
- rename `app-config.basic.yaml` to `app-config.example.yaml`
- add `app-config.example.production.yaml` which enables postgres and routes frontend via backend (similar to `app-config.production.yaml`, but without certificates and using different variable names that are available through the upstream helm chart)
- change `CMD` to `ENTRYPOINT` so it doesn't get overwritten by dynamic `args` in the pod spec of the Helm chart
- change the entrypoint arguments to list all configs that should be …
=> feat: modify app-configs so default entrypoint can be used by helm

Dockerfile
Added `mkdocs` to the showcase image in order to run techdocs in a local setup mode
- Fixes #265 
=> Added mkdocs to Dockerfile to run local techdocs

packages/app/public/homepage/data.json
Updated the Openshift, Keycloak, ArgoCD, SonarQube links.
Removed Vault since we are no longer using it.
Set the Grafana as "Coming Soon", since we might use it in the future.
- Fixes #339
=> chore: update homepage links

app-config.yaml
I've noticed missing default configuration for topology `1.7.0` and `1.8.0` (we're at `^1.7.0` in this instance, but it doesn't hurt to be future-proof)
N/A
=> chore: add missing CRs to kubernetes plugin for topology

packages/app/package.json, yarn.lock
https://github.com/janus-idp/backstage-showcase/issues/394
This PR updates the version of @janus-idp/backstage-plugin-topology from
1.9.0 -> 1.10.0
=> chore(deps): update topology plugin to 1.10.0

.github/workflows/docker-build.yaml
This PR addresses the issue of our GitHub actions failing. Whenever we build a new image, we either fail with the error `System.IO.IOException: No space left on device` or we time out. This PR adds a new step that frees up the disk space, giving us more room back for whenever we build.
This step is removing the packages that are included within the GitHub runner. These include android, dotnet, and haskell. 
More [information](https://github.com/jlumbroso/free-disk-space) on the GitHub action.
An [example](https://github.com/janus-idp/backstage-showcase/actions/runs/5685267404) of the failing GH action
- Fixes #425 
- …
=> Add GH action for freeing up disk space

.husky/pre-commit, .prettierrc, package.json, yarn.lock
- Adds `lint-staged` dependency
- Removes `.prettierrc` as it is not used
- Fixes https://github.com/janus-idp/backstage-showcase/issues/465
=> fix(lint-staged): add lint-staged

.changeset/image-labels-support.md, .github/actions/docker-build/action.yaml, .github/workflows/nightly.yaml
1. add `imageLabels: quay.expires-after=14d` to  `.github/workflows/nightly.yaml`.
this label sets the image expiration period in Quay.io
2. use the new ket in `.github/actions/docker-build/action.yaml`, under the `meta` step
3. add `labels: ${{ steps.meta.outputs.labels }}` under `Build and push Docker image` step, this where the actual label is being consumed and set to the newly created image
4. set `imageLabels` under `.github/actions/docker-build/action.yaml` inputs, as non required input
- Fixes #474 
- expect to see expires label in newly pushed nightly images
=> added support for labels, for supporting image expiration

.changeset/dull-rabbits-do.md, app-config.yaml, packages/backend/package.json, packages/backend/src/index.ts, packages/backend/src/metrics.ts, showcase-docs/getting-started.md, yarn.lock
- Adds option (`METRICS_ENABLED=true`) to enable Prometheus metrics optionally.
- When enabled, Prometheus metrics are available at the backed URL in `/metrics ` (`http://localhost:7007/metrics`)
- Fixes https://github.com/janus-idp/backstage-showcase/issues/230
=> feat(backend): add Prometheus metrics

.changeset/shy-cobras-tease.md, packages/app/config.d.ts, packages/app/package.json, packages/app/src/App.tsx, packages/app/src/components/Root/Root.tsx, packages/app/src/components/Root/SidebarLogo.test.tsx, packages/app/src/components/Root/SidebarLogo.tsx, packages/app/src/hooks/useUpdateTheme.test.ts, packages/app/src/hooks/useUpdateTheme.ts, packages/app/src/themes/darkTheme.ts, packages/app/src/themes/lightTheme.ts, yarn.lock
Provides the ability to customize the branding for Janus. User can update Icons and primary color with configurations in app-config.yaml for multiple themes.
```
app:
branding:
fullLogo: ${BASE64_SVG_FULL_LOGO_URI}
iconLogo: ${BASE64_SVG_ICON_LOGO_URI}
theme:
- light:
primaryColor: ${PRIMARY_LIGHT_COLOR}
- dark:
primaryColor: ${PRIMARY_DARK_COLOR}
```
**Screenshots:**
Light Theme
Dark Theme:
- Fixes https://github.com/janus-idp/backstage-showcase/issues/540
=> feat(app): make branding icons and primary color configurable

.changeset/thirty-bags-kiss.md, packages/backend/src/index.ts, packages/backend/src/loader/CommonJSModuleLoader.ts
Fix a bug in the upstream `CommonJSLoader`, which prevented laoding modules from embedded `node_modules` folders of private packages located in the plugin `node_modules` folder.
This is a fixed version of the [corresponding upstream code](https://github.com/backstage/backstage/blob/master/packages/backend-plugin-manager/src/loader/CommonJSModuleLoader.ts).
A PR on the upstream repository will follow, but until the change lands upstream and can be imported into the showcase after the next release, we will use the fixed loader added in the showcase application itself.
No issue
=> fix : fix a bug in the upstream CommonJSModuleLoader

.changeset/thin-frogs-jog.md, .gitignore, app-config.yaml, docker/Dockerfile, docker/brew.Dockerfile, docker/install-dynamic-plugins.py, dynamic-plugins.default.yaml, dynamic-plugins/.eslintignore, dynamic-plugins/.eslintrc, dynamic-plugins/package.json, package.json, packages/backend/src/index.ts, tsconfig.json, turbo.json
This PR fixes the dynamic plugins build by adding the packages of the various dynamic plugins wrappers to the monorepo, which allows leveraging the whole yarn + turbo machinery, also for dynamic plugins. 
It adds the switch of a first, very simple plugin (roadie utils) to dynamic, in order to test and validate the whole machanism.
This PR is based on PR #600 which should be merged before.
No dedictaed issue. Part of a wider task.
=> chore: Prepare for the switch of backend plugins to dynamic plugins

.changeset/breezy-trainers-do.md, packages/app/src/components/DynamicRoot/DynamicRoot.tsx, packages/app/src/components/DynamicRoot/Loader.tsx, packages/app/src/utils/dynamicUI/initializeRemotePlugins.ts
Add extra error handling while initializing dynamic front-end plugins. If a plugin fails to initialize, it won't be registered and won't be rendered at the expected place.
=> fix(dynamic-plugins): handle plugin initialization failures

.changeset/nervous-mangos-protect.md, packages/backend/src/index.ts, packages/backend/src/plugins/permission.ts
Add a dynamic-plugin-aware `PluginIDProvider` to allow the RBAC plugin to grab the pluginIDs of backend dynamic plugins.
- Fixes #623
=> Add a dynamic-plugin-aware `PluginIDProvider`

.changeset/old-fans-work.md, packages/backend/package.json, packages/backend/src/plugins/app.ts, yarn.lock
Backend merged config is injected by the `app-backend` upstream plugin inside one of the Javascript
static assets before service static assets.
So we should never allow this specific JS file to be cached on the client side,
so that any change in the configuration can be seen on the frontend
side after a backend restart.
That's particularly critical to get the latest UI configuration
of added dynamic frontend plugins.
- Fixes No issue number.
=> fix: disable cache for injected file.

docker/Dockerfile, docker/brew.Dockerfile
Don't run package scripts (`prepack`, `postpack` foe example) when using `npm pack` at runtime to install the dynamic plugins.
In fact that's also quite expected that no arbitrary script would be run while installing downloaded dynamic plugins.
=> chore: don't run scripts on dynamic plugin install

package.json
chore: bump root package.json to 1.0.0 before we branch for 1.0.x / 1.1.0
N/A
N/A
=> chore: bump root package.json to 1.0.0 before we branch for 1.0.x / 1.1.0

docker/Dockerfile, docker/brew.Dockerfile
chore: fix final brew runtime stage so that content lives in /opt/app-root/src instead of /remote-sources
N/A
https://issues.redhat.com/browse/RHIDP-429
N/A
=> chore: fix final brew runtime stage so that content lives in /opt/app-root/src instead of /remote-sources

.github/workflows/add-to-project.yaml
Adds a job that labels every new issue with `post-FF` label to GitHub action that this triggers for every new issue.
This is to make it easier to track issues discovered after FF
It will be removed after the release.
- Fixes #?
=> automatically label new issues with post-FF label

packages/backend/package.json
Reverts the `yarn start` script to no longer load the `app-config.example.yaml` file for local development
N/A
=> chore: revert `yarn start` script

.changeset/real-boxes-clap.md, packages/app/src/components/catalog/EntityPage/index.tsx, showcase-docs/dynamic-plugins.md
The dedicated tekon tab is no longer needed as it will only be shown on the CI tab
- Fixes https://github.com/janus-idp/backstage-showcase/issues/718
=> fix: removes tekton tab

.changeset/perfect-balloons-repeat.md, .github/workflows/ci.yaml
Stop ignoring docs changes from triggering "Main Job"
the "Main Job" is configured as required check-in GitHub. When it is not triggered the docs-only PRs can't be merged without admin override.
- Fixes #?
=> chore(ci): trigger the Main Job for all changes

.changeset/rotten-seas-fetch.md, app-config.dynamic-plugins.yaml, dynamic-plugins.default.yaml, dynamic-plugins/imports/package.json, dynamic-plugins/wrappers/backstage-plugin-lighthouse/package.json, dynamic-plugins/wrappers/backstage-plugin-lighthouse/src/index.ts, packages/app/config.d.ts, packages/app/src/components/DynamicRoot/DynamicRoot.tsx, packages/app/src/components/Root/Root.tsx, packages/app/src/utils/dynamicUI/extractDynamicConfig.ts, showcase-docs/dynamic-plugins.md
Instead of embedding all MUI4 icons into the bundle, we can depend in `app.getSystemIcon()` icon catalog. This PR allows users to extend it via dynamic plugins and therefore cleanup our bundle of unnecessary icons.
~Depends on: https://github.com/janus-idp/backstage-plugins/pull/919~
Resolves: https://github.com/janus-idp/backstage-showcase/issues/725
=> feat(dynamic-plugins): replace static MUI Icons library import with dynamic appIcons

.changeset/slimy-numbers-grab.md, packages/backend/package.json, yarn.lock
Update rbac-backend plugin to version 1.6.2 to make plugin working with ssl.
- Fixes janus-idp/backstage-plugins#913
- ## PR acceptance criteria
=> fix(rbac): update rbac-backend plugin to version 1.6.3

docker/install-dynamic-plugins.py
Increase max entry size for dynamic plugins in order to avoid triggering a zip-bomb error during installation for plugins delivered as part of the showcase docker image.
The previous value (10000000) was not enough for 2 of the plugins delivered as part of the showcase docker image (tekton plugin and the topology plugin)
=> fix: increase max entry size for dynamic plugins

docker/Dockerfile, docker/brew.Dockerfile, docker/install-dynamic-plugins.sh
This PR adds an `installDynamicPlugins.sh` shell script that runs the `install-dynamic-plugins.py` python script.
This will avoid surfacing the use of `python` in the helm chart (when defining the `initContainer` command.
The goal here is to make it easy and transparent (no required change in the Helm Chart), if we want to implement dynamic plugin installation in another language - as a node CLI for example) 
- Fixes #?
=> chore: shell script to install dynamic plugins

.changeset/fresh-parrots-develop.md, packages/backend/src/index.ts
Updates the import of HostDiscovery from @backstage/backend-common to @backstage/backend-app-api. 
There seems to have been a recent update to `@backstage/backend-app-api` and `@backstage/backend-common` that mentions [HostDiscovery](https://github.com/backstage/backstage/blob/master/packages/backend-common/CHANGELOG.md#patch-changes-3) is now deprecated in backend-common and to now import it from backend-app-api
- Fixes #771
=> Change import of HostDiscovery

docker/Dockerfile, docker/brew.Dockerfile, dynamic-plugins/imports/import-plugins.js, dynamic-plugins/imports/package.json
Some `yarn.lock` files (the one in the imported backend dynamic plugins) were missed by the cachito replacement that occurs during the downstream docker build.
This PR fixes it.
=> fix: `yarn.lock` files missed by cachito replacement

.changeset/shy-berries-confess.md, dynamic-plugins/imports/package.json
Update Keycloak to consume https://github.com/janus-idp/backstage-plugins/pull/968 fix  for https://github.com/janus-idp/backstage-plugins/issues/949
~Waits for `1.7.6` to be published~
N/A
=> fix: update keycloak plugin to fix not a constructor error

.changeset/new-adults-sort.md, app-config.dynamic-plugins.yaml, dynamic-plugins.default.yaml, dynamic-plugins/imports/package.json
SSIA, makes segment frontend plugin dynamic
Requires https://github.com/janus-idp/backstage-plugins/pull/955, waiting for requirements to be met
=> fix(dynamic-plugins): use segment as a dynamic plugin

docker/brew.Dockerfile
This fixes the missing `/opt/app-root/src/.npm` directory in Brew build image that was causing problems on Kubernetes clusters.
More info is at https://issues.redhat.com/browse/RHIDP-728
- Fixes #?
=> fix: missing .npm directory in Brew build

.changeset/swift-avocados-jog.md, plugins/scalprum-backend/src/service/router.ts
This commit adds a log statement to the scalprum-backend plugin to log each successfully loaded frontend dynamic plugin, using a similar format to what's current used to log backend dynamic plugins.  Here's what it would look like on the console:
- Fixes #893
=> chore(scalprum-backend): Frontend plugins log line

.changeset/smooth-pumas-argue.md, dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd/package.json
There seems to be an upstream regression https://github.com/RoadieHQ/roadie-backstage-plugins/issues/1238 that renders the `EntityArgoCDHistoryCard` unusable when ArgoCD plugin is used as both the frontend and backend plugin. I hope a version downgrade in a wrapped dynamic plugin is possible since this package is included in the image statically anyways and it is not published.
This is a temporary workaround, not a fix.
- Fixes #?
=> fix: downgrade ArgoCD frontend plugin, upstream regression

dynamic-plugins.default.yaml
We must change 3Scale plugin environment variables because it does not comply with Openshift and POSIX standards for environment variables (Must not start with a digit).
Just added an underscore ("_") to the variables name.
- Fixes #?
JIRA: https://issues.redhat.com/browse/RHIDP-1030
Fixes https://github.com/janus-idp/backstage-showcase/issues/849
=> fix(3scale): modify 3scale environment variables

.changeset/young-numbers-whisper.md, dynamic-plugins.default.yaml, dynamic-plugins/imports/package.json, packages/app/src/components/AppBase/AppBase.tsx, packages/app/src/components/Root/Root.tsx, packages/app/src/components/admin/AdminPage.test.tsx, packages/app/src/components/admin/AdminPage.tsx
This change adds a Administration navigation tab and page intended for plugins that are for administration of an Janus/RHDH instance.  This commit adds two routes /admin/rbac and /admin/plugins and related mountpoints so that dynamic plugins can contribute UI components to this page.  The page can also deal with a few edge cases and will also not be visible should no plugins be configured to show up on it.  A test is provided that covers these cases.  This change also adds the dynamic-plugins-info dynamic plugin which is one of two components intended to appear on this page.
Part of [RHIDP-980](https://issues.redhat.com/browse/RHIDP-980).  This is an approach to provide a home for dynamic plugins that fall under the "Administration" tab, for example:
Please make sure that the following …
=> feat(app) an AdminPage for admin plugins

.changeset/twenty-falcons-work.md, packages/app/src/components/DynamicRoot/DynamicRoot.tsx
This change updates the options being passed to Scalprum to remove a deprecation warning that was being printed to the browser console.
- Fixes #956
=> chore(app): remove deprecation warning

showcase-docs/monitoring-and-logging.md
This extends the existing documentation [Setting up Metrics Monitoring and Logging for Backstage Showcase](https://github.com/janus-idp/backstage-showcase/blob/main/showcase-docs/monitoring-and-logging.md?rgh-link-date=2024-01-31T12%3A01%3A44Z) with the information on how to configure this when RHDH is deployed using the operator.
- Fixes https://issues.redhat.com/browse/RHIDP-1142
- Fixes https://github.com/janus-idp/operator/issues/180
- Follow the operator instructions to install the operator and install RHDH on OpenShift: https://github.com/janus-idp/operator/blob/main/.rhdh/docs/installing-ci-builds.adoc
- Follow the documentation in this PR to try it out
=> docs: Document how to set up monitoring and logging on OpenShift when using the operator

.changeset/sweet-colts-exercise.md, packages/app/src/components/Root/Root.tsx, packages/app/src/themes/componentOverrides.ts, packages/app/src/themes/darkTheme.ts, packages/app/src/themes/lightTheme.ts
- Fixes  https://issues.redhat.com/browse/RHIDP-1165 ,  https://issues.redhat.com/browse/RHIDP-1164
Selected Tab (dark theme)
Tab when hovered (dark theme)
Selected Tab (light theme)
Tab when hovered (light theme)
Nav when hovered (light theme)
Nav when hovered (dark theme)
=> Add MUI theme config to fix Sidebar and Tabs color

.changeset/good-kings-allow.md, packages/app/src/themes/componentOverrides.ts
Part of: https://github.com/janus-idp/backstage-showcase/pull/960
Fixed 
Fixed the disabled tab color
=> Fix MUI Tab console warnings

.ibm/pipelines/openshift-tests.sh, .ibm/pipelines/value_files/values_showcase.yaml, e2e-tests/playwright.config.ts, e2e-tests/playwright/e2e/plugins/quay/quay.spec.ts, e2e-tests/playwright/support/pageObjects/global-obj.ts, e2e-tests/playwright/utils/UIhelper.ts, e2e-tests/playwright/utils/quay/quay.ts
=> RHIDP-1074 [Playwright tests] enable quay.spec.ts test

.ibm/pipelines/openshift-tests.sh, e2e-tests/playwright/e2e/plugins/quay/quay.spec.ts, e2e-tests/playwright/utils/Common.ts, e2e-tests/playwright/utils/UIhelper.ts
[e2e-test] Enhance loginAsGithubUser() to Handle Intermittent Pop-up Visibility Issues
https://issues.redhat.com/browse/RHIDP-1396
=> [e2e-test] Enhance loginAsGithubUser() to Handle Intermittent Pop-up Visibility Issues & Fix Quay test

.ibm/pipelines/openshift-tests.sh, .ibm/pipelines/resources/config_map/configmap-app-config-rhdh.yaml, .ibm/pipelines/resources/config_map/configmap-rbac-policy-rhdh.yaml, .ibm/pipelines/value_files/values_showcase.yaml, e2e-tests/playwright/e2e/github-happy-path.spec.ts, e2e-tests/playwright/e2e/guest-signin-happy-path.spec.ts, e2e-tests/playwright/e2e/plugins/acr.spec.ts, e2e-tests/playwright/e2e/plugins/ocm.spec.ts, e2e-tests/playwright/e2e/plugins/quay/quay.spec.ts, e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts, e2e-tests/playwright/e2e/techdocs.spec.ts, e2e-tests/playwright/support/pageObjects/global-obj.ts, e2e-tests/playwright/support/pageObjects/page-obj.ts, e2e-tests/playwright/support/pages/rbac.ts, e2e-tests/playwright/utils/UIhelper.ts
- Added playwright e2e tests
- Updated RBAC frontend and backend packages
- Updated existing tests in `guest-signin-happy-path` . Once the RBAC is enabled, catalog components will not be accessible to guest users.
- disabled the ocm e2e tests
- Fixes https://issues.redhat.com/browse/RHIDP-1340
**app-config.local.yaml**
catalog configuration:
```
- type: url
target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/acme-corp.yaml
rules:
- allow: [User, Group]
```
permission configuration:
```
permission:
enabled: true
rbac:
policies-csv-file: /<path-to-your-csv-file>/rbac-policy.csv
policyFileReload: true
admin:
users:
- name: user:default/rhdh-qe
```
dynamic plugins configuration:
``` …
```
=> [rbac]: added playwright e2e tests

e2e-tests/playwright/e2e/plugins/ocm.spec.ts
The OCM (Open Cluster Management) test configurations in the e2e (end-to-end) tests have been updated with new specifications for the testCluster; CPU cores have been increased from 12 to 16, and memory size from 47Gi to 63Gi. Additionally, a previously skipped test "Navigate to Clusters and Verify OCM Clusters" has been enabled for execution.
- Fixes #?
=> Update testCluster specifications and enable OCM test

.ibm/pipelines/value_files/values_showcase.yaml, dynamic-plugins.default.yaml
This change enables the dynamic-plugins-info UI by default when installing the app via helm  or operator.
- Fixes #?
=> chore(admin): enable dynamic-plugins-info

e2e-tests/playwright/e2e/google-signin-happy-path.spec.ts
The 'beforeAll' hook in the 'google-signin-happy-path' end-to-end test has been updated to skip the test. This change was necessary to prevent the test from running in certain scenarios where it wasn't needed. The test can be enabled or disabled as required in future.
- Fixes #?
=> Skip Google sign-in e2e test in beforeAll hook

e2e-tests/playwright/e2e/google-signin-happy-path.spec.ts
The commit removes the skip on 'beforeAll' hook in the 'google-signin-happy-path' end-to-end test. Now, the entire test, including this hook, will be run in our suite. This was done to align with updates in our testing strategy or requirements.
- Fixes #?
=> Disable Google signin happy path test

e2e-tests/playwright/e2e/plugins/quay/quay.spec.ts, e2e-tests/playwright/utils/quay/quay.ts
Extend quay plugin e2e suite to include the changes contributed by RHTAP
https://issues.redhat.com/browse/RHIDP-1112
=> [e2e-tests] Add security scan check to quay plugin suite

packages/backend/src/index.ts, packages/backend/src/loader/CommonJSModuleLoader.ts, packages/backend/src/loader/index.ts
A big number of upstream backstage backend plugins usie the `resolvePackagePath` function provided by the `backstage-common` package.
This function doesn't work with the plugins are converted to dynamic and loaded dynamically.
This PR customizes the default`CommonJSLoader` used by the upstream `DynamicPluginManager` when loading dynamic plugins, so that calls to the `resolvePackagePath()` function in order to retrieve the plugin package folder can now succeed.
No issue for now.
=> Support `resolvePackagePath` for dynamic backend plugins.

.dockerignore, .rhdh/docker/Dockerfile, docker/Dockerfile, packages/backend/package.json, packages/backend/src/modules/authProvidersModule.ts, plugins/auth-backend-module-oidc-provider/.eslintrc.js, plugins/auth-backend-module-oidc-provider/README.md, plugins/auth-backend-module-oidc-provider/config.d.ts, plugins/auth-backend-module-oidc-provider/dev/index.ts, plugins/auth-backend-module-oidc-provider/package.json, plugins/auth-backend-module-oidc-provider/src/authenticator.test.ts, plugins/auth-backend-module-oidc-provider/src/authenticator.ts, plugins/auth-backend-module-oidc-provider/src/index.ts, plugins/auth-backend-module-oidc-provider/src/module.test.ts, plugins/auth-backend-module-oidc-provider/src/module.ts, plugins/auth-backend-module-oidc-provider/src/resolvers.ts, showcase-docs/auth.md, showcase-docs/getting-started.md, yarn.lock
Forked the Auth backend OIDC provider module from Upstream into the Showcase. The purpose of this is to address the sign-out issue currently faced by users who are using OAuth2 Proxy and Keycloak. This fork will enable them to switch to the OIDC provider and Keycloak, providing the ability to log out properly.
This PR also introduces some documentation on configuring auth providers within showcase. I settled for the inclusion of a few simple providers with very little detail at this time, with the exception of the OIDC provider. With this provider, I opted to an additional example since we will be trying to recommend this over OAuth2 Proxy.
If we wish to expand upon this further, I believe we should open up a separate issue that tackles the auth providers as a whole. Just wanted to at …
=> feat(OIDC): adds a forked version of the OIDC auth plugin

.github/renovate.json, dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd/package.json, yarn.lock
downgrade roadiehq/backstage-plugin-argo-cd back to 2.4.1 to avoid regression.
For more info, see the original PR https://github.com/janus-idp/backstage-showcase/pull/947
=> fix: downgrade ArgoCD frontend plugin

dynamic-plugins/imports/package.json
Bump the tekton plugin to include the ACS report crashing UI.
-  https://github.com/janus-idp/backstage-plugins/issues/1355
- https://github.com/janus-idp/backstage-plugins/releases/tag/%40janus-idp%2Fbackstage-plugin-tekton%403.5.12
cc: @nickboldt
=> chore(deps): bump tekton plugin to 3.5.12

package.json, yarn.lock
Declare the dependency `@smithy/is-array-buffer@2.1.1` in the package.json. We are still having some build issues that might be linked to this dependency no longer being explicitly available in the yarn lock file. It was originally removed whenever the OIDC auth plugin module was added in favor of `@smithy/is-array-buffer@^2.2.0`. For some reason, it is not being properly picked up during our build process so this PR aims to declare it explicitly.
- Fixes #?
=> fix(deps): declare @smithy/is-array-buffer in package.json

dynamic-plugins/imports/package.json
Bump the topology plugin to include the fix for routes sown for workloads with same name, across namespaces
- Fixes #?
- https://issues.redhat.com/browse/RHTAPBUGS-1166
- https://issues.redhat.com/browse/RHIDP-1693
- https://github.com/janus-idp/backstage-plugins/pull/1389
- https://github.com/janus-idp/backstage-plugins/releases/tag/%40janus-idp%2Fbackstage-plugin-topology%401.18.8
=> chore(deps): bump topology plugin to 1.18.8

.github/renovate.json
* Added a package rule for devDependencies.  Let's wait and see before adding automerge
* Included the  `@internal` package so static backend plugins are scanned
* Added configs for vulnerabilityAlerts and osvVulnerabilityAlerts - similar to what was done for the operator: https://github.com/janus-idp/operator/pull/282.  Will switch off dependabot PR creation once this is merged
- Fixes https://issues.redhat.com/browse/RHIDP-1737
=> chore(renovate): update renovate config

e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts, e2e-tests/playwright/utils/Common.ts
Added a text verification for rbac RoleList page after updated a role. This is for [RHIDP-1362](https://issues.redhat.com//browse/RHIDP-1362).
**Also fixed a bug of e2e tests `checkAndReauthorizeGithubApp` function.**
- Fixes [RHIDP-1362](https://issues.redhat.com/browse/RHIDP-1362)
- Related to [PR](https://github.com/janus-idp/backstage-plugins/pull/1354) in backstage-plugins repo.
=> chore(rbac): update e2e test for bug fix

packages/app/src/themes/componentOverrides.ts, packages/app/src/themes/defaultThemePalette.ts
Match table styles with PF5.
- Fixes [RHIDP-1707](https://issues.redhat.com/browse/RHIDP-1707): Add MUI theme config so that Tables look similar to PF5
https://github.com/janus-idp/backstage-showcase/assets/26255262/5bfd8597-2bcb-44c1-9691-d9c23dcd425a
=> fix(ui): match table styles with PF5

docs/configuration-env-variables.md, packages/backend/src/modules/authProvidersModule.ts
Ability to define the HTTP header containing the username for the OAuth 2 Proxy Provider
Implements a fallback strategy
1. Environment variable defined by the value of `OAUTH_USER_HEADER`
2. `x-forwarded-preferred-username` HTTP Header (Primary use case: with Keycloak/RHSSO/RHBK)
3. `x-forwarded-user` (Primary use case: OpenShift)
- Fixes #?
Make use of a variety of OAuth Providers:
1. Configure OpenShift OAuth based on instructions [here](https://janus-idp.io/blog/2023/02/20/using-openshift-authentication-to-secure-access-to-backstage)
2. Configure Keycloak based on instructions [here](https://janus-idp.io/blog/2023/01/17/enabling-keycloak-authentication-in-backstage)
3. Specify the `OAUTH_USER_HEADER` with a desired header to …
=> Updated how OAuth headers are processed

.github/workflows/ci.yaml, .github/workflows/techdocs.yaml
chore(deps): fail the build if workspace dirty after a yarn install (yarn.lock changed) (RHIDP-1203, [RHIDP-1204](https://issues.redhat.com//browse/RHIDP-1204))
N/A
N/A
=> chore(deps): fail the build if workspace dirty after a yarn install (yarn.lock changed) (RHIDP-1203, RHIDP-1204)

packages/app/src/themes/componentOverrides.ts
Template cards height is too big in 1.1.x and bottom section is hidden in main branch.
- Fixes [RHIDP-1927](https://issues.redhat.com/browse/RHIDP-1927): Default card height for templates is more by default and bottom section is hidden
=> fix(template): fixed template cards display issues

packages/app/src/themes/componentOverrides.ts, packages/app/src/themes/darkTheme.ts, packages/app/src/themes/defaultThemePalette.ts, packages/app/src/themes/lightTheme.ts
This PR is for matching current style with PF5 style.
Main changes:
1. Overrode font-family to use Red Hat Text font
2. Updated main container background color to white
3. Updated header background color to white
4. Updated template cards style
5. Removed tabs background color
6. Updated tabs button style to display only one bottom border on tab selected
7. Added tabs padding
8. Replaced homepage search bar shadow with a border
9. Updated font weight and text transform for left side bar, page title and filter label text
10. Added border radius to catalog owner filter section
- Fixes [RHIDP-1984](https://issues.redhat.com/browse/RHIDP-1984): Add MUI theme config so that background color and font look similar to PF5
Screen recording …
=> fix(ui): match styles with PF5

packages/app/public/learning-paths/data.json
This PR adds ansible learning paths to data.json.
Once merged these will be visible in learning paths section
and used to show these in ansible plugin.
- Fixes #?
=> Add ansible learning paths

app-config.yaml, packages/app/config.d.ts, packages/app/src/components/Root/SidebarLogo.test.tsx, packages/app/src/components/Root/SidebarLogo.tsx, showcase-docs/customization.md
under app-config now you can set `fullLogoSize` to change width of the logo
- Fixes #1203 
Set the below in your config to change width of the logo
```
app:
branding:
fullLogoSize: ${FULL_LOGO_SIZE}
```
=> branding: add ability to customize sidebar logo

packages/app/src/themes/componentOverrides.ts
Fixes below display issues. Screenshots could be found on first comment of [RHIDP-2074](https://issues.redhat.com/browse/RHIDP-2074).
1. Disabled elements background color on Step component
2. Disabled action column header background color
3. Background color on View Graph page
4. Left padding on OCM table
- Fixes R[HIDP-2074](https://issues.redhat.com/browse/RHIDP-2074)
Enable OCM and RBAC plugin
Screenshots:
=> fix(ui): display issues

packages/app/src/themes/componentOverrides.ts
Indicator of vertical tabs needs to be fixed.
- Fixes [RHIDP-1403](https://issues.redhat.com/browse/RHIDP-1403): [Theme] Visual indicator missing from vertical tabs
Screen recording:
https://github.com/janus-idp/backstage-showcase/assets/26255262/219b3e88-b9d4-4b6e-93a5-ea063aa1ac89
=> fix(ui): tabs indicator display

OWNERS
This issue is to add QEs as approvers for the OpenShift-CI-related changes in the source(https://github.com/janus-idp/backstage-showcase/blob/main/OWNERS). This file will be synched by https://github.com/openshift/release/blob/master/ci-operator/config/janus-idp/backstage-showcase/OWNERS
- Fixes [RHIDP-2201](https://issues.redhat.com/browse/RHIDP-2201)
=> add additional approvers for OpenShift-CI-related changes

e2e-tests/package.json, package.json, packages/app/src/build-metadata.json
Signed-off-by: RHDH Build (rhdh-bot) <rhdh-bot@redhat.com>
=> feat: tagRelease.sh bump versions in 1.1.x for 1.1 release

packages/backend/src/logger/customLogger.ts
Remove ansi colors from logs. After https://github.com/janus-idp/backstage-showcase/pull/1211 changed the log format to JSON, the ANSI escape sequences get outputted as plain text making the logs more difficult to parse through.
Ex:
```console
{"level":"\u001b[32minfo\u001b[39m","message":"::ffff:10.129.2.2 - - [03/May/2024:16:01:59 +0000] \"GET /healthcheck HTTP/1.1\" 200 15 \"-\" \"kube-probe/1.29\"","service":"rootHttpRouter","timestamp":"2024-05-03 16:01:59","type":"incomingRequest"}
```
- Fixes [RHIDP-1632](https://issues.redhat.com/browse/RHIDP-1632)
=> chore: remove ansi colors from logs

packages/app/src/components/DynamicRoot/DynamicRoot.test.tsx, packages/app/src/components/DynamicRoot/DynamicRoot.tsx, packages/app/src/components/DynamicRoot/ScalprumRoot.tsx, packages/app/src/components/admin/AdminTabs.test.tsx, packages/app/src/utils/dynamicUI/extractDynamicConfig.test.ts, packages/app/src/utils/dynamicUI/extractDynamicConfig.ts
This change overhauls the way in which the dynamic frontend configuration is obtained and evaluated, by first passing the loaded configuration through a ConfigReader vs directly evaluating the array of application configurations that the backend API returns.
- Fixes [RHIDP-2297](https://issues.redhat.com/browse/RHIDP-2297)
=> fix(ui): RHIDP-2297 avoid duplicate config

packages/app/package.json, packages/app/src/components/AppBase/AppBase.tsx, packages/app/src/components/DynamicRoot/DynamicRoot.tsx, packages/app/src/components/DynamicRoot/DynamicRootContext.tsx, packages/app/src/utils/dynamicUI/extractDynamicConfig.test.ts, packages/app/src/utils/dynamicUI/extractDynamicConfig.ts, packages/app/src/utils/test/TestRoot.tsx, showcase-docs/dynamic-plugins.md, yarn.lock
This commit enables support for Scaffolder field extensions.  A plugin
can export a field extension as documented and then configure it to be
included in the list of enabled scaffolder field extensions using the
following configuration:
```yaml
frontend:
my-plugin:
scaffolderFieldExtensions:
- importName: SomeExportedFieldExtension
```
- Fixes [RHIDP-1803](https://issues.redhat.com/browse/RHIDP-1803)
- Fixes #1146 
There's a really simple extension in [this package](https://github.com/gashcrumb/simple-test-components) that can be used for a quick test.  You can import [this template](https://gist.github.com/gashcrumb/4d5705887f3b3c248b0720cb08dd2cb3) and then use this configuration:
```yaml
frontend: …
```
=> feat(app) RHIDP-1803 enable field extensions

e2e-tests/playwright/e2e/catalog-timestamp.spec.ts, e2e-tests/playwright/support/pageObjects/global-obj.ts, packages/app/src/components/AppBase/AppBase.tsx, packages/backend/package.json, packages/backend/src/index.ts, yarn.lock
- The PR adds the scaffolder annotator action in the backend
- In the UI, the catalog page will now show a new `Created At` column for entity kind `Component`
- The new column can be sorted
- Has E2E test
- Fixes 
https://issues.redhat.com/browse/RHIDP-2104
https://issues.redhat.com/browse/RHIDP-2193
**Test setup:**
- Changes in `app-config.yaml`
```
catalog:
location:
- type: url
target: https://github.com/debsmita1/nodejs-ex-1/blob/master/local-template.yaml
rules:
- allow: [Template]
```
- Use the `Create React App Template with timestamping` template to register the entity
=> feat(catalog): added created at column in the catalog page

.rhdh/docker/Dockerfile, docker/Dockerfile, docs/proxy.md, packages/backend/package.json, packages/backend/src/corporate-proxy.ts, packages/backend/src/index.ts, showcase-docs/corporate-proxy.md, yarn.lock
This PR allows running the Showcase app behind a corporate proxy, which was the root cause of a login failure using the GitHub auth behind a proxy.
It does so per the upstream instructions provided on this page: https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/help-im-behind-a-corporate-proxy.md
This way, it can honor the conventional `HTTP_PROXY`, `HTTPS_PROXY`, and `NO_PROXY` environment variables (and their lowercase equivalents).
The `undici` and `global-agent` packages added here allow covering settings for the native `fetch` and `node-fetch` respectively. Note that even if `node-fetch` is recommended for HTTP data fetching by Backstage packages [[ADR013](https://backstage.io/docs/architecture-decisions/adrs-adr013/)], we identified a couple of plugins making …
=> feat(backend): Support running behind a corporate proxy [RHIDP-2217]

.rhdh/docker/Dockerfile, docker/Dockerfile
Adds the `NODE_OPTIONS=--no-node-snapshot` env variable so that the scaffolder is usable in nodejs 20.
- Fixes [RHIDP-2436](https://issues.redhat.com/browse/RHIDP-2436)
=> chore(docker): set the `NODE_OPTIONS=--no-node-snapshot` env variable

packages/app/src/components/DynamicRoot/DynamicRootContext.tsx, packages/app/src/components/catalog/EntityPage/DynamicEntityTab.tsx, packages/app/src/utils/dynamicUI/extractDynamicConfig.ts, packages/app/src/utils/dynamicUI/getMountPointData.ts
This change adds exception handling to the two points where plugin supplied condition functions are evaluated, once when rendering the catalog entity tabs, and a second time when a plugin's mountpoint configuration is being checked.  This change also makes the ApiHolder context object available as a 2nd argument; available at the second evaluation point.
- Fixes [RHIDP-2266](https://issues.redhat.com/browse/RHIDP-2266)
An easy way to test this is to throw an exception from [here](https://github.com/gashcrumb/simple-test-components/blob/main/src/plugin.ts#L35) and use [this](https://github.com/gashcrumb/simple-test-components/tree/main#copy-build-results-to-host-application) plugin.  The configuration for this would look like:
```yaml …
```
=> fix(app): RHIDP-2266 add condition error handling

packages/app/src/components/DynamicRoot/DynamicRoot.tsx, packages/app/src/components/DynamicRoot/DynamicRootContext.tsx, packages/app/src/components/DynamicRoot/ScalprumRoot.tsx, packages/app/src/utils/dynamicUI/getMountPointData.ts
This change exposes the dynamic UI configuration to dynamic plugins via
the scalprum API holder available with the scalprum React API.  This
change also moves around some blocks for consistency and improves the
typing for the DynamicRootContext objects.
- Fixes [RHIDP-2338](https://issues.redhat.com/browse/RHIDP-2338)
This can be validated using [this plugin](https://github.com/gashcrumb/simple-test-components) which contains a component that will use the configuration exposed via scalprum to create a new mount point, and then render a component on that mount point.  Use this configuration:
```yaml
backstage-plugin-simple-test-components:
dynamicRoutes:
- path: /test-route
importName: …
```
=> feat(app) RHIDP-2338 expose dynamic UI config

packages/app/src/components/catalog/EntityPage/ContextMenuAwareEntityLayout.tsx, packages/app/src/components/catalog/EntityPage/EntityPage.tsx
This PR adds support for dynamic frontend plugins that contribute extra items in the Catalog entity package content menu.
Without this support, plugins like the upstream `badges` or `playlist` plugins cannot be used as dynamic plugins.
- Fixes [RHIDP-2530](https://issues.redhat.com/browse/RHIDP-2530)
=> feat: support catalog entity extra context menu items.

dynamic-plugins/imports/package.json
Updates the topology plugin to `1.21.10`. `1.21.10` fixes a bug where conditional permission policies for catalog entities would cause the topology view to now show up. 
- Fixes [RHIDP-2594](https://issues.redhat.com/browse/RHIDP-2594)
=> chore(deps): update topology plugin

.rhdh/docker/Dockerfile
Signed-off-by: RHDH Build (rhdh-bot) <rhdh-bot@redhat.com>
=> feat: tagRelease.sh bump versions in 1.2.x for 1.2 release

packages/app/src/apis.ts
Passes the expected `configApi` parameter to resolve warning.
- Fixes [RHIDP-2627](https://issues.redhat.com/browse/RHIDP-2627)
Deprecation warning is not present in the browser console when the OIDC provider is configured.
=> fix(auth): fix deprecation warning when OIDC provider is configured

.github/renovate.json
- Reworked the config so we have smaller, bite sized PRs that will hopefully make things easier to merge
- Dashboard restricted Python PRs because upgrades could potentially cause conflicts (e.g. see [mkdocs-techdocs-core](https://github.com/backstage/mkdocs-techdocs-core/blob/main/requirements.txt#L4-L5) requirements).  There is currently no way to pin down the versions
- For a preview of these changes, see the [dependency dashboard](https://github.com/kim-tsao/backstage-showcase-renovate/issues/3) in the test repo
- Fixes #?
- https://issues.redhat.com/browse/RHIDP-2883
=> chore(renovate): rework config to break down PRs

.ibm/pipelines/resources/config_map/configmap-app-config-rhdh.yaml, e2e-tests/playwright/e2e/custom-theme.spec.ts, e2e-tests/playwright/e2e/github-happy-path.spec.ts, e2e-tests/playwright/support/pageObjects/global-obj.ts, e2e-tests/playwright/utils/APIHelper.ts, e2e-tests/playwright/utils/UIhelper.ts, e2e-tests/playwright/utils/custom-theme/theme-verifier.ts
Refactor custom theme E2E test and update uihelper functions
The custom theme end-to-end test was refactored to be more focused and reliable. The 'UIhelper' was enriched with new functions that improve reusability in tests. Also, configuration for application theming and authentication methods were updated.
Refactor custom theme E2E test and update uihelper functions
The custom theme end-to-end test was refactored to be more focused and reliable. The 'UIhelper' was enriched with new functions that improve reusability in tests. Also, configuration for application theming and authentication methods were updated.
[RHIDP-744](https://issues.redhat.com/browse/RHIDP-744)
=> RHIDP-744 [Test Automation] Automate RHDH theme customization - E2E

e2e-tests/playwright/e2e/github-happy-path.spec.ts, e2e-tests/playwright/support/pages/CatalogImport.ts, e2e-tests/playwright/utils/UIhelper.ts
There is a failing test, because of this bug: https://issues.redhat.com/browse/RHIDP-3159
Reported test flakiness: https://issues.redhat.com/browse/RHIDP-3128
When the test is fixed, only unskip the test. Don't revert this PR.
- Fixes #?
=> RHIDP-3159: Disable failing GitHub test

dynamic-plugins/imports/package.json
Bump the argocd plugin version to include the below bug fix.
- https://issues.redhat.com/browse/RHIDP-2746
Commit section keeps loading in Dynamic Plugin @janus-idp/backstage-plugin-argocd when app is deployed via Helm through ArgoCD.
With this fix commit section will be hidden for the application created via helm charts.
cc: @nickboldt
=> fix(argocd): bump the argocd version to include latest bug fixes

packages/app/public/index.html, packages/app/src/components/AppBase/AppBase.tsx, packages/app/src/components/Root/ConfigUpdater.tsx
Currently `app.branding.iconLogo` is not being injected during runtime, which leads favicon not updating from customization. This PR added a `ConfigUpdater` component to take the config at runtime so that customized iconLogo will be picked up as favicon.
- Fixes issue #777 
- [RHIDP-2673](https://issues.redhat.com/browse/RHIDP-2673)
Test data:
```
data: 
app-config-rhdh.yaml: |
app: 
branding: 
iconLogo: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAMAAABEpIrGAAADAFBMVEVHcEyWcCiolEdoUSP+4DD7xRX8zBe4qVCtjDKtiCL+94mkgSWpiy6tmDmogyC1mzGvnkCjgCaypUW2pTvjuzbhuzfMvD2viBzWwjfYqBW2rU360R+3jRnz2jPg1ETmvzTPsCvZsDn8yhrvuR31ySL+7ETsxC68lCK2jyDhujrFmhq5sVPYrBzerS3zwh+9kBj3yBxWORf+5jL91CF/XB3swizdtTjrrRTitTD1yCO5sFfjujbnvS9KOi3DkBTovC/WqD …
```
=> fix(ui): update config at runtime to apply branding

.rhdh/docker/Dockerfile, docker/Dockerfile
Update the docker file to remove the `NODE_OPTIONS=--no-node-snapshot` environmental variable in favor of directly adding it as an argument in the `ENTRYPOINT`.
This allows users to define their own `NODE_OPTIONS` to add additional node arguments (such as `--max-http-header-size=32768`) without accidentally overwriting the existing `NODE_OPTIONS` defined in the image.
- Fixes N/A
=> chore(docker): remove NODE_OPTIONS in favor of embedding it into the ENTRYPOINT

dynamic-plugins/imports/package.json, yarn.lock
This PR pulls in the scaffolder-relation-processor plugin from the [backstage-community repository](https://github.com/backstage/community-plugins/blob/main/workspaces/scaffolder-relation-processor/plugins/catalog-backend-module-scaffolder-relation-processor/package.json) into the [1.2.x branch of janus-showcase](https://github.com/janus-idp/backstage-showcase/blob/1.2.x/dynamic-plugins/imports/package.json). This includes updating the dynamic-plugins-imports/package.json file to reference the correct version of the plugin.
Updated dynamic-plugins-imports/package.json to include the following dependency because of its newly allocated scope.
`"@backstage-community/plugin-catalog-backend-module-scaffolder-relation-processor": "0.2.0"`
The [scaffolder-relation-processor …
=> Pull in scaffolder-relation-processor plugin from @backstage-community to 1.2.x branch of janus-showcase because it is the new scope.

e2e-tests/playwright.config.ts, e2e-tests/playwright/utils/Common.ts
Now we are using the default resolution for tests 720p. I suggest to switch to 1080p for two reasons:
- Users probably use 1080p (minimum)
- Some parts of the UI might not be shown at 720p (see the two screenshots) bellow.
The drawback is, that the screen recordings will be slightly bigger.
720p
1080p
- Fixes #?
=> [e2e] Increase Plawright resolution to 1080p

e2e-tests/playwright/e2e/catalog-scaffoldedfromLink.spec.ts, e2e-tests/playwright/support/pages/CatalogImport.ts, e2e-tests/playwright/utils/APIEndpoints.ts, e2e-tests/playwright/utils/UIhelper.ts
[e2e] Link Scaffolded Templates to Catalog Items
https://issues.redhat.com/browse/RHIDP-2078
https://issues.redhat.com/browse/RHIDP-2077
=> [e2e] Link Scaffolded Templates to Catalog Items

README.md, dynamic-plugins/imports/package.json, packages/app/package.json, packages/backend/package.json, yarn.lock
This PR is to incorporate updates made to rbac plugin by PR https://github.com/janus-idp/backstage-plugins/pull/1859 and it also updates rbac-backend and rbac-common to its compatible versions.
Once this PR is merged it needs to be cherry-picked in 1.2.x.
- Fixes https://issues.redhat.com/browse/RHIDP-3038
=> chore(rbac): update rbac rbac-backend and rbac-common plugins versions

dynamic-plugins/imports/package.json
Bump the keycloak-backend plugin version to `1.11.1` to include the "[expose extension points for the keycloak-backend plugin](https://github.com/janus-idp/backstage-plugins/blob/main/plugins/keycloak-backend/CHANGELOG.md#janus-idpbackstage-plugin-keycloak-backend-1110-2024-06-19)" change.
- Fixes [RHIDP-2965](https://issues.redhat.com/browse/RHIDP-2965)
=> bump keycloak-backend plugin version

packages/app/src/components/learningPaths/LearningPathsPage.tsx
Fixes: https://issues.redhat.com/browse/RHIDP-3248
With #1379 the @mui/material package is updated from 5.15.21 to 5.16.0 which breaks the learning path page.
* Removed an extra layer of Grid that wasn't necessary.
* Also replaced the custom CSS rule `textDecoration: 'none'` with a Link prop `.underline="none"`
Some history:
- Fixes TODO
=> RHIDP-3248: fix(learningpath): restore spacing between cards

.rhdh/docker/Dockerfile, docker/Dockerfile
Specified `--setopt=install_weak_deps=0` to ensure we are only pulling in required packages when we run a "microdnf update" in the Dockerfiles. 
- Fixes https://issues.redhat.com/browse/RHIDP-3213 
=> ensure that images contain only the minimum set of dependencies

packages/app/config.d.ts, packages/backend/src/modules/authProvidersModule.ts, showcase-docs/auth.md
Update the `signInWithCatalogUserOptional` option to only allow sign in without user being in the catalog with the config `dangerouslySignInWithoutUserInCatalog: true`.
- Fixes [RHIDP-3074](https://issues.redhat.com/browse/RHIDP-3074)
1. Try to sign in with user not present in the catalog and you should see the error message appear - not allowing sign in 
2. Add config: `dangerouslySignInWithoutUserInCatalog: true` and verify that the error message no longer appears and sign in is successful
=> add dangerouslySignInWithoutUserInCatalog option

packages/backend/src/modules/authProvidersModule.ts
[This issue](https://issues.redhat.com/browse/RHIDP-3529) with GitHub user entities not being ingested into the catalog as expected causes the error when trying to sign in with Github in some environments. Temporarily enabling this setting for GitHub until this issue is resolved. (More details in the Jira issue)
- Related to [RHIDP-3529](https://issues.redhat.com/browse/RHIDP-3529)
Confirm that the error not longer appears when signing in with GitHub and the user does not exist in the catalog.
=> Enable dangerouslyAllowSignInWithoutUserInCatalog option for GitHub

yarn.lock
Resolved `prom-client` dependency to the same version to fix the `/metrics` issue
- Fixes [RHIDP-3458](https://issues.redhat.com/browse/RHIDP-3458)
=> chore: fix prometheus metrics

dynamic-plugins/wrappers/backstage-plugin-techdocs-backend-dynamic/dist-dynamic/yarn.lock
Making this consistent with 1.2.x.  Name property got generated as a result of [PR](https://github.com/janus-idp/backstage-showcase/pull/1462) but it may conflict with resolved package, so I'm removing it just to err on the side of caution
- Fixes #?
- N/A
=> chore: regen yarn.lock to remove name property

plugins/dynamic-plugins-info/src/api/DynamicPluginsInfoClient.ts, plugins/dynamic-plugins-info/src/components/DynamicPluginsTable/DynamicPluginsTable.tsx
When setup a default RHDH instance and login as a guest (which is possible by default) and clicking on Administration I got this error:
This API with forbidden:
- Fixes #?
1. Setup an instance with a helm chart
2. Check the Administration page (error message)
=> fix(dynamic-plugins-info): improve plugins error message

.rhdh/docker/Dockerfile, docker/Dockerfile, docker/install-dynamic-plugins.py, showcase-docs/dynamic-plugins.md
Adds support for loading plugins packaged inside OCI images.
Rework of #1469 
Instead of the oras python library, which does not work out of the box with ghcr or docker registries (due to authentication and requesting temporary tokens for auth), this PR uses `skopeo`
The image is downloaded only once, even if it contains multiple plugins.
We're still assuming there's only one layer in the image and only inspect the first layer.
config example
```yaml
plugins:
- disabled: false
package: >-
oci://quay.io/tkral/simple-chat:v0.0.1!internal-backstage-plugin-simple-chat-backend-dynamic
- disabled: false
package: >-
oci://quay.io/tkral/simple-chat:v0.0.1!internal-backstage-plugin-simple-chat
pluginConfig:
frontend:
internal.backstage-plugin-simple-chat:
appIcons:
- importName: …
```
=> add install method of plugin from container registry

.ibm/pipelines/value_files/values_showcase.yaml
1.3 nightly and PR checks Failing, Test catalog-scaffoldedfromLink.spec.ts is failing because the default plugins, which were previously enabled by default, are now disabled. : https://github.com/janus-idp/backstage-showcase/pull/1517
https://issues.redhat.com/browse/RHIDP-3729
=> [e2e] Fix: Enable default required plugins for scaffoldedfromlink test

e2e-tests/package.json, package.json, packages/app/src/build-metadata.json
=> chore: tagRelease.sh: bump to 1.4.0 in main branch + regen yarn.lock

.ibm/pipelines/value_files/values_showcase-rbac.yaml, .ibm/pipelines/value_files/values_showcase.yaml, app-config.dynamic-plugins.yaml, dynamic-plugins.default.yaml, dynamic-plugins/imports/package.json, plugins/dynamic-plugins-info/src/components/DynamicPluginsTable/DynamicPluginsTable.test.tsx, plugins/dynamic-plugins-info/src/components/InternalPluginsMap.tsx
Manual cherry-pick of https://github.com/janus-idp/backstage-showcase/pull/1541 into 1.3.x, because the cherry-pick bot could not do it automagically: https://github.com/janus-idp/backstage-showcase/pull/1541#issuecomment-2321056352
- Fixes https://issues.redhat.com/browse/RHIDP-2738
I manually deployed the [quay.io/janus-idp/backstage-showcase:pr-1547](https://quay.io/repository/janus-idp/backstage-showcase?tab=tags&tag=pr-1547) image in a cluster (via the Operator) and checked that everything works, using the same scenario depicted in https://github.com/janus-idp/backstage-showcase/pull/1541#pullrequestreview-2269148960
/cc @debsmita1
=> [1.3.x] add bulk import plugin

packages/backend/package.json, packages/backend/src/index.ts
Remove static installation of `@backstage/plugin-catalog-backend-module-logs`
* I've tested this change and confirmed that the error no longer occurs
When trying to test images locally and ran into this error. Since we now [provide this plugin dynamically](https://github.com/janus-idp/backstage-showcase/pull/1498), removing the static installation in the backend will fix this issue.
```
{"level":"info","message":"Listening on :7007","service":"rootHttpRouter","timestamp":"2024-09-03 16:05:13"}
/opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1616
throw new Error(
^
Error: Module 'logs' for plugin 'catalog' is already registered
at #doStart (/opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1616:19)
at process.processTicksAndRejections …
```
=> remove static installation of plugin-catalog-backend-module-logs

packages/backend/src/modules/authProvidersModule.ts
When trying to login with GitHub auth, the following error appears when the user signing in is not present in the catalog.
`Login failed; caused by Error: "sub" claim provided by the auth resolver is not a valid EntityRef. `
- Fixes [RHIDP-3896](https://issues.redhat.com/browse/RHIDP-3896)
When `dangerouslyAllowSignInWithoutUserInCatalog` is set to true, there should not be any errors when logging in. 
=> fix entityRef name when signing in without user in catalog

e2e-tests/playwright/e2e/catalog-timestamp.spec.ts
This is a follow-up to #1565, which fixed one test, but broke the following one. The second text expects the search field to be empty, but it is not cleared automatically.
- Fixes [RHIDP-3967](https://issues.redhat.com/browse/RHIDP-3967)
=> [e2e] Fix failure of `catalog-timestamp`

packages/app/src/components/Root/Root.tsx
To allow sidebar menu items with empty string icon to be rendered.
- Fixes [RHIDP-3989](https://issues.redhat.com/browse/RHIDP-3989)
Test with any dynamic plugin with `menuItem.icon` set to `''` in configuration. Such as
```
dynamicRoutes:
- path: /fcp-github-repo
importName: FCPBackstageGitHubRepoTestHarness
menuItem:
text: FCP Github Repo
icon: ''
```
=> fix(ui): allow empty string icon in menu item

packages/backend/src/modules/authProvidersModule.ts
Reverting the temporary change by [this PR](https://github.com/janus-idp/backstage-showcase/pull/1468/files) as [the issue](https://issues.redhat.com/browse/RHIDP-3529) requiring this modification has been addressed.
=> revert enabling dangerouslyAllowSignInWithoutUserInCatalog for GitHub

packages/app/src/api/CustomDataApiClient.ts, packages/app/src/apis.ts
This PR updated the credentials to be passed for the proxy
See Backstage 1.28 release notes about the BREAKING: Proxy backend plugin protected by default -
https://github.com/backstage/backstage/releases/tag/v1.28.0 
- Fixes https://issues.redhat.com/browse/RHIDP-4015 
1. Setup custom data for home page , follow https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.2/html/getting_started_with_red_hat_developer_hub/proc-customize-rhdh-homepage_rhdh-getting-started#proc-customize-rhdh-homepage_rhdh-getting-started 
2. Setup costom data for learning path, follow https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.2/html/getting_started_with_red_hat_developer_hub/proc-customize-rhdh-learning-paths_rhdh-getting-started 
- Using JSON files that are hosted or GitHub or …
=> fix(app): proxy for home and learning paths

e2e-tests/package.json, package.json, packages/app/src/build-metadata.json
=> chore: tagRelease.sh: bump to 1.2.5 in 1.2.x branch + regen yarn.lock

dynamic-plugins.default.yaml
As a user configuring the Kubernetes settings, I specify a limited set of `objectTypes` that I want to view in the topology plugin. However, since RHDH includes pre-configured custom resources in its Kubernetes configuration, I might encounter warnings for resources like Tekton or Routes, which can be confusing as I haven't set up those resources. 
This PR removes custom resources that were pre-configured with the Kubernetes backend dynamic plugin configuration. This change eliminates warnings for resources that haven't been configured by the user.
- Fixes https://issues.redhat.com/browse/RHIDP-4240
Before
After
- Once the image of rhdh is generated for this PR, deploy it on a cluster. 
- Add the below Kubernetes configuration in the …
=> [Topology]: remove custom resources from k8s configuration

packages/app/src/utils/dynamicUI/extractDynamicConfigFrontend.test.ts, packages/app/src/utils/dynamicUI/extractDynamicConfigFrontend.ts
Menu items should be hidden when title is not defined, instead of showing an empty row in menu.
- Fixes [RHIDP-4158](https://issues.redhat.com/browse/RHIDP-4158)
https://github.com/user-attachments/assets/bccef970-1c97-4cc3-80b6-35771cd73d4d
=> RHIDP-4158: fix(ui): hide menu items with no title in sidebar nav

packages/app/src/components/Root/Root.tsx
Getting "Each child in a list should have a unique "key" prop." warning in console.
- Fixes [RHIDP-4213](https://issues.redhat.com/browse/RHIDP-4213)
Run backstage-showcase locally and see Console tab in inspector.
=> fix(ui): fixed console warning

docs/auth.md
When trying to set the `dangerouslyAllowSignInWithoutUserInCatalog` config, it is confusing which indentation to place the config at. This code snippet makes it more clear. 
=> clarify indentation level of config in auth documentation

package.json, yarn.lock
Reverses the [fix](https://github.com/janus-idp/backstage-showcase/pull/1715) to upgrade to this dependency due to incompatibility issues
- Fixes #?
https://issues.redhat.com/browse/RHIDP-4114
https://issues.redhat.com/browse/RHIDP-4115
https://issues.redhat.com/browse/RHIDP-4116
https://issues.redhat.com/browse/RHIDP-4117
=> chore(deps): undo bump @backstage/plugin-techdocs-backend to 1.10.13

e2e-tests/playwright.config.ts
AKS nightly jobs are currently failing due to recently added authProvider tests https://github.com/janus-idp/backstage-showcase/pull/1643 . These tests need to be skipped for AKS clusters, following the same pattern we hav for showcase OCP clusters. 
https://issues.redhat.com/browse/RHIDP-4444 
=> chore(e2e): fix aks tests

.rhdh/docker/Dockerfile, docker/Dockerfile
chore(npm registry default): set default npm registry to https://registry.npmjs.org/ instead of cachito; also set path to cafile  ([RHIDP-4410](https://issues.redhat.com//browse/RHIDP-4410))
N/A
N/A
=> chore(npm registry default): set default npm registry to https://registry.npmjs.org/ instead of cachito; also set path to cafile (RHIDP-4410)

dynamic-plugins/wrappers/backstage-plugin-tech-radar/src/api/CustomTechRadar.ts, dynamic-plugins/wrappers/backstage-plugin-tech-radar/src/index.ts
Fixes: https://issues.redhat.com/browse/RHDHBUGS-99
This PR updated the credentials to be passed for the proxy
See Backstage 1.28 release notes about the BREAKING: Proxy backend plugin protected by default -
https://github.com/backstage/backstage/releases/tag/v1.28.0 
- Fixes https://issues.redhat.com/browse/RHDHBUGS-99
1. Setup custom data for techradar page , follow https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.3/html/getting_started_with_red_hat_developer_hub/proc-customize-rhdh-tech-radar-page_rhdh-getting-started#using-hosted-json-files-to-provide-data-to-the-tech-radar-page
- Using JSON files that are hosted or GitHub or GitLab. To access the data from the JSON files, add below to app-config.yaml
```
proxy:
endpoints:
'/developer-hub':
target: …
```
=> fix(app): proxy for tech-radar

package.json, yarn.lock
This PR, removes `"dset": "^3.1.4"` from resolutions within the 1.2.x branch, undoing this PR: https://github.com/janus-idp/backstage-showcase/pull/1718/files
- Fixes #?
=> chore(deps): remove dset version 3.1.4 from resolutions

dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab-backend-dynamic/dist-dynamic/yarn.lock, yarn.lock
Fix CVE-2024-45590 in the `immobiliarelabs-backstage-plugin-gitlab-backend-dynamic` plugin.  Bumps up other dependencies like braces and mysql2
- Fixes #?
- https://issues.redhat.com/browse/RHIDP-3917
- https://issues.redhat.com/browse/RHIDP-4520
- https://issues.redhat.com/browse/RHIDP-2331
=> chore(deps): release-1.3, update body-parser, mysql2 and braces

.ibm/pipelines/resources/cluster_role_binding/cluster-role-binding-ocm.yaml
Add missing ServiceAccount for ClusterRoleBinding for e2e OCM tests
- Fixes https://issues.redhat.com/browse/RHIDP-4610?
=> add missing ServiceAccount for ClusterRoleBinding

.ibm/pipelines/openshift-ci-tests.sh
Refactor `configure_namespace` by extracting namespace deletion into a new function `delete_namespace`. Introduce functions to remove blocking finalizers and forcibly delete namespaces stuck in 'Terminating' status. This improves reliability and handling of namespace deletions in the OpenShift CI pipeline.
- Fixes [RHIDP-4752](https://issues.redhat.com/browse/RHIDP-4752)
=> Refactor namespace deletion logic and add finalizer removal.

.github/workflows/next-build-image.yaml, .github/workflows/pr-build-image.yaml
To have consistent image names with SHORT_SHA as a suffix, use  `git rev-parse --short=8`. Otherwise, we would get inconsistent number of digits from the command.  
- Fixes [RHIDP-4775](https://issues.redhat.com/browse/RHIDP-4775)
=> chore(e2e): use a fixed digit of SHORT_SHA for image name

catalog-entities/apis/petstore.yaml
An e2e test fails when trying to import https://github.com/janus-idp/backstage-showcase/blob/main/catalog-entities/all.yaml with the following error:
`{"error":{"name":"InputError","message":"InputError: Processor PlaceholderProcessor threw an error while preprocessing; caused by Error: Placeholder $openapi could not read location https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.0/petstore.yaml, NotFoundError: Request failed for https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/petstore.yaml, 404 Not Found"},"request":{"method":"POST","url":"/locations?dryRun=true"},"response":{"statusCode":400}}`
The breakage is due to this [change](https://github.com/OAI/OpenAPI-Specification/pull/4166) which moved …
=> chore(fix): update petstore url to fix tests

e2e-tests/playwright/e2e/github-happy-path.spec.ts
At the test under github happy path: "Verify all 12 Software Templates appear in the Create page", there is an assertion waiting for a title which is already waited and validated on the previous line.
Keeping this step does not add any stability, nor validates anything in the test, and is now causing the test to fail due to the selector resolving to 2 frontend elements.
Example: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/janus-idp_backstage-showcase/1869/pull-ci-janus-idp-backstage-showcase-main-e2e-tests/1853815613202370560/artifacts/e2e-tests/janus-idp-backstage-showcase/artifacts/showcase/trace/index.html?trace=https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/janus-idp_backstage-showcase/1869/pull- …
=> test(e2e): deleting pointless assertion for "Verify all 12 Software Templates appear in the Create page" test

yarn.lock
- Fixes #?
- related to https://github.com/janus-idp/backstage-showcase/commit/e0166d5f80b2b953e44ddfbcf688f4df27381bc3 which dedupes the dependency.  
=> chore(deps): dedupe @types/http-proxy

.rhdh/docker/Dockerfile, docker/Dockerfile
chore(docker): ensure yarn is on the path so we can refer to it inside package.json files
this fix is for downstream but might as well do the same for upstream for now to be consistent
N/A
https://issues.redhat.com/browse/RHIDP-4211
N/A
=> chore(docker): ensure yarn is on the path (RHIDP-4211)

e2e-tests/package.json, package.json, packages/app/src/build-metadata.json
=> chore: tagRelease.sh: bump to 1.3.2 in release-1.3 branch

.rhdh/docker/Dockerfile, docker/Dockerfile, docs/corporate-proxy.md, docs/proxy.md, packages/backend/src/corporate-proxy.ts
Undici has added native support for proxy handling, so it is no longer necessary for us to have our own custom proxy handling for `fetch` calls.
This was introduced in Undici v6.14.0 and enhanced in the next versions and appears to fix the issues faced with the handling of the `NO_PROXY` env var by `fetch` [1]
This PR simplifies the code by removing such custom handling and also clarifies the expectations in the documentation (based on some manual testing I've done).
Note that [`global-agent`](https://github.com/gajus/global-agent) should still continue to handle proxy settings for `node-fetch`.
[1] https://github.com/nodejs/undici/releases/tag/v6.14.0
- Fixes https://issues.redhat.com/browse/RHDHBUGS-106
- Fixes https://issues.redhat.com/browse/RHIDP-4646
Please make sure that the …
=> fix(corporate-proxy): use the built-in `EnvHttpProxyAgent` from `undici` to fix the proxy issues reported

.ibm/pipelines/openshift-ci-tests.sh, e2e-tests/playwright/e2e/plugins/tekton/tekton.spec.ts
Disable Tekton plugin tests by adding `test.describe.skip`. Also, comment out pipeline setup commands in the OpenShift CI script, including steps to install the pipelines operator and apply pipeline configuration.
- Fixes #?
=> Skip Tekton plugin tests and comment out pipeline setup

dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-keycloak-dynamic/dist-dynamic/package.json, dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-keycloak-dynamic/dist-dynamic/yarn.lock, dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-keycloak-dynamic/package.json, dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-bulk-import-backend-dynamic/package.json, dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-bulk-import/package.json
This PR removes the `--no-embed-as-dependencies` flag from the keycloak wrapper's export-dynamic command.
=> chore(keycloak): update export-dynamic command

packages/backend/src/modules/authProvidersModule.ts
When authenticating with GitLab, users were not able to be resolved because the authenticator was trying to resolve via `userId` which is not a valid parameter when users are added via [Catalog Backend Module for GitLab Organizational Data](https://github.com/backstage/backstage/tree/master/plugins/catalog-backend-module-gitlab-org).
This PR fixes this by resolving via the username instead.
- Fixes [RHIDP-4349](https://issues.redhat.com/browse/RHIDP-4349) & [RHDHBUGS-87](https://issues.redhat.com/browse/RHDHBUGS-87)
Users are able to sign in with GitLab. 
=> fix: fix GitLab auth by resolving via username not userId

.ibm/pipelines/openshift-ci-tests.sh
Commented out the `install_pipelines_operator` function calls and a sleep operation in the deployment script. This change is made to disable the installation processes that are not currently necessary, streamlining the script execution.
- Fixes #?
=> chore(e2e): disable unused pipeline operator installation

e2e-tests/playwright/e2e/plugins/rbac/rbac-api.spec.ts
Disable a flaky test in order to unblock other PRs. A separate issue will be opened to re-enable the test. 
- Fixes https://issues.redhat.com/browse/RHIDP-4775
=> test(e2e): disable a flaky test temporarily:  catalog-entity refresh is denied after DELETE

docs/dynamic-plugins/override-core-services.md, packages/backend/package.json, packages/backend/src/defaultServiceFactories.test.ts, packages/backend/src/defaultServiceFactories.ts, packages/backend/src/index.ts, packages/backend/src/logger/customLogger.ts, yarn.lock
This change explicitely adds the default service factories to the backend statically to prevent dynamic plugins from being able to override them by default.  It's possible to override each statically added service factory via an environment variable derived from the service factory ID.  So for example to add a "core.rootHttpService" service factory configuration from a dynamic plugin, set ENABLE_CORE_ROOTHTTPROUTER_OVERRIDE to "true".  This change also adds a logger to the backend main.  Finally, a unit test has been added that checks the installed backend-defaults value for the defaultServiceFactories list against what this change adds to catch future regressions.
- Fixes [RHIDP-4786](https://issues.redhat.com/browse/RHIDP-4786) …
=> feat(backend): add service factories by default

.ibm/pipelines/resources/config_map/configmap-app-config-rhdh.yaml, .ibm/pipelines/value_files/values_showcase.yaml, dynamic-plugins/_utils/src/wrappers.test.ts, e2e-tests/playwright/data/theme-constants.ts, e2e-tests/playwright/e2e/custom-theme.spec.ts, e2e-tests/playwright/utils/custom-theme/theme-verifier.ts
Updates the app-config to now load a custom theme plugin to satisfy the ability to load custom themes dynamically.
- Fixes [RHIDP-4462](https://issues.redhat.com/browse/RHIDP-4462)
There are a couple of things that are worth discussing within this PR.
First, I am using a custom theme plugin that I created and is currently under my name. Ideally, a better alternative would be to move this to a place that the qe team owns / has more control over. I was wondering where that location would be most appropriate and how we want to manage ownership moving forward.
- [Plugin repo](https://github.com/PatAKnight/qe-theme-dynamic-plugins)
- [NPM plugin](https://www.npmjs.com/package/@pataknight/backstage-plugin-rhdh-qe-theme)
Second, this test …
=> chore(e2e): automate custom theme dynamic plugin

dynamic-plugins/wrappers/pagerduty-backstage-plugin-backend-dynamic/dist-dynamic/package.json, dynamic-plugins/wrappers/pagerduty-backstage-plugin-backend-dynamic/dist-dynamic/yarn.lock, dynamic-plugins/wrappers/pagerduty-backstage-plugin-backend-dynamic/package.json
Pagerduty backend plugin was updated recently but the `export-dynamic` command was not. `no-embed-as-dependencies` needed to be removed because of the use of the database by the newer version of Pagerduty backend plugin. See [RHIDP-3844](https://issues.redhat.com/browse/RHIDP-3844) which spun out of [RHIDP-1648](https://issues.redhat.com/browse/RHIDP-1648)
- Fixes [RHIDP-4945](https://issues.redhat.com/browse/RHIDP-4945)
=> fix(pagerduty): update to remove no embed as dependencies

.ibm/pipelines/resources/config_map/app-config-rhdh.yaml, e2e-tests/playwright/e2e/plugins/http-request.spec.ts, e2e-tests/playwright/utils/UIhelper.ts
Reenables the scaffolder-backend-module-http-request e2e test that was disabled due to a problem with the dynamic plugin.
- Fixes [RHIDP-4837](https://issues.redhat.com/browse/RHIDP-4837)
=> chore(e2e): reenable scaffolder-backend-module-http-request test

e2e-tests/playwright/e2e/plugins/rbac/rbac-api.spec.ts, e2e-tests/playwright/support/pages/rbac.ts
https://issues.redhat.com/browse/RHIDP-4958
Added error tracking and logging to beforeEach, afterEach, and afterAll hooks to improve robustness and clarity. Skipped cleanup actions if errors occurred during retries to avoid inconsistent state.
- Fixes #?
=> chore(e2e): rhidp-4958 re-enable the flaky test - catalog-entity refresh is denied after DELETE

.ibm/pipelines/openshift-ci-tests.sh, .ibm/pipelines/resources/pipeline-run/hello-world-pipeline-run.yaml, .ibm/pipelines/resources/pipeline-run/hello-world-pipeline.yaml, .ibm/pipelines/value_files/values_showcase.yaml, e2e-tests/playwright/e2e/plugins/tekton/tekton.spec.ts, e2e-tests/playwright/utils/tekton/tekton.ts
Re-enable previously disabled Tekton pipelines across multiple files. Updated API version from `v1beta1` to `v1` in pipeline YAML files for compatibility.
- Fixes #?
=> chore(e2e): rhidp-4811 Enable Tekton pipelines and update API version

docs/dynamic-plugins/examples.md, docs/dynamic-plugins/index.md
This change adds a document to hold links to examples that have been developed showing either how to use dynamic plugins or show off features that are related to or enabled by dynamic plugins.
- Fixes [RHIDP-4872](https://issues.redhat.com/browse/RHIDP-4872)?
Please request changes with a link for any other examples we would like included in this document.
=> chore(docs): add dynamic plugins examples doc

.ibm/pipelines/openshift-ci-tests.sh, docs/e2e-tests/README.md
In the e2e tests setup, we are installing Chromium, Firefox, and Webkit, but we only run tests on Chromium. This is unnecessary, slows down the process, and produces unintended traffic. This PR edits the tests setup that we only install Chromium and its dependencies.
- Fixes [RHIDP-5047](https://issues.redhat.com/browse/RHIDP-5047)
=> chore(ci): playwright install only chromium

.ibm/pipelines/env_variables.sh, .ibm/pipelines/openshift-ci-tests.sh, e2e-tests/package.json, e2e-tests/playwright.config.ts, e2e-tests/playwright/e2e/configuration-test/config-map.spec.ts, e2e-tests/playwright/utils/helper.ts, e2e-tests/playwright/utils/k8sHelper.ts, yarn.lock
=> chore(e2e): rhidp-4049 change app-config at e2e test runtime

e2e-tests/package.json, package.json, packages/app/src/build-metadata.json
=> chore: tagRelease.sh: bump to 1.5.0 in main branch + regen yarn.lock

.ibm/pipelines/openshift-ci-tests.sh, .ibm/pipelines/utils.sh
- Re-enable Data Router (`droute`) after the outage got resolved.
- Add an exception to don't fail the PR check if only `droute` failed. That way, `droute` failure would only fail the nightly jobs. 
- Fixes [issues.redhat.com/browse/RHIDP-5084](https://issues.redhat.com/browse/RHIDP-5084)
=> chore(ci): re-enable `droute` and don't fail on pull requests

dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-dynamic-home-page/package.json, yarn.lock
* This updates the `dynamic-home-page` dependency to include @kim-tsao PR https://github.com/janus-idp/backstage-showcase/pull/1977 after we migrated the plugin to rhdh-plugins repo.
* ~~Also removed the default home page and added it to the dynamic-plugins.default.yaml. When a user disables the dynamic home page, also the menu item will disappear automatically.~~
- Fixes #?
=> fix(homepage): wrapper update (incl update @scalprum/react-core from 0.8 to 0.9)

yarn.lock
Missed updating cross-spawn in root yarn.lock
CVE-2024-21538
- Fixes #?
[RHIDP-4864](https://issues.redhat.com/browse/RHIDP-4864)
=> chore(deps): update root yarn.lock

dynamic-plugins/wrappers/backstage-community-plugin-acr/src/index.ts, dynamic-plugins/wrappers/backstage-community-plugin-jfrog-artifactory/src/index.ts, dynamic-plugins/wrappers/backstage-community-plugin-nexus-repository-manager/src/index.ts, dynamic-plugins/wrappers/backstage-community-plugin-ocm/src/index.ts, dynamic-plugins/wrappers/backstage-community-plugin-quay/src/index.ts, dynamic-plugins/wrappers/backstage-community-plugin-rbac/src/index.ts, dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd/src/index.ts, dynamic-plugins/wrappers/backstage-community-plugin-tekton/src/index.ts, dynamic-plugins/wrappers/backstage-community-plugin-topology/src/index.ts, dynamic-plugins/wrappers/backstage-plugin-notifications/src/index.ts, dynamic-plugins/wrappers/backstage-plugin-signals/src/index.ts, dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-bulk-import/src/index.ts, dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-dynamic-home-page/src/index.ts
Big thanks and kudos to @gashcrumb who solved the issue https://github.com/janus-idp/backstage-plugins/pull/2183 for dynamic plugins with a comment. But it needs to be applied to all plugins.
I'm adding this here now (also with respect to the 1.4 timeline) to these frontend plugins that allowed me to add it.
I would expect that a better solution is to automatically apply this rule when bundling a plugin! But for me the code looks save to be called twice and I'm fine to revert this in 1.4 or 1.5 as soon as we're sure that we include this somewhere else. Tbc. and tbd.  :smirk: 
This fixes at least our ad-hoc issues with Bulk import and RBAC.
* https://issues.redhat.com/browse/RHIDP-5104 Bulk import layout issues with MUI v5 components (missing gaps)
I tested these plugins and compared …
=> fix: add mui v5 workaround in wrapper code

dynamic-plugins/wrappers/backstage-plugin-techdocs/src/ShadowRootStylesProvider.tsx, dynamic-plugins/wrappers/backstage-plugin-techdocs/src/addons.tsx, dynamic-plugins/wrappers/backstage-plugin-techdocs/src/wrapped.tsx
Techdocs are rendered in a shadow root so that the backstage theme doesn't affect the rendered content, and the markdown style doesn't affect the backstage app.
The `ReportIssue` techdocs addon requires some additional CSS rules ([for example](https://github.com/backstage/backstage/blob/master/plugins/techdocs-module-addons-contrib/src/ReportIssue/ReportIssue.tsx#L36-L44)), which needs to apply to this shadow root, which also works in a common backstage installation.
But with our dynamic plugins (based on webpack federation) these MUI v4 styles are applied to the root dom via JSS.
This PR adds a workaround to ensure that the styles of the `ReportIssue` components are added within the shadow root element.
It isn't possible to create an additional shadow root here without reusing or copying …
=> fix(techdocs): fix ReportIssue style issue when loaded as dynamic plugin

dynamic-plugins/wrappers/backstage-plugin-techdocs/src/ShadowRootStylesProvider.tsx, dynamic-plugins/wrappers/backstage-plugin-techdocs/src/addons.tsx, dynamic-plugins/wrappers/backstage-plugin-techdocs/src/wrapped.tsx
This is backport of #2024
**1.4 without this PR:**
https://github.com/user-attachments/assets/92837c7a-7f52-4e81-9879-ff8d6cfa6416
**with this PR (tested on a cluster with [pr-2029-29bed5cf](https://quay.io/janus-idp/backstage-showcase:pr-2029-29bed5cf))**
https://github.com/user-attachments/assets/fef8bd4c-2dcf-400e-9cab-4418ea0905e4
- Fixes [RHDHBUGS-97](https://issues.redhat.com/browse/RHDHBUGS-97) Bug in text selection in "Docs" section of RHDH
- 1.4 ticket [RHIDP-5120](https://issues.redhat.com/browse/RHIDP-5120) Huge icon when techdoc text is selected, and report a doc issue feature didn't worked [1.4]
Techdocs is enabled by default.
=> fix(techdocs): fix ReportIssue style issue when loaded as dynamic plugin [release-1.4]

dynamic-plugins/wrappers/backstage-plugin-techdocs/package.json, dynamic-plugins/wrappers/backstage-plugin-techdocs/src/ShadowRootStylesProvider.tsx, dynamic-plugins/wrappers/backstage-plugin-techdocs/src/addons.tsx, dynamic-plugins/wrappers/backstage-plugin-techdocs/src/wrapped.tsx, yarn.lock
This is a manual backport of #2024 (main) / #2029 (1.4) because 1.3 has different code style (prettier) rules and requires that the material-ui dependency be mentioned in the techdocs package.json.
**1.3 without this PR:**
https://github.com/user-attachments/assets/0fc47831-5cd4-45c3-9861-bb539647b1b9
**with this PR (tested on a cluster with [pr-2030-abfb8b96](https://quay.io/janus-idp/backstage-showcase:pr-2030-abfb8b96))**
https://github.com/user-attachments/assets/a064fd54-c8a8-40fc-84c4-10c43aa2243b
- Fixes [RHDHBUGS-97](https://issues.redhat.com/browse/RHDHBUGS-97) Bug in text selection in "Docs" section of RHDH
- 1.3 ticket [RHIDP-5121](https://issues.redhat.com/browse/RHIDP-5121) Huge icon when techdoc text is selected, and report a doc issue feature didn't worked [1.3]
Please make …
=> fix(techdocs): fix ReportIssue style issue when loaded as dynamic plugin [release-1.3]

e2e-tests/playwright/e2e/configuration-test/config-map.spec.ts
Integrated the UIhelper utility to open the "Home" sidebar in the configuration map test. This enhances the test by ensuring the correct UI state before verifying the page title, improving accuracy and reliability.
- Fixes #?
=> Add UI helper to open sidebar in config map test

docs/e2e-tests/CONTRIBUTING.MD
Adding some general rules that I think are relevant.
- Fixes https://issues.redhat.com/browse/RHIDP-4243
=> docs: adding general rules to e2e contribution guidelines 

packages/app/src/components/UserSettings/GeneralPage.tsx, packages/app/src/components/UserSettings/InfoCard.test.tsx, packages/app/src/components/UserSettings/InfoCard.tsx, packages/app/src/components/UserSettings/SettingsPages.tsx
**Fixes:** https://issues.redhat.com/browse/RHIDP-5212
The settings page shows currently 5 build information on the settings page:
This PR
1. shows only the "RHDH Version" and "Backstage Version" by default.
2. the card shows a Copy button that copies (all) build information to the clipboard.
3. the card shows also a More/Less button to show all build information.
4. it automatically saves in localStorage if the user expands the information and shows them the next time automatically
5. it also shows more information when the user clicks (or tries to select) the version information
6. or when the user tries to copy the information with the keyboard.
https://github.com/user-attachments/assets/133897c8-30d1-4ead-94f5-81aa70e9a643
- TODO
=> feat(settings): hide detailed build version information and show them on demand

e2e-tests/playwright/e2e/catalog-scaffoldedfromLink.spec.ts, e2e-tests/playwright/utils/Common.ts
Improve Github popup login used in catalog-scaffoldedfromLink.spec.ts, which is making the e2e fail. 
- Fixes [RHIDP-5209](https://issues.redhat.com/browse/RHIDP-5209)
=> fix: [e2e-tests] Improve Github popup login used in catalog-scaffoldedfromLink.spec.ts

dynamic-plugins/wrappers/backstage-community-plugin-topology/package.json
chore(metadata) backstage-community-plugin-topology should remain GA level support [ci skip]
N/A
Because this plugin was GA in 1.3, it should remain GA after moving to BCP repo. 
https://issues.redhat.com/browse/RHIDP-5103
N/A
=> chore(metadata): backstage-community-plugin-topology should remain GA level support [ci skip] (RHIDP-5103)

.ibm/pipelines/value_files/values_showcase-rbac.yaml
This PR also enables the 'dynamic-home-page' plugin in 1.4 when running and testing the CI job with RBAC.
The plugin is enabled for customers **by default** and was disabled without any reason (a copy-paste issue by myself, I guess) in the RBAC setup.
And this confused people (for a good reason), so also if this doesn't touch our product, it might help to reduce noise in the future by fixing the CI config.
It was merged into main as part of #2089
- Fixes #?
=> [release-1.4] chore(ci): enable homepage plugin on ci setup

e2e-tests/package.json, package.json, packages/app/src/build-metadata.json
=> chore: tagRelease.sh: bump to 1.4.1 in release-1.4 branch

.ibm/pipelines/cluster/aks/az.sh, .ibm/pipelines/cluster/aks/deployment.sh, .ibm/pipelines/cluster/gke/deployment.sh, .ibm/pipelines/cluster/gke/gcloud.sh, .ibm/pipelines/cluster/osd-gcp/create-osd.sh, .ibm/pipelines/cluster/osd-gcp/destroy-osd.sh, .ibm/pipelines/jobs/aks.sh, .ibm/pipelines/jobs/gke.sh, .ibm/pipelines/jobs/main.sh, .ibm/pipelines/jobs/operator.sh, .ibm/pipelines/jobs/periodic.sh, .ibm/pipelines/openshift-ci-tests.sh, .ibm/pipelines/utils.sh, e2e-tests/playwright/e2e/plugins/quick-access-and-tech-radar.spec.ts
- Fix k8s CI job configurations after https://github.com/janus-idp/backstage-showcase/pull/2032 
- Use `#!/bin/bash` shebang in CI files. This is appropriate for how the scripts are written and is recommended by https://github.com/koalaman/shellcheck. Also incorporate more improvements from ShellCheck.
- Fixes [RHIDP-5214](https://issues.redhat.com/browse/RHIDP-5214)
=> chore(ci): fix k8s jobs, better shebang 

dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-org-dynamic/package.json, dynamic-plugins/wrappers/backstage-plugin-notifications-backend-dynamic/package.json, yarn.lock
This change updates the wrappers for the notification backend and catalog backend module for gitlab org to explicitly embed some packages that are needed at runtime, as the normal behavior of the janus-idp CLI for these dependencies are to move them to peer dependencies.
- Fixes [RHIDP-5308](https://issues.redhat.com/browse/RHIDP-5308)
- Fixes https://issues.redhat.com/browse/RHIDP-5319
=> fix(wrappers): embed runtime dependencies

dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-org-dynamic/dist-dynamic/package.json, dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-org-dynamic/dist-dynamic/yarn.lock, dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-org-dynamic/package.json
fixes missing embedded dependency in gitlab-org plugin
- Fixes https://issues.redhat.com/browse/RHIDP-5319
=> [release-1.3] fix gitlab-org wrapper

dynamic-plugins/wrappers/backstage-community-plugin-rbac/package.json, plugins/licensed-users-info-backend/package.json, yarn.lock
Updates RBAC frontend to include https://github.com/backstage/community-plugins/pull/2173
- Fixes: https://issues.redhat.com/browse/RHIDP-5134 and https://issues.redhat.com/browse/RHIDP-5135
=> fix(rbac): fix overview page styling issues

.ibm/pipelines/jobs/periodic.sh
revert nightly job namespace names changes made in https://github.com/janus-idp/backstage-showcase/pull/2101
- Fixes #?
=> chore(ci): revert nightly job namespace names

.ibm/pipelines/jobs/aks.sh
This PR enables the use of an ephemeral AKS cluster. 
Cluster provisioning will be part of the job (configured in https://github.com/openshift/release/pull/59507). However, this PR needs to be merged first.
The fallback to a long-running cluster is kept.
- Fixes [RHIDP-4763](https://issues.redhat.com/browse/RHIDP-4763)
=> chore(ci): use ephemeral AKS cluster with fallback

.ibm/pipelines/utils.sh
Data Router (`droute`) is failing to send the test results on the first try. This PR adds the retry, which seems to work fine (the second retry is usually successful).
This also adds verbose logging and recommended troubleshooting steps.
Related to discussion here: https://redhat-internal.slack.com/archives/C06Q4M84XDG/p1734598673170759
- Fixes [RHIDP-5392](https://issues.redhat.com/browse/RHIDP-5392)
=> chore(ci): fix droute failing to send results on 1st try

.ibm/pipelines/utils.sh
Use better error handling for the Data Router. Previously, if there was any failure in the test and if the Data Router retry was triggered, it resulted in highlighting the error message from the Data Router, even though it was not actually an error.
- Fixes [RHIDP-5392](https://issues.redhat.com/browse/RHIDP-5392)
=> chore(ci): fix droute error handling for nightly

.github/workflows/next-build-image.yaml, .github/workflows/pr-build-image.yaml, .github/workflows/update-backstage.yaml, .github/workflows/versioned-build-image.yaml
chore(migrate) switch from janus-idp secrets and quay publishing paths to rhd and quay.io/rhdh-community
N/A
N/A
=> chore(migrate): switch from janus-idp secrets and quay publishing paths to rhd and quay.io/rhdh-community

README.md
Some small text changes after we migrated from Janus IDP to RHD.
=> docs: update some janus and showcase references

.ibm/pipelines/resources/config_map/app-config-rhdh-rbac.yaml, .ibm/pipelines/resources/config_map/app-config-rhdh.yaml, .ibm/pipelines/resources/config_map/dynamic-homepage-and-sidebar-config.yaml, .ibm/pipelines/utils.sh
Refactor e2e tests that use hardcoded `janus-idp/backstage-showcase` => `redhat-developer/rhdh` (folders, yaml references etc.)
I kept the references to `quay.io/janus-idp/backstage-showcase`.
This fixes this error caused by having hardcoded variables and the repo migration:
```
cp: cannot stat '/tmp/backstage-showcase/e2e-tests/test-results/*': No such file or directory
```
- Fixes [RHIDP-5497](https://issues.redhat.com/browse/RHIDP-5497)
=> chore(ci): refactor hardcoded backstage-showcase in e2e tests

packages/backend/package.json, plugins/dynamic-plugins-info-backend/package.json, plugins/licensed-users-info-backend/package.json, plugins/scalprum-backend/package.json, yarn.lock
Updates to Express v4.21.2 to bump path-to-regexp to v0.1.12
Fixes: CVE-2024-52798
- Fixes [RHIDP-5177](https://issues.redhat.com/browse/RHIDP-5177)
=> chore(deps): [release-1.4] Bump path-to-regexp to v0.1.12 to fix CVE-2024-52798

.ibm/pipelines/value_files/diff-values_showcase_AKS.yaml, .ibm/pipelines/value_files/diff-values_showcase_GKE.yaml
`Verify Scaffolded link in components Dependencies and scaffoldedFrom relation in entity Raw Yaml` tests are failing for nightly GKE and AKS. Seems like at some point the plugin was disabled and never re-enabled. This is causing the tests to fail as the label that comes from the `backstage-community-plugin-catalog-backend-module-scaffolder-relation-processor-dynamic` is not present.
This PR enables the plugin so that the tests will pass again.
- Fixes [RHIDP-5450](https://issues.redhat.com/browse/RHIDP-5450)
=> chore(e2e): enable scaffolder processor for GKE and AKS tests

.github/workflows/pr-build-image.yaml
https://issues.redhat.com/browse/RHIDP-5538
Add steps to detect PRs with changes only in the `e2e/` folder and skip the build in such cases. Additionally, check if the image already exists in Quay.io and bypass the build if it does. This reduces unnecessary builds, improving efficiency in the CI workflow.
- Fixes https://issues.redhat.com/browse/RHIDP-5538
=> chore(e2e): skip PR build for changes limited to e2e folder or existing image

.github/workflows/pr-build-image.yaml
Corrected the folder name from 'e2e' to 'e2e-tests' in workflow logic to ensure accurate conditional checks. This prevents incorrect build skips or triggers due to the inconsistent naming.
- Fixes #?
=> chore(CI): fix typo in folder name in CI build condition check

.ibm/pipelines/env_variables.sh, .ibm/pipelines/openshift-ci-tests.sh, .ibm/pipelines/resources/config_map/app-config-rhdh-rbac.yaml, .ibm/pipelines/resources/config_map/app-config-rhdh.yaml, .ibm/pipelines/resources/postgres-db/values-showcase-postgres.yaml, .ibm/pipelines/utils.sh, .ibm/pipelines/value_files/values_showcase-rbac.yaml, .ibm/pipelines/value_files/values_showcase.yaml, e2e-tests/package.json, e2e-tests/playwright/e2e/github-happy-path.spec.ts, e2e-tests/playwright/e2e/plugins/quay/quay.spec.ts, e2e-tests/playwright/support/pages/CatalogImport.ts, e2e-tests/playwright/utils/APIEndpoints.ts
Refactor repo name and image.
- Repository: `janus-idp/backstage-showcase` => `redhat-developer/rhdh`
- Quay.io:`janus-idp/backstage-showcase` => `rhdh-community/rhdh`
This fixes this error caused by having hardcoded variables and the repo migration:
```
cp: cannot stat '/tmp/backstage-showcase/e2e-tests/test-results/*': No such file or directory
```
Should fix also:
```
Timed out waiting for Docker image redhat-developer/rhdh:pr-2179-3b39bd3a. Time elapsed: 50 minute(s).
```
- Fixes [RHIDP-5497](https://issues.redhat.com/browse/RHIDP-5497), [RHIDP-5555](https://issues.redhat.com/browse/RHIDP-5555)
=> chore(migration): refactor hardcoded repo and images (#2172, #2181)

packages/backend/package.json, yarn.lock
* patch update for @opentelemetry/host-metrics which contains a fix version for the `systeminformation` dependency
* seems to be a safe update since [changes](https://github.com/open-telemetry/opentelemetry-js-contrib/commits/main/packages/opentelemetry-host-metrics) have been minimal since `0.35.4`
- Fixes #?
CVE-2024-56334
https://issues.redhat.com/browse/RHIDP-5541
=> chore: update opentelemetry/host-metrics to fix CVE-2024-56334

.ibm/pipelines/env_variables.sh, .ibm/pipelines/openshift-ci-tests.sh, .ibm/pipelines/resources/config_map/configmap-app-config-rhdh-rbac.yaml, .ibm/pipelines/resources/config_map/configmap-app-config-rhdh.yaml, .ibm/pipelines/utils.sh, .ibm/pipelines/value_files/values_showcase-rbac.yaml, .ibm/pipelines/value_files/values_showcase.yaml, e2e-tests/playwright/e2e/github-happy-path.spec.ts, e2e-tests/playwright/e2e/plugins/quay/quay.spec.ts, e2e-tests/playwright/support/pages/CatalogImport.ts
=> Cherry pick 1.3 showcase refactor

.github/actions/docker-build/action.yaml, .github/actions/get-sha/action.yml, .github/workflows/next-build-image.yaml, .github/workflows/pr-build-image.yaml
This updates the build process for the next image (build from main branch)
It adds the arm64 image build. arm64 and amd64 are built in parallel.
Platform specific images are tagged with `next-{platform}`. This is mainly to make the amd64 image available quickly (takes less than 40 min) for testing, as arm64 build can take 4 hours.
After both builds are done, the `next` multiplatform tag is pushed and can be used.
- Fixes https://issues.redhat.com/browse/RHIDP-5027
=> chore(ci): build multiplatform next container image

.ibm/pipelines/utils.sh, e2e-tests/playwright.config.ts
Skip a test that uses Route which is specific to OCP and doesn't work on K8S.
- Fixes #?
=> chore(e2e): skip topology plugin test on k8s clusters

e2e-tests/playwright/e2e/audit-log/catalog.spec.ts, e2e-tests/playwright/e2e/audit-log/log-utils.ts
=> chore(e2): rhidp-5439 - [e2e] container "backstage-backend" in pod ... is waiting to start: PodInitializing

e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
same as https://github.com/redhat-developer/rhdh/pull/2155
- Fixes #?
=> test(e2e): adjust selectors for rbac test for 1.4

e2e-tests/playwright/e2e/audit-log/catalog.spec.ts
skip audit log test until its fixed.
- Fixes #?
=> chore(e2e): skip audit log test

catalog-entities/groups.yaml, catalog-entities/groups/rhdh-team.yaml, catalog-info.yaml, docs/mkdocs.yml
Replace Showcase with RHDH and finally add a catalog-info.yaml to the root so that we can use it in our team instance.
With that, it will just expose a system `rhdh` and a component `rhdh`.
This is the first of multiple PRs because the e2e tests load some catalog entities from this repo (via an url from main). So this PR adds the new RHDH catalog entity, a follow-up PR will then change the tests, and later I will cleanup the showcase entities.
- Part of https://issues.redhat.com/browse/RHIDP-5574
I've tested it with a `app-config.local.yaml`
```yaml
catalog:
rules:
- allow: [Component, System, Group, Resource, Location, Template, API]
locations:
- type: file
target: ../../catalog-info.yaml
- type: file
target: …
```
=> chore: create catalog-info.yaml and entity for the rhdh-team

e2e-tests/playwright/e2e/catalog-scaffoldedfromLink.spec.ts, e2e-tests/playwright/e2e/plugins/bulk-import.spec.ts, e2e-tests/playwright/utils/quay/quay.ts
chore(e2e): add delay after template registration to prevent catalog open failure
https://issues.redhat.com/browse/RHIDP-5671 
=> chore(e2e): add delay after template registration to prevent catalog open failure

.github/workflows/pr-build-image.yaml, .ibm/pipelines/openshift-ci-tests.sh
chore: fix PR builder so that when new commits are added to an existing PR, new builds happen. Previously it was assumed that the presence of a pr-123 tag meant the build was already done, but this could be for a previous commit SHA, so we need to check for the presence of a pr-123-SHA image tag, instead of pr-123. 
- Fixes #?
=> chore: fix PR builder so when new commits are added, new builds happen (check for pr-123-SHA instead of pr-123)

yarn.lock
Fixes [CVE-2024-55565](https://github.com/advisories/GHSA-mwcw-c2x4-8c55) by bumping nanoid to 3.3.8
- Fixes [RHIDP-5540](https://issues.redhat.com/browse/RHIDP-5540)
=> chore(deps): bump nanoid to 3.3.8 to fix CVE-2024-55565

.github/workflows/next-build-image.yaml
fixing failing nightly next image build
=> chore(ci): fix nightly image build by add missing step to set REF_NAME based on branch

e2e-tests/playwright/e2e/catalog-scaffoldedfromLink.spec.ts, e2e-tests/playwright/e2e/plugins/bulk-import.spec.ts, e2e-tests/playwright/utils/quay/quay.ts
chore(e2e): cherry-pick #2245 - add delay after template registration to prevent catalog open failure 
https://issues.redhat.com/browse/RHIDP-5671 
=> chore(e2e): cherry-pick #2245 - add delay after template registration to prevent catalog open failure

.ibm/pipelines/jobs/periodic.sh
rh-pre-commit.version: 2.3.2
rh-pre-commit.check-secrets: ENABLED
ignore sanity deployment in periodic job due to [RHIDP-5689](https://issues.redhat.com/browse/RHIDP-5689):
- Fixes #?
=> chore(ci): ignore sanity deployment in periodic job

.github/renovate.json
Disable updates from rhdh-plugins which are currently bundled together with other updates and making it difficult to review/merge.  
See examples:
https://github.com/redhat-developer/rhdh/pull/2228
https://github.com/redhat-developer/rhdh/pull/2225
The current expectation is to have plugin owners run the GH workflow to update their plugins so we'll rely on that for now
- Fixes #?
- https://issues.redhat.com/browse/RHIDP-5743
=> chore: disable renovate updates from rhdh-plugins

.rhdh/docker/Dockerfile, docker/Dockerfile
The existence of the index.html.tmpl tells Backstage to take that file and load it into memory, inject the needed appConfig (instead of writing it into a random *.chunk.js file, and then serve that file from memory so that we can set the readOnlyRootFilesystem: true option for the RHDH container, further improving the security of our offering.
https://issues.redhat.com/browse/RHIDP-5761
=> chore: linking index.html to index.html.tmpl

.ibm/pipelines/jobs/gke.sh
After migration to a Standard GKE cluster, a temporary token was used. This proved not reliable with GKE and a permanent token is better.
- Fixes #?
=> chore(ci): change service account token on GKE

.ibm/pipelines/openshift-ci-tests.sh
rh-pre-commit.version: 2.3.2
rh-pre-commit.check-secrets: ENABLED
RDS test automation tests are failing and need to be investigated. They will be skipped for the time being.
- Fixes #?
=> chore(ci): skip rds tests in 1.4

packages/backend/package.json, yarn.lock
Manual cherry pick of https://github.com/redhat-developer/rhdh/pull/2224 to bump undici to v6.21.1
- Fixes #?
- [RHIDP-5739](https://issues.redhat.com/browse/RHIDP-5739)
- [CVE-2025-22150](https://redirect.github.com/nodejs/undici/security/advisories/GHSA-c76h-2ccp-4975)
=> chore: [release-1.3] fix CVE-2025-22150

dynamic-plugins.default.yaml, dynamic-plugins/wrappers/backstage-community-plugin-acr/package.json, yarn.lock
Update ACR plugin from 1.8.5 to 1.10.0.
From https://github.com/backstage/community-plugins/blob/main/workspaces/acr/plugins/acr/CHANGELOG.md
- 182e024: Backstage version bump to v1.35.0
- 0c1e93a: add support for the new frontend-system (alpha)
- 0c1e93a: Aligned the exported component names with other plugins and the Backstage recommendations. Please use the exported `AcrImagesEntityContent` component instead of `AcrPage`. `AcrPage` is still exported, but deprecated and might be removed in the future.
- f9270df: fix `react-use` compile issue and update plugin description
- 350250c: Updated dependency `@testing-library/jest-dom` to `6.6.3`.
- 18f9d9d: Updated dependency `@types/node` to `18.19.68`.
- a6e850f: Updated dependency `msw` to `1.3.5`.
- 2nd step of …
=> feat(acr): update acr plugin to 1.10.0

docs/auth.md, docs/ping-identity-oidc-setup.md, packages/backend/package.json, packages/backend/src/modules/authProvidersModule.ts, packages/backend/src/modules/authResolvers.ts, yarn.lock
Adds the `oidcSubClaimMatchingKeycloakUserId` and `oidcSubClaimMatchingPingIdentityUserId` resolvers that resolve based on the more secure, `sub` claim from OIDC.
- Fixes [RHIDP-4798](https://issues.redhat.com/browse/RHIDP-4798)
=> chore: add additional OIDC auth resolvers

packages/app/package.json, packages/app/src/components/Root/Root.tsx, yarn.lock
Randomly found the dependency to @janus-idp/backstage-plugin-rbac-common today.
This PR replaces it with @backstage-community/plugin-rbac-common
- Resolves https://issues.redhat.com/browse/RHIDP-5871
=> refactor: replace janus-idp/rbac-common dep with updated BCP/rbac-common

docs/auth.md, docs/dynamic-plugins/export-derived-package.md, packages/app/config.d.ts, packages/backend/package.json, packages/backend/src/modules/authProvidersModule.test.ts, packages/backend/src/modules/authProvidersModule.ts, packages/backend/src/transientGroupOwnershipResolver.test.ts, packages/backend/src/transientGroupOwnershipResolver.ts, yarn.lock
* Adds `InheritedGroupOwnershipResolver` to provide the ability to add optionally transient parent groups into the resolved user group membership
* Enabled by this config: `includeInheritedGroupOwnership?: boolean`
* Adds unit tests for `AuthProviderModule` and `InheritedGroupOwnershipResolver`
With `includeTransientGroupOwnership` to true:
* Includes `maintainers` group which is a parent of `maintainers-plugins` and `maintainers-showcase`
With `includeTransientGroupOwnership` to false (by default):
* only direct group ownership is included
- Fixes [RHIDP-5505](https://issues.redhat.com/browse/RHIDP-5505) and [RHIDP-5506](https://issues.redhat.com/browse/RHIDP-5506)
=> feat: support configuration to include transient group ownership during auth

.github/renovate.json
Enable this config in order to pick up the recent @janus-idp/cli changes that were made
- Fixes #?
- https://issues.redhat.com/browse/RHIDP-5890
See test [PR](https://github.com/kim-tsao/rhdh-renovate-2/pull/25)
=> chore: enable renovate on janus cli updates

docker/install-dynamic-plugins.py, docs/dynamic-plugins/installing-plugins.md
It introduces quasi locking mechanism to make sure install-dynamic-plugins script does not write to dynamic-plugins-root directory concurrently to shared persistence volume.
https://issues.redhat.com/browse/RHIDP-5732
To test on Operator:
1. Configure PVC for dynamic-plugins-root volume in profile/rhdh/default-config/deployment.yaml
```
volumes:
- name: dynamic-plugins-root
persistentVolumeClaim:
claimName: dynamic-plugins-root
```
and deploy Operator with it
2. Create PVC like
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
name: dynamic-plugins-root
spec:
accessModes:
- ReadWriteOnce
volumeMode: Filesystem
resources:
requests:
storage: 2Gi
```
3. Create multi replica Backstage CR like:
```
apiVersion: …
```
=> feat: avoid dynamic-plugins writing conflicts

.ibm/pipelines/env_variables.sh, .ibm/pipelines/jobs/periodic.sh, .ibm/pipelines/resources/postgres-db/values-showcase-postgres.yaml, .ibm/pipelines/utils.sh, e2e-tests/package.json, e2e-tests/playwright.config.ts, e2e-tests/playwright/e2e/configuration-test/config-map.spec.ts, e2e-tests/playwright/e2e/verify-tls-config-health-check.spec.ts
Right now there is one TLS config test that runs as it's own test suite. Later on more TLS config tests will be made, so they need to all be contained into one test suite in one namespace (showcase-runtime). 
[RHIDP-5557](https://issues.redhat.com/browse/RHIDP-5557)
=> chore(e2e): incorporate tls tests into showcase-runtime

app-config.dynamic-plugins.yaml, dynamic-plugins.default.yaml, dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-global-floating-action-button/package.json, yarn.lock
- remove the default GitHub FAB
- updated the fab wrapper to the version 1.0.0
- enabled the fab plugin by default
- Fixes https://issues.redhat.com/browse/RHIDP-5844
=> fix: update fab wrapper

dynamic-plugins/wrappers/backstage-community-plugin-rbac/package.json, e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts, e2e-tests/playwright/support/pageObjects/rbac-po.ts, e2e-tests/playwright/support/pages/rbac.ts, e2e-tests/playwright/utils/ui-helper.ts, packages/app/package.json, packages/backend/package.json, plugins/licensed-users-info-backend/package.json, yarn.lock
Updates all of the RBAC plugins. Also removes `@janus-idp/backstage-plugin-rbac-common` in favor of `@backstage-community/plugin-rbac-common`.
- [RHDHBUGS-162](https://issues.redhat.com/browse/RHDHBUGS-162)
- [RHIDP-5232](https://issues.redhat.com/browse/RHIDP-5232)
=> chore: update rbac plugins

e2e-tests/package.json, package.json, packages/app/src/build-metadata.json
=> chore: tagRelease.sh: bump to 1.6.0 in main branch + regen yarn.lock

.github/workflows/next-build-image.yaml
Updates next-build-image GitHub Workflow to use actual arm machine (ubuntu-24.04-arm) to build the arm image, no more emulation.
This reduces the arm image build time from 6+ hours to 1 hours 🎉 
- Fixes #?
=> chore(ci): use arm VM (ubuntu-24.04-arm) for building arm images

.ibm/pipelines/env_variables.sh, .ibm/pipelines/jobs/periodic.sh, .ibm/pipelines/openshift-ci-tests.sh, .ibm/pipelines/utils.sh, .ibm/pipelines/value_files/sanity-check-plugins.yaml, e2e-tests/package.json, e2e-tests/playwright.config.ts, e2e-tests/playwright/e2e/audit-log/catalog.spec.ts
Reintegrates the "add_sanity_plugins_check" step into the periodic pipeline.
- Fixes #?
=> chore(e2e): refactor periodic pipeline to include sanity plugins check

dynamic-plugins.default.yaml
With #2263 we merged a small configuration where the Pod init fails to start when the notification and header plugin are enabled. Since the header is now enabled by default this means as soon as someone enables the notification plugin.
Why this doesn't happen on e2e? Because the header is there disabled yet because the e2e tests aren't ready yet... Lessons learned...
Helm chart example:
```
global:
dynamic:
plugins:
- package: ./dynamic-plugins/dist/backstage-plugin-notifications
disabled: false
- package: ./dynamic-plugins/dist/backstage-plugin-notifications-backend-dynamic
disabled: false
- package: ./dynamic-plugins/dist/backstage-plugin-signals
disabled: false
- package: ./dynamic-plugins/dist/backstage-plugin-signals-backend-dynamic
disabled: false
```
Pod failed with duplicate …
=> fix: pod failed to start with notification plugin enabled (CrashLoopBackOff)

dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-cloud-dynamic/package.json, dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-server-dynamic/package.json, dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-dynamic/package.json, dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-org-dynamic/package.json, dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-org-dynamic/package.json, dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-msgraph-dynamic/package.json, dynamic-plugins/wrappers/backstage-plugin-notifications-backend-dynamic/package.json, dynamic-plugins/wrappers/backstage-plugin-notifications-backend-module-email-dynamic/package.json, dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-azure-dynamic/package.json, dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-bitbucket-cloud-dynamic/package.json, dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-bitbucket-server-dynamic/package.json, dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-gerrit-dynamic/package.json, dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-github-dynamic/package.json, dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-gitlab-dynamic/package.json, dynamic-plugins/wrappers/backstage-plugin-signals-backend-dynamic/package.json, dynamic-plugins/wrappers/backstage-plugin-signals/package.json, dynamic-plugins/wrappers/backstage-plugin-techdocs-backend-dynamic/package.json, dynamic-plugins/wrappers/backstage-plugin-techdocs/package.json, package.json, yarn.lock
Related to [PR changes](https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/pull/882).  We are pulling in newer BS plugins.  We need to rollback to 1.4.0 levels.
- Fixes #?
https://issues.redhat.com/browse/RHIDP-6086
=> chore: release-1.4: rollback bs scoped plugins to 1.4.0 levels

.ibm/pipelines/jobs/operator.sh
Based on: https://github.com/redhat-developer/rhdh-operator/blob/f186141100530856541a30b6696314064428dda8/.rhdh/scripts/install-rhdh-catalog-source.sh#L62-L64
- Fixes https://issues.redhat.com/browse/RHIDP-6085
=> chore(ci): use branch specific operator version for e2e

.ibm/pipelines/resources/config_map/dynamic-global-floating-action-button-config.yaml, .ibm/pipelines/resources/config_map/dynamic-homepage-and-sidebar-config.yaml, .ibm/pipelines/utils.sh, .ibm/pipelines/value_files/values_showcase.yaml, dynamic-plugins/_utils/src/wrappers.test.ts, e2e-tests/playwright/e2e/home-page-customization.spec.ts, e2e-tests/playwright/e2e/plugins/application-listener.spec.ts, e2e-tests/playwright/e2e/plugins/application-provider.spec.ts, e2e-tests/playwright/e2e/plugins/global-floating-button.spec.ts, e2e-tests/playwright/support/pageObjects/global-fab-po.ts, e2e-tests/playwright/support/pageObjects/page-obj.ts, e2e-tests/playwright/support/pages/home-page.ts
Added e2e tests for the global floating action button
- Fixes https://issues.redhat.com/browse/RHIDP-5845 , https://issues.redhat.com/browse/RHIDP-5400
To run the e2e tests successfully in your local:
Add the changes in the file `[dynamic-global-floating-action-button-config.yaml](https://github.com/redhat-developer/rhdh/pull/2405/files#diff-c872edf0bcd722091622844223e3e136c04a3aee0212ee6a806473205604c071)`
in your app-config
Start the app in one terminal
In another terminal, from `e2e-tests` path run 
-> `yarn showcase global-floating-button.spec.ts` 
-> `yarn showcase application-provider-listener.spec.ts`
=> chore(e2e-test): [Test automation] Verify global floating action button , application provider and listener

dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-cloud-dynamic/package.json, dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-server-dynamic/package.json, dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-dynamic/package.json, dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-org-dynamic/package.json, dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-org-dynamic/package.json, dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-msgraph-dynamic/package.json, dynamic-plugins/wrappers/backstage-plugin-notifications-backend-dynamic/package.json, dynamic-plugins/wrappers/backstage-plugin-notifications-backend-module-email-dynamic/package.json, dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-azure-dynamic/package.json, dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-bitbucket-cloud-dynamic/package.json, dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-bitbucket-server-dynamic/package.json, dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-gerrit-dynamic/package.json, dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-github-dynamic/package.json, dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-gitlab-dynamic/package.json, dynamic-plugins/wrappers/backstage-plugin-signals-backend-dynamic/package.json, dynamic-plugins/wrappers/backstage-plugin-signals/package.json, dynamic-plugins/wrappers/backstage-plugin-techdocs-backend-dynamic/package.json, dynamic-plugins/wrappers/backstage-plugin-techdocs/package.json, package.json, yarn.lock
Reverts redhat-developer/rhdh#2423 following [this thread](https://redhat-internal.slack.com/archives/C07EVRDD7KN/p1740499149568729?thread_ts=1739979127.163679&cid=C07EVRDD7KN).
=> chore: release-1.4: rollback bs scoped plugins to 1.4.0 levels - REVERT

docker/install-dynamic-plugins.py, docs/dynamic-plugins/installing-plugins.md
- Lock waiting status for dynamic plugins install script looks like:  "======= Waiting for lock release (file: /dynamic-plugins-root/install-dynamic-plugins.lock)..."
- Updated dynamic plugins install docs with reasons for SIGKILL signal.
https://issues.redhat.com/browse/RHIDP-6142
https://issues.redhat.com/browse/RHDHBUGS-135
=> chore: add SIGKILL note, add lock filename to log for waiting status

.ibm/pipelines/resources/config_map/app-config-rhdh.yaml, .ibm/pipelines/value_files/values_showcase-rbac.yaml, .ibm/pipelines/value_files/values_showcase.yaml, e2e-tests/playwright/e2e/audit-log/scaffold.spec.ts, e2e-tests/playwright/e2e/authProviders/basic-authentication.spec.ts, e2e-tests/playwright/e2e/authProviders/github-provider.spec.ts, e2e-tests/playwright/e2e/authProviders/microsoft-provider.spec.ts, e2e-tests/playwright/e2e/authProviders/rhsso-76-provider.spec.ts, e2e-tests/playwright/e2e/default-global-header.spec.ts, e2e-tests/playwright/e2e/github-happy-path.spec.ts, e2e-tests/playwright/e2e/google-signin-happy-path.spec.ts, e2e-tests/playwright/e2e/guest-signin-happy-path.spec.ts, e2e-tests/playwright/e2e/plugins/analytics/analytics-disabled-rbac.spec.ts, e2e-tests/playwright/e2e/plugins/dynamic-plugins-info/dynamic-plugins-info.spec.ts, e2e-tests/playwright/e2e/plugins/http-request.spec.ts, e2e-tests/playwright/e2e/plugins/kubernetes-actions/kubernetes-actions.spec.ts, e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts, e2e-tests/playwright/support/pages/bulk-import.ts, e2e-tests/playwright/utils/custom-theme/theme-verifier.ts, e2e-tests/playwright/utils/ui-helper.ts
Update e2e tests for global header.
Changes including:
1. enabled global-header plugin in "showcase-rabc" and "showcase" test values
2. added `support` field to the default configMap `app-config-rhdh.yaml`
3. enabled notifications plugins to as it's a default component in global header
4. added `appConfig` field to `upstream.backstage` config in order to test notification unread amount badge
5. replaced `openSidebar("Settings") with a new uiHelper function `goToSettingsPage()`
6. added `default-global-header.spec.ts`
7. updated `clickLink()` and `verifyLink()` in `uiHelper`
8. replaced `openSidebar("Create...")` with updated `clickLink({ ariaLabel: "Create..." })`
9. updated `getByPlaceholder("Search")` to `getByPlaceholder("Search", { exact: true })` so that it only specify the filter …
=> chore(e2e): add e2e tests for global header

e2e-tests/package.json, package.json, packages/app/src/build-metadata.json
=> chore: tagRelease.sh: bump to 1.3.6 in release-1.3 branch

packages/backend/package.json, yarn.lock
Updates the RBAC backend plugin to grab a few reported bug fixes for 1.5
- Fixes [RHIDP-4697](https://issues.redhat.com/browse/RHIDP-4697)
- Fixes [RHIDP-6180](https://issues.redhat.com/browse/RHIDP-6180)
- Fixes [RHIDP-6088](https://issues.redhat.com/browse/RHIDP-6088)
=> chore(rbac): update rbac backend plugin

plugins/dynamic-plugins-info/src/components/DynamicPluginsTable/DynamicPluginsTable.tsx
This change updates the dynamic-plugins-info UI logic to reflect that all plugins returned from the API being used are enabled, which fixes the problem where externally installed plugins were showing up as disabled in the UI.
- Fixes [RHIDP-5594](https://issues.redhat.com/browse/RHIDP-5594)
=> fix: show external plugins as enabled

.ibm/images/Dockerfile, .ibm/images/README
chore(deps): revert to using mcr.microsoft.com/playwright:v1.48.2-jammy to unblock 1.5 builds -- must stay on Node 20 ([RHIDP-6244](https://issues.redhat.com//browse/RHIDP-6244))
N/A
N/A
=> chore(deps): revert to using mcr.microsoft.com/playwright:v1.48.2-jammy to unblock 1.5 builds -- must stay on Node 20 (RHIDP-6244)

dynamic-plugins/wrappers/backstage-community-plugin-acr/package.json, dynamic-plugins/wrappers/backstage-community-plugin-jfrog-artifactory/package.json, dynamic-plugins/wrappers/backstage-community-plugin-nexus-repository-manager/package.json, dynamic-plugins/wrappers/backstage-community-plugin-ocm-backend-dynamic/package.json, dynamic-plugins/wrappers/backstage-community-plugin-quay/package.json, dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd/package.json, dynamic-plugins/wrappers/backstage-community-plugin-scaffolder-backend-module-kubernetes-dynamic/package.json, dynamic-plugins/wrappers/backstage-community-plugin-tekton/package.json, dynamic-plugins/wrappers/backstage-community-plugin-topology/package.json, e2e-tests/playwright/e2e/audit-log/scaffold.spec.ts, e2e-tests/playwright/e2e/plugins/topology/topology.spec.ts, packages/backend/package.json, yarn.lock
Update:
- @backstage-community/plugin-acr
- @backstage-community/plugin-jfrog-artifactory
- @backstage-community/plugin-nexus-repository-manager
- @backstage-community/plugin-quay
- @backstage-community/plugin-rbac
- @backstage-community/plugin-redhat-argocd
- @backstage-community/plugin-scaffolder-backend-module-kubernetes
- @backstage-community/plugin-tekton
- @backstage-community/plugin-topology
- @backstage-community/plugin-scaffolder-backend-module-annotator
Update plugins with newer @kubernetes/client-node or @kubernetes/client-node. Use newer @backstage-community/plugin-scaffolder-backend-module-annotator updated to backstage 1.35
- Fixes https://issues.redhat.com/browse/RHIDP-5721
- Fixes https://issues.redhat.com/browse/RHIDP-4744
Please make sure that the following steps are …
=> chore(deps): update plugins with new k8s-client, update plugin annotator

docs/e2e-tests/README.md, docs/e2e-tests/examples.md, docs/index.md
chore(docs): fix broken link to old 1.1 docs and other missing files
N/A
This is a fix for the mardown link tests: https://github.com/redhat-developer/rhdh/actions/runs/13683992706/job/38262912758?pr=2516
as surfaced by my PR for https://issues.redhat.com//browse/RHIDP-2028 in https://github.com/redhat-developer/rhdh/pull/2375/commits
N/A
=> chore(docs): fix broken link to old 1.1 docs and other missing files

.ibm/pipelines/value_files/values_showcase-auth-providers.yaml, e2e-tests/playwright/e2e/authProviders/rhsso-76-provider.spec.ts
Manual cherry-pick of https://github.com/redhat-developer/rhdh/pull/2451
=> [release-1.5] chore(e2e): add RHSSO sub claim resolvers to auth e2e tests

dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-catalog-backend-module-marketplace-dynamic/package.json, dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace/package.json, plugins/dynamic-plugins-info/app-config.dynamic.yaml, yarn.lock
Add new marketplace providers to automatically register all the marketplace plugins, packages on application startup. With this change, upgrading users or new users onboarding RHDH 1.5 does not require to add any configuration changes to see the default plugins in the Extensions tab.
- https://issues.redhat.com/browse/RHIDP-6299
=> fix(marketplace): bump catalog backend module for marketplace

.ibm/pipelines/openshift-ci-tests.sh, e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts, e2e-tests/playwright/utils/ui-helper.ts
Updated the "Next" and "Save" button clicks to use `{force: true}` in the RBAC Playwright test. This change addresses potential issues with element interactivity during test execution.
- Fixes #?
=> chore(e2e): rhidp-6330 Fix Failing E2E Test - Nightly - Rbac - Edit users and groups and update policies of a role from the overview page

packages/app/public/index.html, packages/app/src/components/AppBase/AppBase.tsx
fixes https://issues.redhat.com/browse/RHIDP-6015
- do not show janus favicons if a custom favicon is set, so that there are no issues with which favicon should take priority
- do not use the "Janus Community Showcase" metadata description if `app.title` is set
- move the favicon `ConfigUpdater`to outside the `AppRouter` component so that it can work in the `OauthRequestDialog`
before:
after:
the following shouldn't happen:
- the Janus favicon flashes momentarily before the custom one is set
- the Janus favicon apperas in the login screen
- the description metadata in the HTML is "Janus Community Showcase"  if `app.title` is set
=> fix(favicon): re-embed dynamic favicon into index.html

.dockerignore, .github/workflows/push-e2e-runner.yaml, .ibm/images/Dockerfile, .ibm/images/README, .ibm/pipelines/utils.sh
Switch Docker build context to project root and integrate `.yarnrc.yml` to specify Yarn version. Modify workflows and `.dockerignore` to accommodate the new build context and ensure `.yarnrc.yml` is included. Add error handling for Yarn installation in `utils.sh` to improve debugging.
- Fixes https://issues.redhat.com/browse/RHIDP-6351
=> chore(e2e): rhidp-6351 Update Dockerfile, workflows, and scripts for Yarn support

.ibm/pipelines/env_variables.sh, .ibm/pipelines/resources/config_map/app-config-rhdh-rbac.yaml, .ibm/pipelines/resources/config_map/rbac-policy.csv, .ibm/pipelines/value_files/values_showcase-rbac.yaml, catalog-entities/e2e-test-resources/rbac-transitive-parent-ownership.yaml, e2e-tests/playwright/data/rbac-constants.ts, e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
Adds e2e tests for `includeTransitiveGroupOwnership` config with RBAC
Test cases added:
- user apart of sub group can view component owned by parent group when `includeTransitiveGroupOwnership` is set to `true`
- Fixes [RHIDP-5955
](https://issues.redhat.com/browse/RHIDP-5955)
=> chore(e2e): add tests for includeTransitiveGroupOwnership config with RBAC

yarn.lock
Regenerated `yarn.lock` by running:
- `yarn install`
- `cd packages/app`
- `yarn remove @backstage/plugin-api-docs`
- `yarn add @backstage/plugin-api-docs@0.12.4` (same version reinstalled)
This picked up transitive dependency updates that resolve `node-gyp` build errors in `tree-sitter`
Refs: https://issues.redhat.com/browse/RHIDP-6288
=> chore(deps): reinstall @backstage/plugin-api-docs to fix node-gyp errors in tree-sitter

packages/app/src/components/Root/Root.tsx
- Modified Backstage SidebarItem styles to allow long menu item labels to wrap instead of being cut off.
- Refactored code to simplify the codebase and improve sidebar menu display, especially on smaller screens.
[Figma reference](https://www.figma.com/design/Gp6QQ0wtRO3RSCphRZIdjQ/RHDH-Theme?node-id=908-9509&p=f&t=8n10OTFioWinXaMl-0)
- Fixes [RHIDP-6010](https://issues.redhat.com/browse/RHIDP-6010)
=> fix(sidebar): wrap long menu item label in sidebar

yarn.lock
`cpu-features` is an optional transitive dependency required via `ssh2`:
https://github.com/mscdex/ssh2/blob/dd5510c0888476e9eec205273732473fcce5adc6/package.json#L18-L21
This change is the most minimal way to adopt the transitive dependency update to fix the `node-gyp` errors. It was achieved by removing the `cpu-features` from the `yarn.lock` and rerunning a regular `yarn install` to pick up the later version.
Note we should separately consider a wider regeneration of the `yarn lock` on the main branch as we're missing quite a few transitive updates that are now available. 
- Fixes: [RHIDP-6288](https://issues.redhat.com/browse/RHIDP-6288)
=> chore: force transitive update of cpu-features

.github/actions/get-sha/action.yml, .ibm/pipelines/resources/config_map/app-config-rhdh.yaml, .rhdh/docker/Dockerfile, docker/Dockerfile, docs/customization.md, e2e-tests/playwright/e2e/plugins/user-settings-info-card.spec.ts, packages/app/config.d.ts, packages/app/src/build-metadata.json, packages/app/src/components/UserSettings/InfoCard.test.tsx, packages/app/src/components/UserSettings/InfoCard.tsx, packages/app/src/types/types.ts, scripts/update-metadata.mjs
- Allowing users to specify their customized build info via app-config
- Customized build shows first 2 information when collapsed
- Fallbacks to build-metadata.json content when customization is not available
- Fixes https://issues.redhat.com/browse/RHIDP-5213
Add the following snippet in your app-config.yaml file
```
buildInfo:
title: 'RHDH Build info'
card:
TechDocs builder: 'local'
Authentication provider: 'Github'
RBAC: disabled
```
=> feat(user-settings): allow overriding build info in the user settings page

packages/backend/src/modules/authProvidersModule.ts, packages/backend/src/modules/authResolvers.ts
Add `oauth2ProxyUserHeaderMatchingUserEntityName` auth resolver to restore previous functionality that was not preserved in [this PR](https://github.com/redhat-developer/rhdh/pull/2354).
- Fixes [RHIDP-6380](https://issues.redhat.com/browse/RHIDP-6380)
=> fix: add oauth2ProxyUserHeaderMatchingUserEntityName auth resolver

dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace/package.json, dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace/src/index.ts, yarn.lock
Will update screenshots when a container image is available.
| Currently the extensions drawer looks like this | It should look like this |
| --- | --- |
| ![Screenshot from 2025-03-14 12-18-14](https://github.com/user-attachments/assets/ee52a130-b04e-42be-8778-00b046b7c2da) | ![Screenshot from 2025-03-14 12-06-50](https://github.com/user-attachments/assets/b7135b8f-fcc9-4eec-a87f-a977ed2c62e0) |
| RHDH Version: 1.5.0<br>Backstage Version: 1.35.1<br>Upstream: rhdh release-1.5 @ 2d7b8127<br>Midstream: rhdh rhdh-1.5-rhel-9 @ 04c0d061<br>Build Time: 2025-03-12T08:35:41Z | localhost, how it should look like<br><br>Will update screenshots when a container image is available. |
- Fixes https://issues.redhat.com/browse/RHIDP-6411
Test …
=> [release-1.5] fix(marketplace): add MUI v5 workaround to marketplace wrapper, similar to other plugins

dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd/package.json, dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd-backend-dynamic/package.json, dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd-backend-dynamic/src/index.ts, yarn.lock
The newer versions of these plugins include a feature that supports multi-source applications.
Here are the related PRs:
- https://github.com/backstage/community-plugins/pull/2941
- https://github.com/RoadieHQ/roadie-backstage-plugins/pull/1842
- Fixes [RHTAP-4505](https://issues.redhat.com/browse/RHTAP-4505)
=> chore(argocd): update Red Hat and RoadieHQ wrappers

catalog-entities/marketplace/plugins/3scale.yaml, catalog-entities/marketplace/plugins/ansible-plugin.yaml, catalog-entities/marketplace/plugins/azure-container-registry.yaml, catalog-entities/marketplace/plugins/azure-repositories.yaml, catalog-entities/marketplace/plugins/backstage-community-plugin-quay.yaml, catalog-entities/marketplace/plugins/datadog.yaml, catalog-entities/marketplace/plugins/extensions.yaml, catalog-entities/marketplace/plugins/github-issues.yaml, catalog-entities/marketplace/plugins/github-pull-requests.yaml, catalog-entities/marketplace/plugins/github-scaffolder-actions.yaml, catalog-entities/marketplace/plugins/jira.yaml, catalog-entities/marketplace/plugins/ldap-catalog-integration.yaml, catalog-entities/marketplace/plugins/lighthouse.yaml, catalog-entities/marketplace/plugins/nexus-repository-manager.yaml, catalog-entities/marketplace/plugins/openshift-cluster-manager.yaml, catalog-entities/marketplace/plugins/roadie-argocd.yaml, catalog-entities/marketplace/plugins/topology.yaml
Using the CSV created by Jackson Lee, I was able to spot a number of minor inconsistencies and missing data items in the various YAML files used to provide content to the RHDH Extensions Catalog plugin.
One notable change is that the Azure Container Registry plugin had it's support level changed from production down to tech-preview. To the best of mu knowledge based on the data I have this is correct, but you would be wise to double check this with the build manager and product owner.
=> chore(marketplace): various catalog metadata fixes

catalog-entities/marketplace/plugins/datadog.yaml, catalog-entities/marketplace/plugins/extensions.yaml, catalog-entities/marketplace/plugins/lighthouse.yaml, catalog-entities/marketplace/plugins/openshift-cluster-manager.yaml
Without this change the datadog, lighthouse and OpenShift cluster Manager wasn't displayed because the YAML doesn't match the JSON schema.
Before:
After:
- Fixes #?
=> chore(marketplace): convert categories to an array to restore missing plugins

.ibm/pipelines/openshift-ci-tests.sh
Removes a wrong variable override in the e2e job setup phase causing the ci to fail for multiple jobs.
- Fixes [RHIDP-6695](https://issues.redhat.com/browse/RHIDP-6695)
=> chore(e2e): remove wrong JOB_NAME override in openshift-ci-tests.sh

dynamic-plugins/wrappers/backstage-community-plugin-acr/package.json, yarn.lock
Update wrapper for  @backstage-community/plugin-acr , based on backstage 1.36.1 upgrade
Have verified the changes with the image [quay.io/rhdh-community/rhdh:pr-2667](https://quay.io/rhdh-community/rhdh:pr-2667)
- Fixes 
https://issues.redhat.com/browse/RHIDP-6514
=> chore(deps): update acr with backstage 1.36.1 upgrade

yarn.lock
chore(deps): bump to latest tar-fs 3.0.8 and 2.1.2 ([RHIDP-6744](https://issues.redhat.com//browse/RHIDP-6744)) (CVE-2024-12905)
N/A
N/A
=> chore(deps): bump to latest tar-fs 3.0.8 and 2.1.2 (RHIDP-6744) (CVE-2024-12905)

yarn.lock
Update the dockerode and tar-fs dependencies to fix CVE-2024-12905
1.  yarn up -R dockerode to bump to v4.0.5 which has an updated tar-fs dependency (~2.1.2)
2.  yarn up -R tar-fs to bump to the latest patched versions
There's still an older version of tar-fs after these updates but it's caused by 
└─ testcontainers@npm:10.8.1
└─ dockerode@npm:3.3.5 (via npm:^3.3.5)
which is a depdendency of @backstage/backend-test-utils which is a dev dependency
- Fixes #?
https://issues.redhat.com/browse/RHIDP-6748
=> chore: release-1.5: fix CVE-2024-12905

packages/app/src/build-metadata.json
chore: fix version in packages/app/src/build-metadata.json (also updated tagRelease.sh sp this won't happen again for 1.6.1 and 1.7.1)
N/A
related to downstream script update: https://gitlab.cee.redhat.com/rhidp/rhdh/-/commit/8e71345160a47e437dc5cac585cfdae88b170980
N/A
=> chore: fix version in packages/app/src/build-metadata.json (also updated tagRelease.sh sp this won't happen again for 1.6.1 and 1.7.1)

e2e-tests/playwright/e2e/authProviders/rhsso-76-provider.spec.ts, packages/backend/src/modules/authProvidersModule.ts, packages/backend/src/modules/authResolvers.ts
Sets the default OIDC default resolver to resolve by the `sub` claim
- This sub claim is more stable and secure compared parameters used by existing resolvers that are based on mutable values (like user name and email) 
- This PR makes it so that the OIDC sign in flow is more secure by default
- If the user wants to preserve the previous default resolver `emailLocalPartMatchingUserEntityName`, they can still declaratively set this in the `app-config` like: 
```
signIn:
resolvers:
- resolver: emailLocalPartMatchingUserEntityName
```
To accommodate multiple OIDC providers, I created the `oidcSubClaimMatchingIdPUserId` resolver (to be used only in the code, unavailable to customers) that tries both Ping Identity and Keycloak providers. This is done since only 1 resolver is allowed to be …
=> chore: set default OIDC default resolver to resolve by sub claim

dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace/package.json, dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace/src/index.ts, yarn.lock
Will update screenshots when a container image is available.
| Currently the extensions drawer looks like this | It should look like this |
| --- | --- |
| ![Screenshot from 2025-03-14 12-06-29](https://github.com/user-attachments/assets/45038429-35f3-4a2b-9cf4-52689f16f1e0) | ![Screenshot from 2025-03-14 12-06-50](https://github.com/user-attachments/assets/b7135b8f-fcc9-4eec-a87f-a977ed2c62e0) |
| RHDH Version: 1.6.0<br>Backstage Version: 1.35.1<br>Upstream: rhdh main @ 2a9a4645<br>Midstream: rhdh-1-rhel-9 @ fcde362a<br>Build Time: 2025-03-14T01:25:32Z | localhost, how it should look like<br><br>Will update screenshots when a container image is available. |
- Fixes https://issues.redhat.com/browse/RHIDP-6411
Test marketplace on a …
=> fix(marketplace): add MUI v5 workaround to marketplace wrapper, similar to other plugins

.rhdh/docker/Dockerfile
re-enable the cleanup step in dynamic-plugins folder (purge all but dist/ folders) [RHIDP-6868](https://issues.redhat.com//browse/RHIDP-6868)
N/A
N/A
=> chore(cachi2): re-enable the cleanup step in dynamic-plugins folder (purge all but dist/ folders) RHIDP-6868

dynamic-plugins/wrappers/backstage-community-plugin-jfrog-artifactory/package.json, yarn.lock
Updating the `jfrog-artifactory` version to latest version include changes arises due to  
[PR-3514]( https://github.com/backstage/community-plugins/pull/3514) which resolves
1. https://issues.redhat.com/browse/RHIDP-6528
2. https://issues.redhat.com/browse/RHIDP-6757
=> chore(jfrog-artifactory): update package version

.ibm/pipelines/resources/config_map/app-config-rhdh-rbac.yaml, .ibm/pipelines/resources/config_map/app-config-rhdh.yaml
Set the oidc.signin.resolvers in app-config for test deployments (non-RBAC and RBAC) to fix Keycloak login AKS test failures (and occasional GKE failures).
The OIDC auth provider is thoroughly tested in the `auth-providers` scenario. See https://github.com/redhat-developer/rhdh/pull/2694
Fix already verified at https://github.com/redhat-developer/rhdh/pull/2712, see https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/redhat-developer_rhdh/2712/pull-ci-redhat-developer-rhdh-main-e2e-tests-aks-helm-nightly/1909903716522135552/artifacts/e2e-tests-aks-helm-nightly/redhat-developer-rhdh-aks-helm-nightly/artifacts/showcase-k8s-ci-nightly/index.html
- Fixes https://issues.redhat.com/browse/RHIDP-6913 
=> chore(e2e): set keycloak signIn resolver on deployments

.rhdh/docker/Dockerfile, scripts/update-Dockerfile.sh
chore(dockerfile, e2e-tests): exclude e2e-tests folder from .rhdh downstream dockerfile ([RHIDP-6868](https://issues.redhat.com//browse/RHIDP-6868))
Must keep e2e-tests folder in upstream or else PR check builds will fail because the yarn lock is outdated. 
N/A
N/A
=> chore(e2e-tests): exclude e2e-tests folder from .rhdh dockerfile (RHIDP-6868)

.rhdh/docker/Dockerfile, docker/Dockerfile
chore(headers): include node 22.14.0 headers for use with node-gyp offline ([RHIDP-6868](https://issues.redhat.com//browse/RHIDP-6868))
N/A
N/A
=> chore(headers): include node 22.14.0 headers for use with node-gyp offline (RHIDP-6868)

.rhdh/docker/Dockerfile, docker/Dockerfile
chore: suppress pointless warning about existing dir
N/A
Cleans up this warning:
```
[5/5] STEP 15/27: RUN mkdir /opt/app-root/src/.npm; chown -R 1001:1001 /opt/app-root/src/.npm; 
mkdir: cannot create directory '/opt/app-root/src/.npm': File exists
```
N/A
=> chore: suppress pointless warning about existing dir; also remove trailing whitespace

yarn.lock
Manually downgrade/resolve a duplicated dependency to @backstage/plugin-catalog in yarn.lock.
Dependencies before:
```
find . -iname plugin-catalog | xargs -i sh -c 'echo {}; jq .version {}/package.json' 	 
./node_modules/@backstage/plugin-catalog
"1.27.0"
./node_modules/@backstage/plugin-api-docs/node_modules/@backstage/plugin-catalog
"1.28.0"
./node_modules/@backstage-community/plugin-rbac/node_modules/@backstage/plugin-catalog
"1.28.0"
```
With this change:
```
find . -iname plugin-catalog | xargs -i sh -c 'echo {}; jq .version {}/package.json'
./node_modules/@backstage/plugin-catalog
"1.27.0"
```
- Fixes https://issues.redhat.com/browse/RHIDP-6975
Just run the container image and click in the sidebar on APIs.
=> fix(api-docs): use plugin-catalog from backstage 1.36.1

.ibm/pipelines/env_variables.sh, .ibm/pipelines/resources/config_map/rbac-policy.csv, .ibm/pipelines/value_files/values_showcase-rbac.yaml, e2e-tests/playwright.config.ts, e2e-tests/playwright/data/rbac-constants.ts, e2e-tests/playwright/e2e/plugins/kubernetes/kubernetes-rbac.spec.ts, e2e-tests/playwright/support/pageObjects/page-obj.ts, e2e-tests/playwright/support/pages/kubernetes.ts
Adds e2e tests for the kubernetes plugin. These tests mainly focus on the newly added kubernetes permissions `kubernetes.clusters.read` and `kubernetes.resources.read`
- Fixes [RHIDP-6387](https://issues.redhat.com/browse/RHIDP-6387)
=> chore(e2e): add tests for rbac tests for the kubernetes plugin

catalog-entities/marketplace/packages/backstage-community-plugin-azure-devops-backend.yaml, catalog-entities/marketplace/packages/backstage-community-plugin-azure-devops.yaml, catalog-entities/marketplace/packages/backstage-community-plugin-catalog-backend-module-keycloak.yaml, catalog-entities/marketplace/packages/backstage-community-plugin-catalog-backend-module-pingidentity.yaml, catalog-entities/marketplace/packages/backstage-community-plugin-dynatrace.yaml, catalog-entities/marketplace/packages/backstage-community-plugin-github-actions.yaml, catalog-entities/marketplace/packages/backstage-community-plugin-github-issues.yaml, catalog-entities/marketplace/packages/backstage-community-plugin-jenkins-backend.yaml, catalog-entities/marketplace/packages/backstage-community-plugin-jenkins.yaml, catalog-entities/marketplace/packages/backstage-community-plugin-lighthouse.yaml, catalog-entities/marketplace/packages/backstage-community-plugin-scaffolder-backend-module-quay.yaml, catalog-entities/marketplace/packages/backstage-community-plugin-sonarqube-backend.yaml, catalog-entities/marketplace/packages/backstage-community-plugin-sonarqube.yaml, catalog-entities/marketplace/packages/backstage-community-plugin-tech-radar-backend.yaml, catalog-entities/marketplace/packages/backstage-community-plugin-tech-radar.yaml, catalog-entities/marketplace/packages/immobiliarelabs-backstage-plugin-gitlab-backend.yaml, catalog-entities/marketplace/packages/immobiliarelabs-backstage-plugin-gitlab.yaml, catalog-entities/marketplace/packages/red-hat-developer-hub-backstage-plugin-catalog-backend-module-m.yaml, catalog-entities/marketplace/packages/red-hat-developer-hub-backstage-plugin-global-floating-action-b.yaml, catalog-entities/marketplace/packages/red-hat-developer-hub-backstage-plugin-marketplace-backend.yaml, catalog-entities/marketplace/packages/red-hat-developer-hub-backstage-plugin-marketplace.yaml, catalog-entities/marketplace/packages/roadiehq-backstage-plugin-argo-cd.yaml, catalog-entities/marketplace/packages/roadiehq-backstage-plugin-datadog.yaml, catalog-entities/marketplace/packages/roadiehq-backstage-plugin-github-insights.yaml, catalog-entities/marketplace/packages/roadiehq-backstage-plugin-github-pull-requests.yaml, catalog-entities/marketplace/packages/roadiehq-backstage-plugin-jira.yaml, catalog-entities/marketplace/packages/roadiehq-backstage-plugin-security-insights.yaml, catalog-entities/marketplace/packages/roadiehq-scaffolder-backend-argocd.yaml, catalog-entities/marketplace/packages/roadiehq-scaffolder-backend-module-http-request.yaml, catalog-entities/marketplace/packages/roadiehq-scaffolder-backend-module-utils.yaml
Manual backport or similar to #2776 and #2777 -- but I run the generate command again instead of just backporting the changes to ensure it's aligned with the included packages.
---
This updates the included version informations that are shown in the extensions UI.
I regenerated the package yamls with:
```
rm -rf catalog-entities/marketplace/packages
npx -y @red-hat-developer-hub/marketplace-cli generate --namespace rhdh -p dynamic-plugins.default.yaml -o catalog-entities/marketplace/packages
```
And ignored this changes because these contains manual changes:
```
modified:   catalog-entities/marketplace/packages/all.yaml
deleted:    catalog-entities/marketplace/packages/dynatrace-backstage-plugin-dql-backend.yaml
deleted:    catalog-entities/marketplace/packages/dynatrace-backstage-plugin-d …
```
=> [release-1.5] fix(extensions): update package version strings displayed in extensions ui

dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace-backend-dynamic/package.json, yarn.lock
chore(deps): add missing dependency from backstage-plugin-marketplace-backend 0.3 to backstage-plugin-marketplace-common 0.3.0
N/A
[RHIDP-6964](https://issues.redhat.com//browse/RHIDP-6964)
This is the first of 3 PRs:
* fix deps - this PR: https://github.com/redhat-developer/rhdh/pull/2801
* adjust Dockerfiles to do all the dynamic plugin builds at the start instead of in multiple steps (as per https://gitlab.cee.redhat.com/rhidp/rhdh/-/merge_requests/233/) - https://github.com/redhat-developer/rhdh/pull/2803
* remove --no-install flags from downstream dynamic plugin package.json files - https://gitlab.cee.redhat.com/rhidp/rhdh/-/merge_requests/234/diffs
1. Merge all three changes. 
2. Trigger a new gitlab pipeline to pull in the upstream …
=> chore(deps): add missing dependency from backstage-plugin-marketplace-backend 0.3 to backstage-plugin-marketplace-common 0.3.0 (RHIDP-6964) [main]

.rhdh/docker/Dockerfile, docker/Dockerfile
chore(docker): update dockerfiles based on Stan's fix and Tomas' validation in https://gitlab.cee.redhat.com/rhidp/rhdh/-/merge_requests/229 and https://gitlab.cee.redhat.com/rhidp/rhdh/-/merge_requests/233 ([RHIDP-6964](https://issues.redhat.com//browse/RHIDP-6964))
N/A
[RHIDP-6964](https://issues.redhat.com//browse/RHIDP-6964)
This is the 2nd of 3 PRs:
* fix deps - https://github.com/redhat-developer/rhdh/pull/2801
* adjust Dockerfiles to do all the dynamic plugin builds at the start instead of in multiple steps (as per https://gitlab.cee.redhat.com/rhidp/rhdh/-/merge_requests/233/) - this PR #2803
* remove --no-install flags from downstream dynamic plugin package.json files - https://gitlab.cee.redhat.com/rhidp/rhdh/-/merge_requests/234/diff …
=> chore(docker): update dockerfiles based on Stan's fix and Tomas' validation - RHIDP-6964 [main]

.rhdh/docker/Dockerfile, docker/Dockerfile
chore(docker): update dockerfiles based on Stan's fix and Tomas' validation in https://gitlab.cee.redhat.com/rhidp/rhdh/-/merge_requests/229 and https://gitlab.cee.redhat.com/rhidp/rhdh/-/merge_requests/233 ([RHIDP-6964](https://issues.redhat.com//browse/RHIDP-6964))
N/A
[RHIDP-6964](https://issues.redhat.com//browse/RHIDP-6964)
This is the 2nd of 3 PRs:
* fix deps - https://github.com/redhat-developer/rhdh/pull/2802
* adjust Dockerfiles to do all the dynamic plugin builds at the start instead of in multiple steps (as per https://gitlab.cee.redhat.com/rhidp/rhdh/-/merge_requests/233/) - this PR #2804
* remove --no-install flags from downstream dynamic plugin package.json files - https://gitlab.cee.redhat.com/rhidp/rhdh/-/merge_requests/234/diff …
=> chore(docker): update dockerfiles based on Stan's fix and Tomas' validation - RHIDP-6964 [release-1.6]

e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts, e2e-tests/playwright/support/api/rbac-api.ts, e2e-tests/playwright/support/pageObjects/rbac-po.ts
Adds e2e tests for the `IsOwner` conditional rule that has been added to the RBAC plugins. Dependent on #2765 to merge and an image to be built before this can be merged
- Fixes [RHIDP-6616](https://issues.redhat.com//browse/RHIDP-6616)
=> chore(e2e): introduce tests for conditional rule isOwner

packages/app/src/components/UserSettings/SettingsPages.tsx
Add missing OIDC tile to Settings > Auth Providers Tab
- Fixes #?
https://issues.redhat.com/browse/RHIDP-6468
* Set up Keycloak with OIDC + test user
* Configure OIDC auth 
* Configure Keycloak plugin to sync test user
* In dev environment, run "yarn start"
* Login to localhost:7007 with test user credentials
* Navigate to Settings > Authentication Providers to verify OIDC tile exists
=> chore(fix): add OIDC to auth provider tab

packages/app/src/App.tsx, packages/app/src/components/Root/Root.tsx
For [RHIDP-7492](https://issues.redhat.com/browse/RHIDP-7492)
When integrating the `global-header` plugin into RHDH, we originally supported only the `above-main-content` layout. The `above-sidebar` position wasn't accounted for in our layout, and our sidebar is fixed at `top: 0` via the Backstage SidePage component (`.BackstageSidebar-drawer` class). This causes it to overlap with any content rendered above it.
This PR uses a `ResizeObserver` inside a `useLayoutEffect` to measure the total height of headers rendered in the `above-sidebar` position, and adjusts the sidebar’s top value accordingly. This ensures the sidebar no longer overlaps the global headers.
We’re aware that `useLayoutEffect` and unthrottled `ResizeObserver` may impact performance in edge cases. We’re open to …
=> fix(global-header): enable above-sidebar header position

.github/workflows/pr-build-image.yaml
This PR temporarily disables the PR build workflow for the release-1.6 branch while we complete testing for release 1.6.1 RC.
Changes made:
- Added `branches-ignore` configuration to skip PR builds targeting the release-1.6 branch
- This is a temporary measure and should be reverted after release 1.6.1 RC testing is completed
- Fixes #?
=> chore(ci): temporarily disable PR build workflow for release-1.6 branch

.github/actions/check-image-and-changes/action.yaml, .github/workflows/pr-build-image.yaml
This PR introduces a new feature to skip the image build step using a commit message tag.
Changes:
- Added support for `[skip-build]` tag in commit messages to skip the image build step
- Removed branch-based skip configuration in favor of a more flexible tag-based approach
- Build will be skipped if the commit message contains `[skip-build]` anywhere in the message
Example usage:
```git commit -m "feat: update e2e tests [skip-build]"```
This change provides more flexibility by:
- Allowing build skipping on any branch when needed
- Making the skip intention explicit in git history
- Enabling easy toggling of build skipping without branch changes
Note: The e2e tests will still run even when the build is skipped.
- Fixes #?
=> feat(ci): add [skip-build] tag support to bypass image build

.github/actions/check-image-and-changes/action.yaml, .github/workflows/pr-build-image.yaml, .github/workflows/pr.yaml
This PR introduces a new feature to skip the image build step using a commit message tag.
Changes:
* Added support for `[skip-build]` tag in commit messages to skip the image build step
* Added `is_skipped` output to the check-image-and-changes action
* Updated build skip logic to prevent unnecessary builds and comments
* Build will be skipped if the commit message contains `[skip-build]` anywhere in the message
Example usage:  
`git commit -m "feat: update e2e tests [skip-build]"`
This change provides more flexibility by:
* Allowing build skipping on any branch when needed
* Making the skip intention explicit in git history
* Enabling easy toggling of build skipping without branch changes
* Preventing unnecessary comments on PRs when build is skipped
Note: The e2e tests will still run …
=> feat(build): add support for [skip-build] tag to conditionally skip builds

.ibm/pipelines/env_variables.sh, .ibm/pipelines/resources/config_map/rbac-policy.csv, .ibm/pipelines/value_files/values_showcase-rbac.yaml, e2e-tests/playwright.config.ts, e2e-tests/playwright/data/rbac-constants.ts, e2e-tests/playwright/e2e/plugins/kubernetes/kubernetes-rbac.spec.ts, e2e-tests/playwright/support/pageObjects/page-obj.ts, e2e-tests/playwright/support/pages/kubernetes.ts
Adds e2e tests for the kubernetes plugin. These tests mainly focus on the newly added kubernetes permissions `kubernetes.clusters.read` and `kubernetes.resources.read`
- Fixes [RHIDP-6387](https://issues.redhat.com/browse/RHIDP-6387)
This is a manual cherry pick of #2697 as the e2e tests are currently failing on the main branch
=> [release-1.6] chore(e2e): add tests for rbac tests for the kubernetes plugin

.ibm/pipelines/resources/rhdh-operator/rhdh-start.yaml, e2e-tests/playwright/e2e/plugins/kubernetes-actions/kubernetes-actions.spec.ts, e2e-tests/playwright/e2e/plugins/ocm.spec.ts, e2e-tests/playwright/e2e/plugins/topology/topology.spec.ts
rh-pre-commit.version: 2.3.2
rh-pre-commit.check-secrets: ENABLED
The operator nightly tests are currently skipping the kubernetes-actions, topology, and OCM tests. This PR fixes the issue that caused them to be disabled and enables them.
- Fixes [RHIDP-7788](https://issues.redhat.com//browse/RHIDP-7788)
=> fix(e2e): add NODE_TLS_REJECT_UNAUTHORIZED env var in operator test config to re-enable topology, Kubernetes-actions, and OCM tests

packages/backend/src/modules/rhdhSignInResolvers.ts
The key for the UUID claim varies for different IAM setups and it's not convenient or possible for some customers to change this key. It's better to make this configurable on our end. 
**In Keycloak, the `ldapUuidKey` needs to match the `Token Claim Name` of the mapper in the client scope.**
The key is `ldap_uuid` by default.
To use this config:
```
development:
...
signIn:
resolvers:
- resolver: oidcLdapUuidMatchingAnnotation
ldapUuidKey: ldap_uuid
``` 
In this case, the claim key name coming from the IdP that contains the LDAP UUID value is named ldap_uuid.
```
Login failed; caused by Error: The user profile from LDAP is missing the UUID, likely due to a misconfiguration in the provider. Please contact your system administrator for assistance.
```
* This error likely indicates that the …
=> feat: make UUID claim key in oidcLdapUuidMatchingAnnotation resolver configurable

plugins/dynamic-plugins-info-backend/src/service/router.ts, plugins/dynamic-plugins-info/src/components/InternalPluginsMap.ts
Allow service to call `/loaded-plugins` endpoint. Needed for https://github.com/redhat-developer/rhdh-plugins/pull/995, for now we are using this endpoint as opposed to directly calling pluginProvider.
Add missing`backstage-plugin-techdocs-module-addons-contrib` package that is preconfigured.
- Fixes https://issues.redhat.com/browse/RHIDP-7855
=> fix(extensions): allow service to call /loaded-plugins

.ibm/pipelines/cluster/ibm/create-openshift-cluster.sh
This PR introduces a shell script to automate the creation of OpenShift clusters on IBM Cloud, allowing selection of region, zone, machine flavor, and OpenShift version interactively.
The script also automatically applies default resource tags (e.g., app-code, service-phase, cost-center) after the cluster is created.
🔗 Script location:
[create-openshift-cluster.sh](https://github.com/redhat-developer/rhdh/compare/.ibm/pipelines/cluster/ibm/create-openshift-cluster.sh)
- Fixes https://issues.redhat.com/browse/RHIDP-8040
Example output
```
Available Zones:
[1] us-south-1
[2] us-south-2
[3] us-south-3
Choose a zone (1-3):
Available Flavors:
[1] bx2.16x64
[2] cx2.8x16
[3] mx2.4x32
Choose a flavor (1-3):
...
Creating cluster 'my-cluster' in zone us-south-1 with flavor bx2.16x64 and version …
```
=> chore: rhidp-8040 Automate IBM Cloud OpenShift Cluster Creation with Tagging Support

catalog-entities/marketplace/packages/backstage-community-plugin-catalog-backend-module-keycloak.yaml, dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-keycloak-dynamic/package.json, dynamic-plugins/yarn.lock, e2e-tests/playwright/e2e/authProviders/oidc.spec.ts
Pulls in [patch change to add `sanitize[User/Group]NameTransformer`](https://github.com/backstage/community-plugins/pull/4369) in Keycloak plugin
* Adds e2e test to cover this use case
- Fixes [RHDHBUGS-348](https://issues.redhat.com/browse/RHDHBUGS-348)
Try to ingest Keycloak groups and users with `@` in their user/groups ID
=> chore: bump keycloak plugin version and test sanitize[User/Group]NameTransformer

dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-adoption-insights-backend-dynamic/package.json, dynamic-plugins/yarn.lock
This PR bumps `@red-hat-developer-hub/backstage-plugin-adoption-insights-backend` plugin version.
- Fixes
https://issues.redhat.com/browse/RHDHPAI-941
=> chore(deps): bump adoptions insights backend plugin

packages/app/src/components/ErrorPages/ErrorPage.tsx, packages/app/src/components/ErrorPages/NotFoundErrorPage.tsx, packages/app/src/components/ErrorPages/errorButtons/ContactSupportButton.tsx
part of the implementation for https://issues.redhat.com/browse/RHIDP-7509
updates `ErrorPage` components that are compatible with the equivalent from `@backstage/core-components`, so that we can customize these to our brand
this is how the 404 page looks now i.e., (unchanged):
=> feat: update our `ErrorPage` props to match Backstage props

catalog-entities/marketplace/packages/backstage-community-plugin-tech-radar.yaml, catalog-entities/marketplace/packages/immobiliarelabs-backstage-plugin-gitlab.yaml, catalog-entities/marketplace/packages/roadiehq-scaffolder-backend-module-http-request.yaml, dynamic-plugins/wrappers/backstage-community-plugin-tech-radar/package.json, dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab/package.json, dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-http-request-dynamic/package.json, dynamic-plugins/yarn.lock
Bumps some more of the plugin versions to their recent .z releases. Skips the core backstage plugins as those were bumped as part of the Backstage 1.40.0 release
- Fixes [RHIDP-8117](https://issues.redhat.com/browse/RHIDP-8117)
=> chore(deps): bump wrappers to latest .z plugin versions

.github/workflows/next-build-image.yaml
chore(release): use labels instead of imageLabels because all GH actions use slightly different syntax, ffs ([RHIDP-8172](https://issues.redhat.com//browse/RHIDP-8172))
N/A
https://issues.redhat.com/browse/RHIDP-8172
N/A
=> chore(release): use labels instead of imageLabels because all GH actions use slightly different syntax, ffs (RHIDP-8172)

packages/app-next/package.json
This change fixes the app-next ability to load frontend dynamic plugins properly by ensuring the EXPERIMENTAL_MODULE_FEDERATION environment variable is set to "true" when the package is built.
A followup of [RHIDP-6880](https://issues.redhat.com/browse/RHIDP-6880)
=> fix(app-next): fix app-next dynamic plugin loading

dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-dynamic-home-page/package.json, dynamic-plugins/yarn.lock
Update Homepage wrapper
https://issues.redhat.com/browse/RHDHBUGS-1903
https://github.com/user-attachments/assets/dc2b57fa-f597-40e8-96bf-26e2398db7a3
1. Add `Top Visited` and `Recent Visited` Card in homepage by adding below config. You can set custom home page title (visible on the home page) from here. 
```
rootDirectory: dynamic-plugins-root
frontend:
red-hat-developer-hub.backstage-plugin-dynamic-home-page:
dynamicRoutes:
- path: /
importName: DynamicHomePage
config:
props:
title: ''Custom Title"
mountPoints:
- mountPoint: application/listener
importName: VisitListener
- mountPoint: home.page/cards
importName: RecentlyVisitedCard
config:
layouts:
xl: { w: 6, h: 4, x: 6 }
lg: { w: 6, h: 4, x: 6 }
md: { w: 6, h: 4, x: 6 }
sm: { w: 6, h: 4, x: 6 }
xs: { w: 6, h: 4, x: 6 …
```
=> chore(homepage): update homepage version

.ibm/pipelines/cluster/eks/aws.sh, .ibm/pipelines/cluster/eks/eks-helm-deployment.sh, .ibm/pipelines/cluster/gke/gcloud.sh, .ibm/pipelines/env_variables.sh, .ibm/pipelines/jobs/eks-helm.sh, .ibm/pipelines/jobs/eks-operator.sh, .ibm/pipelines/openshift-ci-tests.sh, .ibm/pipelines/resources/config_map/app-config-rhdh-rbac.yaml, .ibm/pipelines/utils.sh, .ibm/pipelines/value_files/diff-values_showcase-rbac_EKS.yaml
- Change EKS e2e to use AWS DNS and a dynamically assigned domain name, instead of mocking.
- Fail when no handle is matched in `openshift-ci-tests.sh`
- Improve checking `if Backstage is up and running` to fail fast with CrashLoopBackOff
- Fixes [issues.redhat.com/browse/RHIDP-4555](https://issues.redhat.com/browse/RHIDP-4555) and [issues.redhat.com/browse/RHIDP-734](https://issues.redhat.com/browse/RHIDP-734)
=> chore(ci): enhance EKS e2e to use AWS DNS

catalog-entities/marketplace/packages/red-hat-developer-hub-backstage-plugin-catalog-backend-module-m.yaml, catalog-entities/marketplace/packages/red-hat-developer-hub-backstage-plugin-marketplace-backend.yaml, catalog-entities/marketplace/packages/red-hat-developer-hub-backstage-plugin-marketplace.yaml, dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-catalog-backend-module-marketplace-dynamic/package.json, dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace-backend-dynamic/package.json, dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace/package.json, dynamic-plugins/yarn.lock
Updates extensions wrappers
- 78b2f53: hide extensions alerts while the plugins are still loading
- fb23720: Introduce `spec.integrity` field for Marketplace package
- 7aa3823: Restrict access to configuration endpoints in production
=> chore(deps): update extensions wrappers

dynamic-plugins/wrappers/backstage-community-plugin-rbac/package.json, dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-quickstart/package.json, dynamic-plugins/yarn.lock
This PR updates the RBAC plugin wrapper to version `1.42.1`.
- [Added optional pagination support to getMembers API
](https://github.com/backstage/community-plugins/commit/a2e5d4e4425dda0b38990ef97d58c959e8a4cea6)
- [docs(rbac): Removing Janus IDP dynamic plugin installation instructions, switching to relative paths for doc links
](https://github.com/backstage/community-plugins/commit/aec6bc20d71f3d93d2094717d845f1adfc145f1c)
- [removed shared-react dependencies
](https://github.com/backstage/community-plugins/commit/ac39bffb727e994bcf9b90db8a8ae257ab8a0640)
- [Fix to remove entire permission when no policy is selected.
](https://github.com/backstage/community-plugins/commit/4719a0ee7fe3b3c85a8a527f8e3df17877a9f83a:)
When a first-time user visits the site, the drawer is being opened …
=> chore: update rbac and quickstart

catalog-entities/marketplace/packages/red-hat-developer-hub-backstage-plugin-lightspeed-backend.yaml, catalog-entities/marketplace/packages/red-hat-developer-hub-backstage-plugin-lightspeed.yaml, catalog-entities/marketplace/plugins/lightspeed.yaml, dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace/package.json, dynamic-plugins/yarn.lock, e2e-tests/playwright/e2e/extensions.spec.ts
Updated Developer Lightspeed images to use official 1.7 OCI images rather than using `next` image tags and Updated extensions frontend plugin.
- Fixes 
https://issues.redhat.com/browse/RHIDP-8359
=> [release-1.7] fix(lightspeed): update lightspeed plugins image and add installation section

catalog-entities/marketplace/packages/red-hat-developer-hub-backstage-plugin-lightspeed-backend.yaml, catalog-entities/marketplace/packages/red-hat-developer-hub-backstage-plugin-lightspeed.yaml, catalog-entities/marketplace/plugins/lightspeed.yaml, dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace/package.json, dynamic-plugins/yarn.lock, e2e-tests/playwright/e2e/extensions.spec.ts
Updated Developer Lightspeed images to use official 1.7 OCI images rather than using `next` image tags and Updated extensions frontend plugin.
- Fixes 
https://issues.redhat.com/browse/RHIDP-8359
=> fix(lightspeed): update lightspeed plugins image and add installation section

e2e-tests/playwright/e2e/plugins/kubernetes-actions/kubernetes-actions.spec.ts, e2e-tests/playwright/utils/common.ts
After adding a wait between steps, the test always passes on the first try. See [results](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/redhat-developer_rhdh/3226/pull-ci-redhat-developer-rhdh-release-1.7-e2e-tests/1950822095625654272/artifacts/e2e-tests/redhat-developer-rhdh/artifacts/showcase/index.html#?testId=cdd9937dac5c40254281-5934b1962f9d20c5c33b)
- Fixes https://issues.redhat.com/browse/RHDHBUGS-1912
=> chore(e2e): fix Kubernetes Actions plugin by adding wait

docs/customization.md, docs/dynamic-plugins/frontend-plugin-wiring.md, packages/app/config.d.ts, packages/app/src/components/DynamicRoot/DynamicRoot.tsx, packages/app/src/components/DynamicRoot/ScalprumRoot.tsx, packages/app/src/types/types.ts, packages/app/src/utils/dynamicUI/extractDynamicConfig.test.ts, packages/app/src/utils/dynamicUI/extractDynamicConfig.ts
This PR adds the following:
- A new dynamic plugins extension point, `translationResources`, which accepts an array of translation resources
- A new `i18n` config field in `app-config.yaml`, allowing users to define the list of locales supported by the app
- Fixes https://issues.redhat.com/browse/RHIDP-8261
In app-config.yaml
- Add the `i18n` configuration
```
i18n:
locales:
- en
- de
- fr
- it
- ja
- ko
- en-US
- en-IN
- en-UK
- zh
- pt-BR
- zh-CN
defaultLocale: en
```
- Add the dynamic plugin configuration for npm plugin (https://github.com/redhat-developer/rhdh-plugin-export-overlays/pull/948#issuecomment-2839434956 , https://github.com/backstage/community-plugins/pull/5020)
```
rootDirectory: dynamic-plugins-root …
```
=> feat(i18n): enable localization framework in RHDH

.gitignore, .ibm/pipelines/cleanup.sh, .ibm/pipelines/env_variables.sh, .ibm/pipelines/jobs/ocp-nightly.sh, .ibm/pipelines/openshift-ci-tests.sh, .ibm/pipelines/reporting.sh, .ibm/pipelines/utils.sh
Use `nounset` to make sure all env vars in CI are populated. This prevents issues where tests started to fail because an env var was not set. This was the case with tests different than the usual Helm on OCP.
For local development, store the `SHARED_DIR` and `ARTIFACT_DIR` in a git-ignored directory.
Refactor `openshift-ci-tests.sh` with conditional sourcing for jobs and proper ShellCheck sourcing.
Refactor GKE cleanup.
Introduce gitignored `env_override.local.sh` to enable easier local testing and limit the chances of accidentally committing an override.
- Part of https://issues.redhat.com/browse/RHIDP-6736
=> chore(ci): use nounset for CI scripts

e2e-tests/playwright/e2e/plugins/bulk-import.spec.ts, e2e-tests/playwright/support/pages/bulk-import.ts, e2e-tests/playwright/utils/api-helper.ts, e2e-tests/playwright/utils/ui-helper.ts
The bulk import test was using a manually defined GitHub repository, which caused issues with retries. Now they are defined dynamically so that retries are allowed. That should lead to a higher success rate with Bulk Import tests.
- Fixes https://issues.redhat.com/browse/RHIDP-8817
=> chore(e2e): retries for bulk import test

docs/customization.md, packages/app/config.d.ts, packages/app/src/apis.ts, packages/app/src/components/DynamicRoot/DynamicRoot.tsx, packages/app/src/components/Root/Root.tsx, packages/app/src/hooks/useLanguagePreference.test.ts, packages/app/src/hooks/useLanguagePreference.ts, packages/app/src/types/types.ts, packages/app/src/utils/language/language.test.ts, packages/app/src/utils/language/language.ts, packages/backend/package.json, packages/backend/src/index.ts, packages/backend/src/modules/userSettings.ts, yarn.lock
Implements bidirectional synchronization of language preferences between the app's language API and user storage, ensuring language settings persist across browser sessions for authenticated users.
- Added `@backstage/plugin-user-settings-backend` dependency to enable persistent user settings storage
- Integrated user settings backend plugin with conditional loading based on persistence configuration
- Created `useLanguagePreference` hook with comprehensive bidirectional sync logic
- Automatically detect browser's language settings to use it as a default lanaguage.
- Added extensive test coverage covering all edge cases
- Integrated hook into Root component to enable automatic language preference persistence
- Added configuration validation and database persistence checks
- Added …
=> feat(i18n): add peristant language preference sync for authenticated users

docs/e2e-tests/e2e-i18n-guide.md
This PR adds a comprehensive guide `e2e-i18n-guide.md` explaining how internationalization (i18n) is integrated into our Playwright-based end-to-end (E2E) tests.
Key highlights include:
- Overview of the project structure for translations.
- Sample translation files (`en.ts`, `fr.ts`, `de.ts`) showing language-specific UI strings.
- Translation loader (`index.ts`) for selecting the active locale based on an environment variable.
- Before-and-after examples demonstrating how to replace hardcoded UI text with translation keys in tests.
- Instructions on running tests in different languages using the `LOCALE` environment variable.
- Benefits of adopting i18n in tests for maintainability, scalability, and multilingual coverage.
This guide will help contributors write language-agnostic tests …
=> docs: add i18n guide for Playwright E2E tests

.github/workflows/update-rpm-lockfile.yaml
Fixes the workflow to actually run the rpm lock update command 
- Fixes [RHIDP-8905](https://issues.redhat.com/browse/RHIDP-8905)?
=> fix: fix rpm lock update to actually run the command

dynamic-plugins/yarn.lock, yarn.lock
Bumps axois to 1.12.2 to resolve CVE-2025-58754
Fixes [RHIDP-8962](https://issues.redhat.com/browse/RHIDP-8962)
=> chore: update axios to fix CVE-2025-58754

dynamic-plugins/yarn.lock, yarn.lock
Bumps axois to 1.12.2 to resolve CVE-2025-58754
- Fixes [RHIDP-8962](https://issues.redhat.com/browse/RHIDP-8962)
=> [release-1.7] chore: update axios to fix CVE-2025-58754
